/**
 * Assessment Entity - Public API
 * Central export point for all assessment entity functionality
 */

// Model exports
export type {
  GradeLevel,
  StreamCategory,
  QuestionType,
  AttemptStatus,
  AssessmentFlowStatus,
  Question,
  ResponseScaleOption,
  AssessmentSection,
  SJTAnswer,
  AnswerValue,
  Answers,
  SectionTimings,
  AssessmentAttempt,
  RIASECScores,
  AptitudeScore,
  AptitudeScores,
  BigFiveScores,
  EmployabilityScores,
  CareerClusterEvidence,
  CareerCluster,
  CareerFitResult,
  SkillGapItem,
  RoadmapStep,
  StreamRecommendation,
  CourseRecommendation,
  AdaptiveAptitudeResult,
  AssessmentResults,
  AssessmentFlowState,
  AssessmentEligibility,
  CollegeAssessment,
  AssessmentType,
  AssessmentMapping,
  LearnerInfo,
  SubjectMark,
  AssessmentResult
} from './model';

export {
  isValidGradeLevel,
  isValidStreamCategory,
  validateAssessmentAttempt,
  validateQuestion,
  validateAssessmentSection,
  validateAnswer,
  validateScore,
  validatePercentage,
  getGradeLevelDisplayName,
  getGradeRange,
  getTopRIASECCodes,
  getRIASECCodeName,
  getRIASECCodeDescription,
  getAptitudeDisplayName,
  getTopAptitudes,
  calculateOverallAptitudeScore,
  getCareerFitLevel,
  sortCareerClustersByMatch,
  filterHighMatchCareers,
  hasCompletedAssessment,
  getAssessmentCompletionPercentage,
  extractKeyInsights,
  calculateAttemptDuration,
  isAttemptExpired,
  canResumeAttempt,
  formatScore,
  formatPercentage,
  calculatePercentage,
  formatDuration,
  formatTimeRemaining
} from './model';
