SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- \restrict wXC3zDVw9heTfCWfOmi2hLYIKXMGkIFyykgkgWPlYFZ90Xj8yWFCDwB1hKgN4eJ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: quizzes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO "public"."quizzes" ("quiz_id", "lesson_id", "title", "description", "passing_score", "time_limit_seconds", "max_attempts", "questions", "is_active", "created_at", "updated_at") VALUES
	('11111111-1111-1111-1111-111111111111', '5317fb02-8b75-4d5c-8fb0-2ce918f4c707', 'What is Blockchain? Quiz', 'Test your understanding of blockchain fundamentals', 70, 300, 3, '[{"id": "q1", "type": "multiple_choice", "options": ["A centralized database managed by a single entity", "A distributed ledger that records transactions across many computers", "A type of cryptocurrency", "A programming language"], "question": "What is a blockchain?", "explanation": "A blockchain is a distributed ledger technology that records transactions across multiple computers in a way that makes it nearly impossible to alter retroactively.", "correct_answer": 1}, {"id": "q2", "type": "multiple_choice", "options": ["Vitalik Buterin", "Elon Musk", "Satoshi Nakamoto", "Mark Zuckerberg"], "question": "Who created Bitcoin and the first blockchain?", "explanation": "Satoshi Nakamoto is the pseudonymous person or group who created Bitcoin and authored its original whitepaper in 2008.", "correct_answer": 2}, {"id": "q3", "type": "multiple_choice", "options": ["2005", "2009", "2012", "2015"], "question": "What year was the first Bitcoin block (Genesis Block) created?", "explanation": "The Genesis Block (Block 0) was created on January 3, 2009, marking the birth of the Bitcoin blockchain.", "correct_answer": 1}, {"id": "q4", "type": "multiple_choice", "options": ["Decentralization", "Immutability", "Centralized control", "Transparency"], "question": "Which of the following is NOT a characteristic of blockchain?", "explanation": "Blockchain is characterized by decentralization, not centralized control. It operates without a single point of authority.", "correct_answer": 2}, {"id": "q5", "type": "multiple_choice", "options": ["Slow internet speeds", "The double-spending problem", "Computer viruses", "Data storage limitations"], "question": "What problem does blockchain technology primarily solve?", "explanation": "Blockchain solves the double-spending problem by ensuring that digital assets cannot be spent twice without the need for a trusted intermediary.", "correct_answer": 1}]', true, '2025-12-24 08:46:40.842997+00', '2025-12-24 08:46:40.842997+00'),
	('22222222-2222-2222-2222-222222222222', '8f9e930f-7cb7-4c75-95a0-ee37652b08fc', 'Centralized vs Decentralized Networks Quiz', 'Test your knowledge of network architectures', 70, 300, 3, '[{"id": "q1", "type": "multiple_choice", "options": ["All participants equally", "A single authority or entity", "No one", "Random nodes"], "question": "In a centralized network, who controls the data?", "explanation": "In centralized networks, a single authority (like a company or government) controls all the data and operations.", "correct_answer": 1}, {"id": "q2", "type": "multiple_choice", "options": ["Faster processing speed", "Lower cost", "No single point of failure", "Easier to manage"], "question": "What is a key advantage of decentralized networks?", "explanation": "Decentralized networks have no single point of failure, making them more resilient to attacks and outages.", "correct_answer": 2}, {"id": "q3", "type": "multiple_choice", "options": ["Bitcoin", "Traditional banking", "Ethereum", "BitTorrent"], "question": "Which is an example of a centralized system?", "explanation": "Traditional banking is centralized - banks control your money and can freeze accounts, reverse transactions, etc.", "correct_answer": 1}, {"id": "q4", "type": "multiple_choice", "options": ["Point to Point", "Peer to Peer", "Protocol to Protocol", "Private to Public"], "question": "What does P2P stand for in blockchain context?", "explanation": "P2P stands for Peer-to-Peer, meaning nodes in the network communicate directly with each other without intermediaries.", "correct_answer": 1}, {"id": "q5", "type": "multiple_choice", "options": ["Too much security", "Scalability issues", "Too transparent", "Too cheap to operate"], "question": "What is a potential challenge of decentralized networks?", "explanation": "Scalability is a major challenge for decentralized networks as they need consensus among many nodes, which can slow down transaction processing.", "correct_answer": 1}]', true, '2025-12-24 08:46:40.842997+00', '2025-12-24 08:46:40.842997+00'),
	('33333333-3333-3333-3333-333333333333', 'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d', 'Block Creation Quiz', 'Test your understanding of how blocks are created', 70, 300, 3, '[{"id": "q1", "type": "multiple_choice", "options": ["A type of cryptocurrency", "A random number used once in mining", "A block header", "A transaction fee"], "question": "What is a nonce in blockchain?", "explanation": "A nonce (number used once) is a random number that miners change to find a valid hash that meets the difficulty target.", "correct_answer": 1}, {"id": "q2", "type": "multiple_choice", "options": ["Physical cables", "The hash of the previous block", "Timestamps only", "User signatures"], "question": "What links blocks together in a blockchain?", "explanation": "Each block contains the cryptographic hash of the previous block, creating an unbreakable chain.", "correct_answer": 1}, {"id": "q3", "type": "multiple_choice", "options": ["Staking", "Mining", "Forging", "Validating"], "question": "What is the process of creating new blocks called?", "explanation": "Mining is the process of creating new blocks by solving complex mathematical puzzles (in Proof of Work systems).", "correct_answer": 1}, {"id": "q4", "type": "multiple_choice", "options": ["Only transaction data", "Previous block hash, timestamp, nonce, and merkle root", "User passwords", "Mining software version"], "question": "What information is typically stored in a block header?", "explanation": "Block headers contain metadata including the previous block hash, timestamp, nonce, difficulty target, and merkle root of transactions.", "correct_answer": 1}, {"id": "q5", "type": "multiple_choice", "options": ["They are encrypted", "Changing one block would require recalculating all subsequent blocks", "They are stored in multiple locations", "Government regulations prevent it"], "question": "Why is it nearly impossible to alter past blocks?", "explanation": "Due to the chain of hashes, altering any block would change its hash, breaking the link to the next block and requiring recalculation of all subsequent blocks.", "correct_answer": 1}]', true, '2025-12-24 08:46:40.842997+00', '2025-12-24 08:46:40.842997+00'),
	('44444444-4444-4444-4444-444444444444', 'b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e', 'Consensus Mechanisms Quiz', 'Test your knowledge of PoW and PoS', 70, 300, 3, '[{"id": "q1", "type": "multiple_choice", "options": ["Proof of Stake", "Proof of Work", "Delegated Proof of Stake", "Proof of Authority"], "question": "What consensus mechanism does Bitcoin use?", "explanation": "Bitcoin uses Proof of Work (PoW), where miners compete to solve complex mathematical puzzles.", "correct_answer": 1}, {"id": "q2", "type": "multiple_choice", "options": ["Too secure", "High energy consumption", "Too fast", "Not decentralized enough"], "question": "What is a major criticism of Proof of Work?", "explanation": "PoW requires enormous computational power, leading to high energy consumption and environmental concerns.", "correct_answer": 1}, {"id": "q3", "type": "multiple_choice", "options": ["Computing power", "Amount of cryptocurrency staked", "First come, first served", "Random selection only"], "question": "In Proof of Stake, what determines who validates the next block?", "explanation": "In PoS, validators are chosen based on the amount of cryptocurrency they have staked as collateral.", "correct_answer": 1}, {"id": "q4", "type": "multiple_choice", "options": ["Bitcoin", "Ethereum", "Litecoin", "Dogecoin"], "question": "Which blockchain transitioned from PoW to PoS?", "explanation": "Ethereum completed its transition from PoW to PoS in September 2022 with The Merge.", "correct_answer": 1}, {"id": "q5", "type": "multiple_choice", "options": ["Reducing transaction fees", "Penalty for malicious behavior where staked tokens are destroyed", "Splitting blocks", "Reducing block size"], "question": "What is slashing in Proof of Stake?", "explanation": "Slashing is a penalty mechanism where validators lose part of their staked tokens if they act maliciously or fail to validate properly.", "correct_answer": 1}]', true, '2025-12-24 08:46:40.842997+00', '2025-12-24 08:46:40.842997+00'),
	('55555555-5555-5555-5555-555555555555', 'c3d4e5f6-a7b8-6c7d-0e1f-2a3b4c5d6e7f', 'Blockchain Cryptography Quiz', 'Test your understanding of cryptographic concepts', 70, 300, 3, '[{"id": "q1", "type": "multiple_choice", "options": ["MD5", "SHA-256", "SHA-1", "AES"], "question": "What hash function does Bitcoin primarily use?", "explanation": "Bitcoin uses SHA-256 (Secure Hash Algorithm 256-bit) for its proof-of-work and transaction verification.", "correct_answer": 1}, {"id": "q2", "type": "multiple_choice", "options": ["They are reversible", "Same input always produces different output", "Small input changes produce completely different outputs", "They can only hash numbers"], "question": "What is a key property of cryptographic hash functions?", "explanation": "Hash functions exhibit the avalanche effect - even a tiny change in input produces a completely different hash output.", "correct_answer": 2}, {"id": "q3", "type": "multiple_choice", "options": ["Signing transactions", "Receiving cryptocurrency (as an address)", "Mining blocks", "Storing passwords"], "question": "What is a public key used for in blockchain?", "explanation": "Public keys (or addresses derived from them) are used to receive cryptocurrency. They can be shared publicly.", "correct_answer": 1}, {"id": "q4", "type": "multiple_choice", "options": ["Your public key", "Your wallet address", "Your private key", "Your transaction history"], "question": "What should you NEVER share with anyone?", "explanation": "Private keys must be kept secret. Anyone with your private key can access and spend your cryptocurrency.", "correct_answer": 2}, {"id": "q5", "type": "multiple_choice", "options": ["The transaction amount", "The sender owns the private key and authorized the transaction", "The block number", "The network speed"], "question": "What does a digital signature prove?", "explanation": "Digital signatures prove that the owner of the private key authorized the transaction, providing authentication and non-repudiation.", "correct_answer": 1}]', true, '2025-12-24 08:46:40.842997+00', '2025-12-24 08:46:40.842997+00');


--
