// College Admin Feature - Public API
export * from './ui';

// Default export for Header component (using educator Header)
export { default as Header } from '@/features/educator/ui/Header';

// API & Data Access
export * from './api';

export * from './model';

// Lib utilities
export * from './lib';
export { collegeTimetablesService } from './api/collegeTimetablesService';
export type { OverdueBook } from './api/LibraryServicetest';
export { createClass } from './api/classService';
export type { AttendanceSession } from './model/attendance-types';
export type { LibraryBook } from './api/libraryService';
export { adminApproveSwapRequest } from './api/classSwapService';
export { autoMapHeaders } from './api/csvImportService';
export { addStudentToClass } from './api/classService';
export { removeStudentFromProgram } from './api/programService';
export { circularService } from './api/circularService';
export type { ValidatedRow } from './api/csvImportService';
export { curriculumApprovalService } from './api/curriculumApprovalService';
export { getStudents } from './api/mentorAllocationService';
export type { EducatorClass } from './api/classService';
export { getCollegeStudentAssignmentStats } from './api/collegeAssignmentService';
export type { Department } from './api/collegeAssignmentService';
export { getDepartments } from './api/mentorAllocationService';
export { getPrograms } from './api/mentorAllocationService';
export type { Student } from './api/mentorAllocationService';
export type { StudentDirectoryEntry } from './api/classService';
export { getCollegeStudentClassInfo } from './api/collegeClassService';
export type { AttendanceRecord } from './model/attendance-types';
export { collegeLecturersService } from './api/collegeLecturersService';
export type { CollegeStudentAssignment } from './api/collegeAssignmentService';
export { createProgramSection } from './api/programService';
export { getCollegeLecturerProgramSections } from './api/programService';
export type { CollegeAssignmentStats } from './api/collegeAssignmentService';
export { getAssignmentStatistics } from './api/collegeAssignmentService';
export type { ExpenditureSummary } from './api/financeService';
export { exportCurriculum } from './api/curriculumExportService';
export { createMentorAllocations } from './api/mentorAllocationService';
export { updateMentorNoteResponse } from './api/mentorAllocationService';
export { getMentors } from './api/mentorAllocationService';
export type { CircularsFilters } from './api/circularsService';
export { collegeEventsService } from './api/collegeEventsService';
export type { CollegeClassmate } from './api/collegeClassService';
export { updateMentorAllocation } from './api/mentorAllocationService';
export { getCollegeSwapStatistics } from './api/classSwapService';
export type { MentorAllocation } from './api/mentorAllocationService';
export { createMentorPeriod } from './api/mentorAllocationService';
export { useCurriculum } from './model/useCurriculum';
export { lessonPlanService } from './api/lessonPlanService';
export type { Program } from './api/collegeAssignmentService';
export type { Course } from './api/collegeAssignmentService';
export { escalateNote } from './api/mentorAllocationService';
export type { CreateCircularData } from './api/circularService';
export { curriculumChangeRequestService } from './api/curriculumChangeRequestService';
export { getCollegeDepartments } from './api/programService';
export { deleteAssignment } from './api/collegeAssignmentService';
export { removeStudentFromClass } from './api/classService';
export { addStudentToProgram } from './api/programService';
export { getCollegeSwapRequestsWithDetails } from './api/classSwapService';
export type { CurriculumApprovalDashboard } from './api/curriculumApprovalService';
export { getAvailableSlotsForSwap } from './api/classSwapService';
export type { CurriculumUnit } from './api/curriculumService';
export type { SubjectGroup } from './model/attendance-types';
export { createSwapRequest } from './api/classSwapService';
export { getPendingSwapCount } from './api/classSwapService';
export type { CollegeClassInfo } from './api/collegeClassService';
export { organizationsService } from './api/organizationsService';
export type { MentorPeriod } from './api/mentorAllocationService';
export type { LibraryStats } from './api/LibraryServicetest';
export { default as factoryVisitsService } from './api/factoryVisitsService';
export { unassignLecturerFromProgramSection } from './api/programService';
export { assignTaskToClass } from './api/classService';
export { fetchStudentDirectory } from './api/classService';
export { collegeTimetableSlotsService } from './api/collegeTimetableSlotsService';
export type { CollegeLessonPlan } from './api/lessonPlanService';
export { getAvailableStudentsForProgram } from './api/programService';
export { createMentorNote } from './api/mentorAllocationService';
export { collegeBreaksService } from './api/collegeBreaksService';
export type { CurriculumOutcome } from './api/curriculumService';
export { updateClass } from './api/classService';
export { getMentorPeriods } from './api/mentorAllocationService';
export { getMentorAllocations } from './api/mentorAllocationService';
export { collegeFacultyLeavesService } from './api/collegeFacultyLeavesService';
export type { ProgramStudent } from './api/programService';
export { fetchCollegeStudentAssignments } from './api/collegeAssignmentService';
export { fetchEducatorClasses } from './api/classService';
export { getSwapRequests } from './api/classSwapService';
export { collegeFacultySubstitutionsService } from './api/collegeFacultySubstitutionsService';
export type { LibrarySetting } from './api/LibraryServicetest';
export { collegeEventRegistrationsService } from './api/collegeEventRegistrationsService';
export { resolveNote } from './api/mentorAllocationService';
export type { DepartmentWithStats } from './api/departmentService';
export { updateMentorPeriod } from './api/mentorAllocationService';
export { getStudentsByProgramSection } from './api/programService';
export { submitCollegeAssignment } from './api/collegeAssignmentService';
export type { LibraryBookIssue } from './api/LibraryServicetest';
export type { Faculty } from './api/courseMappingService';
export type { MentorNote } from './api/mentorAllocationService';
export type { CourseMapping } from './api/courseMappingService';
export { getCollegeClassmates } from './api/collegeClassService';
export type { ProgramExpenditure } from './api/financeService';
export type { Circular } from './api/circularService';
export { updateCollegeStudentAssignmentStatus } from './api/collegeAssignmentService';
export { getFaculty } from './api/facultyService';
export { findAllocationId } from './api/mentorAllocationService';
export type { ImportSummary } from './api/csvImportService';
export { getMentorNotes } from './api/mentorAllocationService';
export { updateMentorNoteFeedback } from './api/mentorAllocationService';
export type { ProgramSection } from './api/collegeAssignmentService';
export type { DepartmentExpenditure } from './api/financeService';
export type { Mentor } from './api/mentorAllocationService';
export type { AssignmentFileUpload } from './ui/AssignmentFileUpload';
export type { MANDATORY_FIELDS } from './api/csvImportService';
export type { ManageStudentsModal } from './ui/modals/ManageStudentsModal';
export type { ManageProgramStudentsModal } from './ui/modals/ManageProgramStudentsModal';
export type { AddStudentModal } from './ui/AddStudentModal';
export type { MentorResponseModal } from './ui/modals/MentorResponseModal';
export type { getStudentTypeInfo } from './api/collegeClassService';
export type { StudentSelectionModal } from './ui/StudentSelectionModal';
export { default as SwapRequestCard } from './ui/SwapRequestCard';
export type { CollegeAdminNotificationService } from './api/collegeAdminNotificationService';
export type { SwapRequestModal } from './ui/modals/SwapRequestModal';
