/**
 * Generate Embedding Handler - Proxy to Cloudflare embedding-api worker
 * 
 * Features:
 * - Routes embedding requests to dedicated embedding-api worker
 * - Worker handles OpenRouter API calls and caching
 * - Supports both direct generation and database updates
 * 
 * Configuration:
 * - Set EMBEDDING_API_URL or VITE_EMBEDDING_API_URL environment variable
 * - Example: https://embedding-api.dark-mode-d021.workers.dev
 */

import { jsonResponse } from '../../../../src/functions-lib/response';
import { authenticateUser, isValidUUID } from '../../shared/auth';
import { checkRateLimit } from '../utils/rate-limit';

interface GenerateEmbeddingRequest {
  text: string;
  table: string;
  id: string;
  type?: 'opportunity' | 'student';
  returnEmbedding?: boolean;
}

export async function handleGenerateEmbedding(request: Request, env: Record<string, string>): Promise<Response> {
  if (request.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  const auth = await authenticateUser(request, env);
  if (!auth) {
    return jsonResponse({ error: 'Authentication required' }, 401);
  }

  const { user } = auth;
  const studentId = user.id;

  if (!checkRateLimit(studentId)) {
    return jsonResponse({ error: 'Rate limit exceeded' }, 429);
  }

  let body: GenerateEmbeddingRequest;
  try {
    body = await request.json() as GenerateEmbeddingRequest;
  } catch {
    return jsonResponse({ success: false, error: 'Invalid JSON' }, 400);
  }

  const { text, table, id, type = 'opportunity', returnEmbedding = false } = body;

  if (!text || !table || !id) {
    return jsonResponse({
      success: false,
      error: 'Missing required parameters: text, table, id'
    }, 400);
  }

  const allowedTables = ['opportunities', 'students', 'profiles', 'courses'];
  if (!allowedTables.includes(table)) {
    return jsonResponse({
      success: false,
      error: `Invalid table. Allowed tables: ${allowedTables.join(', ')}`
    }, 400);
  }

  if (!isValidUUID(id)) {
    return jsonResponse({
      success: false,
      error: 'Invalid id format. Must be a valid UUID.'
    }, 400);
  }

  console.log(`Proxying embedding request for ${type} #${id} to embedding-api worker`);

  try {
    // Get embedding API URL from environment
    const embeddingApiUrl = env.EMBEDDING_API_URL || env.VITE_EMBEDDING_API_URL;

    if (!embeddingApiUrl) {
      return jsonResponse({
        success: false,
        error: 'Embedding API URL not configured. Set EMBEDDING_API_URL or VITE_EMBEDDING_API_URL environment variable.'
      }, 500);
    }

    // Call the embedding-api worker
    const workerResponse = await fetch(`${embeddingApiUrl}/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text,
        id,
        table,
      }),
    });

    if (!workerResponse.ok) {
      const errorText = await workerResponse.text();
      console.error(`Embedding API worker error: ${workerResponse.status} - ${errorText}`);
      return jsonResponse({
        success: false,
        error: `Embedding API error: ${workerResponse.status}`
      }, workerResponse.status);
    }

    const workerData = await workerResponse.json() as any;

    // If returnEmbedding is requested, we'd need to fetch it from the database
    // since the worker doesn't return the actual embedding in the response
    if (returnEmbedding) {
      console.log('⚠️ returnEmbedding flag requires fetching from database after worker updates it');
      // For now, just return success with dimensions
      return jsonResponse({
        success: true,
        message: 'Embedding generated by worker. Use database query to retrieve it.',
        dimensions: workerData.dimensions || 1536
      });
    }

    console.log(`✅ Successfully generated embedding via worker for ${table} #${id}`);

    return jsonResponse({
      success: true,
      message: `Embedding generated for ${type} #${id}`,
      dimensions: workerData.dimensions || 1536,
      model: workerData.model || 'openrouter'
    });

  } catch (error) {
    console.error('Error proxying to embedding-api worker:', error);
    return jsonResponse({
      success: false,
      error: (error as Error).message || 'Unknown error generating embedding'
    }, 500);
  }
}
