#!/usr/bin/env tsx
/**
 * Update All Component Imports
 * 
 * Updates all imports from @/components/ to their new FSD locations
 * using the migration map generated by auto-migrate-all-components.ts
 */

import { glob } from 'glob';
import * as fs from 'fs';
import * as path from 'path';

interface Migration {
  source: string;
  target: string;
}

async function updateAllImports(): Promise<void> {
  console.log('🔄 Updating all component imports...\n');

  // Load migration map
  const migrationMapPath = 'src/migration/data/component-migrations.json';
  if (!fs.existsSync(migrationMapPath)) {
    console.error('❌ Migration map not found. Run auto-migrate-all-components.ts first.');
    process.exit(1);
  }

  const migrations: Migration[] = JSON.parse(fs.readFileSync(migrationMapPath, 'utf-8'));

  // Build import path mappings
  const importMappings = migrations.map(m => {
    // Convert file paths to import paths
    const oldImport = m.source
      .replace(/^src\//, '@/')
      .replace(/\.(tsx|jsx|ts|js)$/, '')
      .replace(/\/index$/, '');
    
    const newImport = m.target
      .replace(/^src\//, '@/')
      .replace(/\.(tsx|jsx|ts|js)$/, '')
      .replace(/\/index$/, '');

    return { oldImport, newImport };
  });

  // Get all source files
  const files = await glob('src/**/*.{ts,tsx,js,jsx}', {
    ignore: ['**/node_modules/**', '**/dist/**', '**/components/**']
  });

  let filesUpdated = 0;
  let importsUpdated = 0;

  for (const file of files) {
    let content = fs.readFileSync(file, 'utf-8');
    let fileModified = false;
    const originalContent = content;

    for (const mapping of importMappings) {
      // Match various import patterns
      const patterns = [
        // import X from '@/components/...'
        new RegExp(`from ['"]${mapping.oldImport.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}['"]`, 'g'),
        // import('@/components/...')
        new RegExp(`import\\(['"]${mapping.oldImport.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}['"]\\)`, 'g'),
      ];

      for (const pattern of patterns) {
        if (pattern.test(content)) {
          const replacement = pattern.source.includes('import\\(') 
            ? `import('${mapping.newImport}')`
            : `from '${mapping.newImport}'`;
          
          content = content.replace(pattern, replacement);
          fileModified = true;
          importsUpdated++;
        }
      }
    }

    if (fileModified && content !== originalContent) {
      fs.writeFileSync(file, content);
      filesUpdated++;
      console.log(`✅ Updated: ${file}`);
    }
  }

  console.log('\n' + '='.repeat(80));
  console.log(`\n📊 Update Summary:`);
  console.log(`   📝 Files updated: ${filesUpdated}`);
  console.log(`   🔗 Imports updated: ${importsUpdated}`);
  console.log('\n✨ Import update complete!');
  console.log('\n⚠️  Next step: Run verify-legacy-imports.ts to confirm zero legacy imports');
}

updateAllImports().catch(console.error);
