// College Admin UI Components
export { default as AddDepartmentModal } from './AddDepartmentModal';
export { default as AddStudentModal } from './modals/AddStudentModal';
export { default as AllocationConfigurationModal } from './AllocationConfigurationModal';
export { default as AssignmentFileUpload } from './AssignmentFileUpload';
export { default as BulkDeleteStudentsModal } from './modals/BulkDeleteStudentsModal';
export { default as CollegeCurriculumBuilderUI } from './CollegeCurriculumBuilderUI';
export { default as CollegeLessonPlanUI } from './CollegeLessonPlanUI';
export { default as CourseMappingModal } from './CourseMappingModal';
export { default as CreateCircularModal } from './CreateCircularModal';
export { default as DeleteStudentModal } from './modals/DeleteStudentModal';
export { default as DepartmentDetailsDrawer } from './DepartmentDetailsDrawer';
export { default as EditDepartmentModal } from './EditDepartmentModal';
export { default as EditStudentModal } from './modals/EditStudentModal';
// export { default as EnrollStudentModal } from './EnrollStudentModal'; // File missing
export { default as FacultyAssignmentModal } from './FacultyAssignmentModal';
export { default as HODAssignmentModal } from './HODAssignmentModal';
export { default as InterventionFeedbackModal } from './InterventionFeedbackModal';
export { default as InterventionModal } from './InterventionModal';
export { default as ManageProgramStudentsModal } from './modals/ManageProgramStudentsModal';
export { ManageStudentsModal, AssignEducatorModal } from './modals/ClassManagementModals';
export { default as MentorCapacityModal } from './MentorCapacityModal';
export { default as MentorDetailsModal } from './MentorDetailsModal';
export { default as MentorResponseModal } from './modals/MentorResponseModal';
export { default as MentorSelectionModal } from './MentorSelectionModal';
export { default as NewCollegeAdminConversationModal } from './NewCollegeAdminConversationModal';
export { default as NewCollegeAdminEducatorConversationModal } from './NewCollegeAdminEducatorConversationModal';
export { default as ReassignModal } from './ReassignModal';
export { default as StudentSelectionModal } from './StudentSelectionModal';
export { default as SwapRequestCard } from './SwapRequestCard';
export { default as SwapRequestModal } from './modals/SwapRequestModal';
export { default as FacultyDocumentViewerModal } from './modals/FacultyDocumentViewerModal';
