-- =============================================================================
-- RIASEC Assessment Seed
-- Section: grade_level = 'general' (shared across after10, after12, college)
-- Questions: 48 total, category_mapping stores riasec type + applicable_grades
-- Note: Section ID is explicit so questions can reference it via section_id FK.
--       Question IDs are auto-generated by the table (gen_random_uuid()).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Section row (explicit ID needed as FK anchor for questions)
-- -----------------------------------------------------------------------------
INSERT INTO "public"."personal_assessment_sections" (
  "id",
  "name",
  "title",
  "description",
  "icon",
  "color",
  "order_number",
  "is_timed",
  "time_limit_seconds",
  "instruction",
  "response_scale",
  "is_stream_specific",
  "is_active",
  "grade_level"
) VALUES (
  'a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6',
  'riasec',
  'Career Interests (RIASEC)',
  'Discover your career interests based on Holland''s RIASEC model.',
  'compass',
  'blue',
  1,
  true,
  1800,
  'Rate how much you would LIKE or DISLIKE each activity. There are no right or wrong answers.',
  '{"type":"likert5","values":[{"value":1,"label":"Strongly Dislike"},{"value":2,"label":"Dislike"},{"value":3,"label":"Neutral"},{"value":4,"label":"Like"},{"value":5,"label":"Strongly Like"}]}',
  false,
  true,
  'general'
) ON CONFLICT (id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- 2. Questions (48 rows, IDs auto-generated)
--    category_mapping = { "type": "R|I|A|S|E|C", "category": "...",
--                         "applicable_grades": ["after10","after12","college"] }
-- -----------------------------------------------------------------------------
INSERT INTO "public"."personal_assessment_questions" (
  "section_id",
  "stream_id",
  "question_text",
  "question_type",
  "order_number",
  "is_active",
  "category_mapping",
  "metadata"
) VALUES

-- R – Realistic (8 questions)
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy repairing broken appliances or devices.', 'likert', 1, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like building things using basic tools (wood, metal, electronics).', 'likert', 2, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'Operating machines or technical equipment appeals to me.', 'likert', 3, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy working on projects that involve physical activity.', 'likert', 4, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like assembling or installing parts to make something work.', 'likert', 5, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer doing fieldwork outside a classroom or office.', 'likert', 6, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy troubleshooting hardware problems.', 'likert', 7, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer learning by doing rather than reading or listening.', 'likert', 8, true, '{"type":"R"}', '{"applicable_grades":["after10","after12","college"]}'),

-- I – Investigative (8 questions)
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy solving tough math or logic problems for fun.', 'likert', 9, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like exploring why something works the way it does.', 'likert', 10, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I read or watch science and tech content beyond what is required in class.', 'likert', 11, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy designing experiments or testing new ideas.', 'likert', 12, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like working with data to find patterns and trends.', 'likert', 13, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy tasks that require deep concentration and focus.', 'likert', 14, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like investigating real-world problems step by step.', 'likert', 15, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer evidence before believing a claim or idea.', 'likert', 16, true, '{"type":"I"}', '{"applicable_grades":["after10","after12","college"]}'),

-- A – Artistic (8 questions)
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy creating artwork, music, content, or performances.', 'likert', 17, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like thinking of unique ways to present ideas.', 'likert', 18, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy writing stories, poems, scripts, or social media posts.', 'likert', 19, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer open-ended tasks over tasks with fixed rules.', 'likert', 20, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like experimenting with colors, visuals, or style.', 'likert', 21, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy brainstorming fresh and original concepts.', 'likert', 22, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I notice design and beauty in everyday things.', 'likert', 23, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like expressing my feelings through creative work.', 'likert', 24, true, '{"type":"A"}', '{"applicable_grades":["after10","after12","college"]}'),

-- S – Social (8 questions)
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy helping someone learn a new skill.', 'likert', 25, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy mentoring juniors or peers.', 'likert', 26, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I feel good supporting people who are in difficulty.', 'likert', 27, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer work that benefits others.', 'likert', 28, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like group activities and collaboration.', 'likert', 29, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I try to understand people''s feelings and perspectives.', 'likert', 30, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy guiding teams to work better together.', 'likert', 31, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like roles involving care, service, or community work.', 'likert', 32, true, '{"type":"S"}', '{"applicable_grades":["after10","after12","college"]}'),

-- E – Enterprising (8 questions)
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I can convince others about an idea I believe in.', 'likert', 33, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like taking leadership roles in projects.', 'likert', 34, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy negotiating or closing deals.', 'likert', 35, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like planning events or ventures.', 'likert', 36, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I feel energized by competition.', 'likert', 37, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I spot opportunities and act quickly on them.', 'likert', 38, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy giving presentations to influence people.', 'likert', 39, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer roles with responsibility and authority.', 'likert', 40, true, '{"type":"E"}', '{"applicable_grades":["after10","after12","college"]}'),

-- C – Conventional (8 questions)
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like organizing information in an orderly way.', 'likert', 41, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy working with spreadsheets or records.', 'likert', 42, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I prefer clear instructions and structure.', 'likert', 43, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like checking work for errors and accuracy.', 'likert', 44, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I keep things neat and systematically arranged.', 'likert', 45, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I enjoy routine tasks that require precision.', 'likert', 46, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I follow step-by-step processes comfortably.', 'likert', 47, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}'),
('a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6', NULL, 'I like jobs that involve planning and scheduling.', 'likert', 48, true, '{"type":"C"}', '{"applicable_grades":["after10","after12","college"]}');
