/**
 * Upload Context Configuration
 * 
 * Central configuration for upload contexts that can be used without authentication.
 * This prevents duplicate definitions and ensures consistency across the storage API.
 */

import type { UploadContext } from './fileSizeLimits';

/**
 * Valid upload contexts that can be used without authentication
 * 
 * SECURITY NOTE: These contexts bypass JWT authentication and should only be used
 * for system-initiated uploads (e.g., certificates generated by the backend).
 * 
 * All unauthenticated uploads are still subject to:
 * - File size validation
 * - MIME type validation
 * - Extension validation
 * - Malware scanning
 * - Magic number validation
 */
export const UNAUTHENTICATED_UPLOAD_CONTEXTS: ReadonlyArray<UploadContext> = [
  'certificate'
] as const;

/**
 * All valid upload contexts (authenticated and unauthenticated)
 */
export const VALID_UPLOAD_CONTEXTS: ReadonlyArray<string> = [
  'assignment',
  'course_video',
  'course_resource',
  'document',
  'certificate',
  'resume',
  'message_attachment',
  'profile_photo',
  'default'
] as const;

/**
 * Check if a given context is valid
 */
export function isValidUploadContext(context: string): context is UploadContext {
  return VALID_UPLOAD_CONTEXTS.includes(context);
}

/**
 * Check if a given context requires authentication
 */
export function requiresAuthentication(context: string): boolean {
  return !UNAUTHENTICATED_UPLOAD_CONTEXTS.includes(context as UploadContext);
}
