export type StageId =
  | 'capabilityWheel'
  | 'interestWorlds'
  | 'characterConstellation'
  | 'selfSocial'
  | 'explorerMap'
  | 'thinkingStyle'
  | 'whatIHaveNeed'
  | 'missions';

export type StageStatus = 'done' | 'current' | 'locked';

export interface StageMeta {
  id: StageId;
  order: number;
  title: string;
  description: string;
  growthLevelLabel: string;
}

export const STAGE_ORDER: StageMeta[] = [
  {
    id: 'capabilityWheel',
    order: 1,
    title: 'Capability Wheel',
    description: 'Your growth across 8 core capabilities.',
    growthLevelLabel: 'Seedling Sprout',
  },
  {
    id: 'interestWorlds',
    order: 2,
    title: 'Interest Worlds',
    description: 'The worlds that light you up.',
    growthLevelLabel: 'Early Growth',
  },
  {
    id: 'characterConstellation',
    order: 3,
    title: 'Character Constellation',
    description: 'Your core character strengths & connections.',
    growthLevelLabel: 'Branching Out',
  },
  {
    id: 'selfSocial',
    order: 4,
    title: 'Self & Social Strengths',
    description: 'Your emotional intelligence & social mastery.',
    growthLevelLabel: 'Branching Out',
  },
  {
    id: 'explorerMap',
    order: 5,
    title: 'Explorer Map',
    description: 'Your journey across interest territories.',
    growthLevelLabel: 'Active Exploration',
  },
  {
    id: 'thinkingStyle',
    order: 6,
    title: 'Thinking Style',
    description: 'How you approach problems and ideas.',
    growthLevelLabel: 'Budding Potential',
  },
  {
    id: 'whatIHaveNeed',
    order: 7,
    title: 'What I Have / Need',
    description: 'Assets you hold and what to build next.',
    growthLevelLabel: 'Budding Potential',
  },
  {
    id: 'missions',
    order: 8,
    title: 'Recommended Missions',
    description: 'Next steps chosen for you.',
    growthLevelLabel: 'Full Bloom',
  },
];

export interface StageReports {
  /** Persisted Growth Map stage-completion progress (see GrowthMapShell) —
   * stored inside gemini_results, not a separate database column. */
  growth_map_progress?: {
    completedStageIds?: StageId[];
  };
  my_interest_worlds?: Array<any>;
  character_strengths_descriptions?: Array<{
    label: string;
    description: string;
    tag: string;
  }>;
  self_social?: {
    self_eq?: Array<{ label: string; status: string; percentage?: number; score_out_of_5?: number }>;
    social_sq?: Array<{ label: string; status: string; percentage?: number; score_out_of_5?: number }>;
  };
  explorer_map?: {
    explored?: Array<{
      label: string;
      score: number;
      status: string;
      percentage: number;
      score_out_of_5: number;
    }>;
    to_explore?: Array<{
      label: string;
      score: number;
      status: string;
      percentage: number;
      score_out_of_5: number;
    }>;
  };
  explorer_insights?: {
    exploredWorlds?: Array<any>;
    toExploreWorlds?: Array<any>;
  };
  thinking_styles?: Array<{
    title: string;
    description: string;
    icon: string;
    value?: number;
  }>;
  capability_wheel?: Array<{
    capability_area: string;
    score_out_of_5: number;
    percentage: number;
    status: string;
  }>;
  what_i_have?: Array<{
    capability_area: string;
    score_out_of_5: number;
  }>;
  what_i_need?: Array<{
    capability_area: string;
    score_out_of_5: number;
  }>;
  mission_recommendations?: Array<{
    priority: number;
    mission_name: string;
    capability_target: string;
    why_recommended: string;
    difficulty: string;
    estimated_duration_days: number;
  }>;
  /**
   * Per-capability-area insight + next step, keyed by the same 8 area names
   * used in capability_wheel (e.g. "Self / EQ", "Social / SQ"). Real AI
   * output, generated and stored in gemini_results (report-generator.ts),
   * but previously never surfaced in the Growth Map UI. Only meaningful
   * alongside capability_wheel (Stage 1) — it does not map to any other
   * single stage.
   */
  capability_insights?: Record<string, { insight: string; next_step: string }>;
  /**
   * A single 200-250 word educator-facing narrative for the whole
   * assessment (not per-stage). Real AI output, stored in gemini_results,
   * previously unused in the Growth Map UI.
   */
  assessmentReport?: string;
  /**
   * Per-stage guidance content (v2 schema), keyed by the same 8 StageId
   * values as STAGE_ORDER. Real AI output, generated by the same
   * report-generation pipeline as every other field here (see
   * report-generator.ts StageGuidance), grounded in each stage's own
   * growth_map evidence — never fabricated in the frontend. Optional because
   * existing, already-generated reports predate this field and will not have
   * it until they are regenerated (not backfilled automatically per explicit
   * instruction). May also be an OLD-shape entry ({parent, instructional,
   * actionSteps}) from before the v2 migration — see StageGuidanceEntryRaw /
   * resolveStageGuidanceSections below for how both shapes are normalized.
   */
  stage_guidance?: Record<StageId, StageGuidanceEntryRaw>;
}

/**
 * The 3 canonical guidance "kinds" every stage's sections are built from —
 * matches GuidanceSectionKind in report-generator.ts. Not every stage has all
 * 3: whatIHaveNeed has only parent+action, missions has only teacher.
 */
export type GuidanceSectionKind = 'parent' | 'teacher' | 'action';

/** App-owned structural definition of one guidance section: which kind it
 * is, and its approved UI title/subtitle — zero learner-facing content. */
export interface GuidanceSectionDef {
  kind: GuidanceSectionKind;
  title: string;
  subtitle: string;
}

/**
 * App-owned registry: which guidance section kinds exist for each stage, in
 * what order, with what approved UI title/subtitle. Gemini never decides
 * this — it only ever supplies desc/highlights content for whichever kinds
 * a stage's entry here lists. Verified against the real Bolt reference
 * (TabbedView.tsx sectionGuidance, all 8 stages) — whatIHaveNeed has only
 * parent+action (no teacher/classroom section), and missions has only
 * teacher (no parent/action section); every other stage has all 3 kinds.
 */
export const STAGE_GUIDANCE_SECTIONS: Record<StageId, GuidanceSectionDef[]> = {
  capabilityWheel: [
    { kind: 'parent', title: 'Parent Translation', subtitle: 'What this means at home' },
    { kind: 'teacher', title: 'Instructional Implications', subtitle: 'Classroom support' },
    { kind: 'action', title: 'Actionable Next Steps', subtitle: 'Try this next' },
  ],
  interestWorlds: [
    { kind: 'parent', title: 'Parent Support at Home', subtitle: 'How to support exploration at home' },
    { kind: 'teacher', title: 'Classroom Alignment', subtitle: 'Connecting electives & projects' },
    { kind: 'action', title: 'Try This World Next', subtitle: 'Next world exploration' },
  ],
  characterConstellation: [
    { kind: 'parent', title: 'Parent Context', subtitle: 'Understanding growth labels' },
    { kind: 'teacher', title: 'Teacher Report Card Notes', subtitle: 'Classroom observation notes' },
    { kind: 'action', title: 'Home vs Class Nurture', subtitle: 'How to nurture character traits' },
  ],
  selfSocial: [
    { kind: 'parent', title: 'Parent Interpretation', subtitle: 'Self & social emotional growth' },
    { kind: 'teacher', title: 'Classroom EQ Integration', subtitle: 'Social mastery in class' },
    { kind: 'action', title: 'Social EQ Challenge', subtitle: 'Growth action plan' },
  ],
  explorerMap: [
    { kind: 'parent', title: 'Parent Guide', subtitle: 'Spatial & hands-on roadmap' },
    { kind: 'teacher', title: 'Subject Choice Mapping', subtitle: 'Curriculum pathway alignment' },
    { kind: 'action', title: 'Next Explorer Challenge', subtitle: 'Next world milestone' },
  ],
  thinkingStyle: [
    { kind: 'parent', title: 'Parent Translation', subtitle: 'Demystifying cognitive styles' },
    { kind: 'teacher', title: 'Instructional Strategy', subtitle: 'Teaching to this thinking style' },
    { kind: 'action', title: 'Next Step Challenge', subtitle: 'Weekly brain exercises' },
  ],
  // Bolt's real "whatihave" stage has only 2 sections (parent + action)
  whatIHaveNeed: [
    { kind: 'parent', title: 'Parent Snapshot', subtitle: 'Assets held & growth horizon' },
    { kind: 'action', title: 'Skill Bridge Plan', subtitle: 'Closing the growth gap' },
  ],
  // Bolt's real "missions" stage has only 1 section (teacher only)
  missions: [
    { kind: 'teacher', title: 'Teacher Monitoring Note', subtitle: 'Classroom mission monitoring' },
  ],
};

export interface SectionIntro {
  heading: string;
  description: string;
}

/** Real generated content for one guidance section (no title/subtitle —
 * those come from STAGE_GUIDANCE_SECTIONS). */
export interface GuidanceSectionContent {
  desc: string;
  highlights: string[];
}

/** A fully resolved section ready to render: app-owned title/subtitle merged
 * with the real generated desc/highlights. */
export interface ResolvedGuidanceSection extends GuidanceSectionDef, GuidanceSectionContent {}

/** OLD (pre-v2) stage_guidance entry shape — some already-generated reports
 * predate the v2 migration and still have this shape in gemini_results. */
export interface StageGuidanceEntryOld {
  parent?: StageGuidanceBlock;
  instructional?: StageGuidanceBlock;
  actionSteps?: StageGuidanceBlock;
  sectionIntro?: SectionIntro;
}

/** NEW (v2) stage_guidance entry shape. */
export interface StageGuidanceEntryNew {
  sections?: Partial<Record<GuidanceSectionKind, GuidanceSectionContent>>;
  sectionIntro?: SectionIntro;
}

/** A stage_guidance[stageId] entry may be either shape (or both, in theory)
 * — resolveStageGuidanceSections checks the new shape first, per-kind, and
 * falls back to the matching legacy field only for kinds the CURRENT stage
 * registry actually lists. */
export type StageGuidanceEntryRaw = StageGuidanceEntryOld & StageGuidanceEntryNew;

export interface StageGuidanceBlock {
  title: string;
  subtitle: string;
  desc: string;
  highlights: string[];
}

/** Maps a v2 GuidanceSectionKind to the legacy field name that historically
 * carried the equivalent content, for backward compatibility with reports
 * generated before the v2 migration. */
const LEGACY_KIND_TO_FIELD: Record<GuidanceSectionKind, keyof StageGuidanceEntryOld> = {
  parent: 'parent',
  teacher: 'instructional',
  action: 'actionSteps',
};

function isValidGeneratedContent(content: unknown): content is GuidanceSectionContent {
  if (!content || typeof content !== 'object') return false;
  const c = content as Record<string, unknown>;
  return (
    typeof c.desc === 'string' &&
    c.desc.trim().length > 0 &&
    Array.isArray(c.highlights) &&
    c.highlights.length >= 2 &&
    c.highlights.length <= 3 &&
    c.highlights.every((h) => typeof h === 'string' && h.trim().length > 0)
  );
}

function isValidLegacyBlock(block: unknown): block is StageGuidanceBlock {
  if (!block || typeof block !== 'object') return false;
  const b = block as Record<string, unknown>;
  return (
    typeof b.desc === 'string' &&
    b.desc.trim().length > 0 &&
    Array.isArray(b.highlights) &&
    b.highlights.length >= 2 &&
    b.highlights.length <= 3 &&
    b.highlights.every((h) => typeof h === 'string' && h.trim().length > 0)
  );
}

/**
 * The single function that resolves a stage's guidance sections for
 * rendering: walks STAGE_GUIDANCE_SECTIONS (app-owned — which kinds exist,
 * in what order, with what title/subtitle) and, for each kind, looks for
 * valid real content first in the v2 shape (`entry.sections[kind]`), falling
 * back to the matching legacy field (`LEGACY_KIND_TO_FIELD`) only for kinds
 * the CURRENT registry lists for this stage. A kind with no valid content in
 * either shape is simply omitted — never a broken or fake tab, never a
 * legacy field forced onto a stage whose new structure doesn't support it.
 */
export function resolveStageGuidanceSections(
  stageId: StageId,
  entry: StageGuidanceEntryRaw | undefined
): ResolvedGuidanceSection[] {
  const defs = STAGE_GUIDANCE_SECTIONS[stageId] ?? [];
  if (!entry) return [];

  const resolved: ResolvedGuidanceSection[] = [];
  for (const def of defs) {
    const fromNew = entry.sections?.[def.kind];
    if (isValidGeneratedContent(fromNew)) {
      resolved.push({ kind: def.kind, title: def.title, subtitle: def.subtitle, ...fromNew });
      continue;
    }

    const legacyField = LEGACY_KIND_TO_FIELD[def.kind];
    const legacyBlock = entry[legacyField];
    if (isValidLegacyBlock(legacyBlock)) {
      resolved.push({
        kind: def.kind,
        title: def.title,
        subtitle: def.subtitle,
        desc: legacyBlock.desc,
        highlights: legacyBlock.highlights,
      });
    }
  }
  return resolved;
}

// Mirrors the backend's isValidSectionIntro caps (report-generator.ts) — the
// backend already strips malformed/oversized sectionIntro entries before
// storage, but this is checked again on the frontend since gemini_results is
// passed through as `any` end-to-end, so a stage component never renders
// malformed or excessively long AI text as if it were a trusted UI heading.
const SECTION_INTRO_MAX_HEADING_LENGTH = 60;
const SECTION_INTRO_MAX_DESCRIPTION_LENGTH = 220;

export function isValidSectionIntro(intro: unknown): intro is SectionIntro {
  if (!intro || typeof intro !== 'object') return false;
  const i = intro as Record<string, unknown>;
  return (
    typeof i.heading === 'string' &&
    i.heading.trim().length > 0 &&
    i.heading.length <= SECTION_INTRO_MAX_HEADING_LENGTH &&
    typeof i.description === 'string' &&
    i.description.trim().length > 0 &&
    i.description.length <= SECTION_INTRO_MAX_DESCRIPTION_LENGTH
  );
}

/**
 * Whether a stage has real report data behind it. This is the only signal
 * available today — there is no persisted per-stage completion state anywhere
 * in the codebase (verified against assessmentStore.ts, types.ts, and the DB
 * schema), so "has data" stands in for "done" until a real progression model
 * exists.
 */
export function hasStageData(id: StageId, reports: StageReports): boolean {
  switch (id) {
    case 'capabilityWheel':
      return (reports.capability_wheel?.length ?? 0) > 0;
    case 'interestWorlds':
      return (reports.my_interest_worlds?.length ?? 0) > 0;
    case 'characterConstellation':
      return (reports.character_strengths_descriptions?.length ?? 0) > 0;
    case 'selfSocial':
      return Boolean(reports.self_social);
    case 'explorerMap':
      return Boolean(reports.explorer_map);
    case 'thinkingStyle':
      return (reports.thinking_styles?.length ?? 0) > 0;
    case 'whatIHaveNeed':
      return Boolean(reports.what_i_have) || Boolean(reports.what_i_need);
    case 'missions':
      return (reports.mission_recommendations?.length ?? 0) > 0;
    default:
      return false;
  }
}

/**
 * Derives Done / Current / Locked from the learner's actual session progress
 * (which stages they have clicked "Next Section" past), NOT from whether
 * gemini_results happens to contain data for a stage. Data presence only
 * gates whether a stage has renderable content (see hasStageData) — it is
 * not a substitute for the learner having gone through the stage.
 *
 * completedStageIds is owned by GrowthMapShell as in-memory React state only
 * (no persistence): it starts empty every page load, so Stage 1 is always
 * "current" and Stages 2-8 always "locked" on a fresh load, regardless of
 * how much gemini_results content already exists.
 */
export function deriveStageStatuses(
  completedStageIds: ReadonlySet<StageId>
): Record<StageId, StageStatus> {
  const statuses = {} as Record<StageId, StageStatus>;
  let currentAssigned = false;

  STAGE_ORDER.forEach((stage) => {
    if (completedStageIds.has(stage.id)) {
      statuses[stage.id] = 'done';
    } else if (!currentAssigned) {
      statuses[stage.id] = 'current';
      currentAssigned = true;
    } else {
      statuses[stage.id] = 'locked';
    }
  });

  return statuses;
}

export function getCurrentStage(
  statuses: Record<StageId, StageStatus>
): StageMeta {
  const current = STAGE_ORDER.find((stage) => statuses[stage.id] === 'current');
  return current ?? STAGE_ORDER[0];
}

export function countDoneStages(statuses: Record<StageId, StageStatus>): number {
  return STAGE_ORDER.filter((stage) => statuses[stage.id] === 'done').length;
}
