export type StageId =
  | 'capabilityWheel'
  | 'interestWorlds'
  | 'characterConstellation'
  | 'selfSocial'
  | 'explorerMap'
  | 'thinkingStyle'
  | 'whatIHaveNeed'
  | 'missions';

export type StageStatus = 'done' | 'current' | 'locked';

export interface StageMeta {
  id: StageId;
  order: number;
  title: string;
  description: string;
  growthLevelLabel: string;
}

export const STAGE_ORDER: StageMeta[] = [
  {
    id: 'capabilityWheel',
    order: 1,
    title: 'Capability Wheel',
    description: 'Your growth across 8 core capabilities.',
    growthLevelLabel: 'Seedling Sprout',
  },
  {
    id: 'interestWorlds',
    order: 2,
    title: 'Interest Worlds',
    description: 'The worlds that light you up.',
    growthLevelLabel: 'Early Growth',
  },
  {
    id: 'characterConstellation',
    order: 3,
    title: 'Character Constellation',
    description: 'Your core character strengths & connections.',
    growthLevelLabel: 'Branching Out',
  },
  {
    id: 'selfSocial',
    order: 4,
    title: 'Self & Social Strengths',
    description: 'Your emotional intelligence & social mastery.',
    growthLevelLabel: 'Branching Out',
  },
  {
    id: 'explorerMap',
    order: 5,
    title: 'Explorer Map',
    description: 'Your journey across interest territories.',
    growthLevelLabel: 'Active Exploration',
  },
  {
    id: 'thinkingStyle',
    order: 6,
    title: 'Thinking Style',
    description: 'How you approach problems and ideas.',
    growthLevelLabel: 'Budding Potential',
  },
  {
    id: 'whatIHaveNeed',
    order: 7,
    title: 'What I Have / Need',
    description: 'Assets you hold and what to build next.',
    growthLevelLabel: 'Budding Potential',
  },
  {
    id: 'missions',
    order: 8,
    title: 'Recommended Missions',
    description: 'Next steps chosen for you.',
    growthLevelLabel: 'Full Bloom',
  },
];

export interface StageReports {
  my_interest_worlds?: Array<any>;
  character_strengths_descriptions?: Array<{
    label: string;
    description: string;
    tag: string;
  }>;
  self_social?: {
    self_eq?: Array<{ label: string; status: string; percentage?: number; score_out_of_5?: number }>;
    social_sq?: Array<{ label: string; status: string; percentage?: number; score_out_of_5?: number }>;
  };
  explorer_map?: {
    explored?: Array<{
      label: string;
      score: number;
      status: string;
      percentage: number;
      score_out_of_5: number;
    }>;
    to_explore?: Array<{
      label: string;
      score: number;
      status: string;
      percentage: number;
      score_out_of_5: number;
    }>;
  };
  explorer_insights?: {
    exploredWorlds?: Array<any>;
    toExploreWorlds?: Array<any>;
  };
  thinking_styles?: Array<{
    title: string;
    description: string;
    icon: string;
  }>;
  capability_wheel?: Array<{
    capability_area: string;
    score_out_of_5: number;
    percentage: number;
    status: string;
  }>;
  what_i_have?: Array<{
    capability_area: string;
    score_out_of_5: number;
  }>;
  what_i_need?: Array<{
    capability_area: string;
    score_out_of_5: number;
  }>;
  mission_recommendations?: Array<{
    priority: number;
    mission_name: string;
    capability_target: string;
    why_recommended: string;
    difficulty: string;
    estimated_duration_days: number;
  }>;
  /**
   * Per-capability-area insight + next step, keyed by the same 8 area names
   * used in capability_wheel (e.g. "Self / EQ", "Social / SQ"). Real AI
   * output, generated and stored in gemini_results (report-generator.ts),
   * but previously never surfaced in the Growth Map UI. Only meaningful
   * alongside capability_wheel (Stage 1) — it does not map to any other
   * single stage.
   */
  capability_insights?: Record<string, { insight: string; next_step: string }>;
  /**
   * A single 200-250 word educator-facing narrative for the whole
   * assessment (not per-stage). Real AI output, stored in gemini_results,
   * previously unused in the Growth Map UI.
   */
  assessmentReport?: string;
  /**
   * Per-stage Parent Translation / Instructional Implications / Actionable
   * Next Steps, keyed by the same 8 StageId values as STAGE_ORDER. Real AI
   * output, generated by the same report-generation pipeline as every other
   * field here (see report-generator.ts StageGuidance), grounded in each
   * stage's own growth_map evidence — never fabricated in the frontend.
   * Optional because existing, already-generated reports predate this field
   * and will not have it until they are regenerated (not backfilled
   * automatically per explicit instruction).
   */
  stage_guidance?: Record<
    StageId,
    {
      parent: StageGuidanceBlock;
      instructional: StageGuidanceBlock;
      actionSteps: StageGuidanceBlock;
      /**
       * Learner-specific section heading + one-sentence description for this
       * stage's own display card (e.g. replacing the hardcoded "My Capability
       * Wheel" / "Your growth across 8 core capabilities..." pair). Optional:
       * older reports predate this field, and the backend omits it for a
       * stage whose evidence is too sparse to say something specific — in
       * both cases the section component falls back to its own static
       * heading/description, never a blank or fabricated one.
       */
      sectionIntro?: SectionIntro;
    }
  >;
}

export interface StageGuidanceBlock {
  title: string;
  subtitle: string;
  desc: string;
  highlights: string[];
}

export interface SectionIntro {
  heading: string;
  description: string;
}

// Mirrors the backend's isValidSectionIntro caps (report-generator.ts) — the
// backend already strips malformed/oversized sectionIntro entries before
// storage, but this is checked again on the frontend since gemini_results is
// passed through as `any` end-to-end, so a stage component never renders
// malformed or excessively long AI text as if it were a trusted UI heading.
const SECTION_INTRO_MAX_HEADING_LENGTH = 60;
const SECTION_INTRO_MAX_DESCRIPTION_LENGTH = 220;

export function isValidSectionIntro(intro: unknown): intro is SectionIntro {
  if (!intro || typeof intro !== 'object') return false;
  const i = intro as Record<string, unknown>;
  return (
    typeof i.heading === 'string' &&
    i.heading.trim().length > 0 &&
    i.heading.length <= SECTION_INTRO_MAX_HEADING_LENGTH &&
    typeof i.description === 'string' &&
    i.description.trim().length > 0 &&
    i.description.length <= SECTION_INTRO_MAX_DESCRIPTION_LENGTH
  );
}

/**
 * Whether a stage has real report data behind it. This is the only signal
 * available today — there is no persisted per-stage completion state anywhere
 * in the codebase (verified against assessmentStore.ts, types.ts, and the DB
 * schema), so "has data" stands in for "done" until a real progression model
 * exists.
 */
export function hasStageData(id: StageId, reports: StageReports): boolean {
  switch (id) {
    case 'capabilityWheel':
      return (reports.capability_wheel?.length ?? 0) > 0;
    case 'interestWorlds':
      return (reports.my_interest_worlds?.length ?? 0) > 0;
    case 'characterConstellation':
      return (reports.character_strengths_descriptions?.length ?? 0) > 0;
    case 'selfSocial':
      return Boolean(reports.self_social);
    case 'explorerMap':
      return Boolean(reports.explorer_map);
    case 'thinkingStyle':
      return (reports.thinking_styles?.length ?? 0) > 0;
    case 'whatIHaveNeed':
      return Boolean(reports.what_i_have) || Boolean(reports.what_i_need);
    case 'missions':
      return (reports.mission_recommendations?.length ?? 0) > 0;
    default:
      return false;
  }
}

/**
 * Derives Done / Current / Locked from the learner's actual session progress
 * (which stages they have clicked "Next Section" past), NOT from whether
 * gemini_results happens to contain data for a stage. Data presence only
 * gates whether a stage has renderable content (see hasStageData) — it is
 * not a substitute for the learner having gone through the stage.
 *
 * completedStageIds is owned by GrowthMapShell as in-memory React state only
 * (no persistence): it starts empty every page load, so Stage 1 is always
 * "current" and Stages 2-8 always "locked" on a fresh load, regardless of
 * how much gemini_results content already exists.
 */
export function deriveStageStatuses(
  completedStageIds: ReadonlySet<StageId>
): Record<StageId, StageStatus> {
  const statuses = {} as Record<StageId, StageStatus>;
  let currentAssigned = false;

  STAGE_ORDER.forEach((stage) => {
    if (completedStageIds.has(stage.id)) {
      statuses[stage.id] = 'done';
    } else if (!currentAssigned) {
      statuses[stage.id] = 'current';
      currentAssigned = true;
    } else {
      statuses[stage.id] = 'locked';
    }
  });

  return statuses;
}

export function getCurrentStage(
  statuses: Record<StageId, StageStatus>
): StageMeta {
  const current = STAGE_ORDER.find((stage) => statuses[stage.id] === 'current');
  return current ?? STAGE_ORDER[0];
}

export function countDoneStages(statuses: Record<StageId, StageStatus>): number {
  return STAGE_ORDER.filter((stage) => statuses[stage.id] === 'done').length;
}
