-- ============================================================================
-- Seed: Complete Hospitality Occupations (Normalized)
-- Date: 2026-05-29
-- Tables: domains, capabilities_master, occupations, occupations_context, riasec_profiles, occupations_capabilities_master
-- Total records: 459
-- ============================================================================

BEGIN;

-- Insert DOMAINS (7 records)
INSERT INTO public.domains (code, name) VALUES
  ('D01', 'Customer Service & Frontline Experience'),
  ('D02', 'Accommodation & Facilities Operations'),
  ('D03', 'Food, Beverage & Event Service Operations'),
  ('D04', 'Transport Movement & Passenger Operations'),
  ('D05', 'Travel Booking, Distribution & Agency Operations'),
  ('D06', 'Destination, Attraction & Cultural Experience Management'),
  ('D07', 'Safety, Compliance & Sustainable Tourism Governance');

-- Insert CAPABILITIES_MASTER (27 records)
INSERT INTO public.capabilities_master (code, name, description) VALUES
  ('IND-CAP-01', 'Verify guest and visitor arrival readiness through identity, booking, and service handoff evidence', 'Guided Guest Arrival Readiness'),
  ('IND-CAP-02', 'Route passengers through terminal assistance, queue control, and disruption communication', 'Guided Passenger Terminal Assistance'),
  ('IND-CAP-03', 'Resolve service recovery, complaint, refund, and claim cases through evidence-based closure', 'Guided Service Recovery Case Closure'),
  ('IND-CAP-04', 'Release rooms through cleaning, readiness inspection, and defect correction evidence', 'Guided Room Readiness Release'),
  ('IND-CAP-05', 'Prepare alternative stays and property handoffs through host readiness and guest issue control', 'Guided Alternative Stay Property Handoff'),
  ('IND-CAP-06', 'Coordinate wellness, leisure, valet, and facility service handoffs through appointment and readiness evidence', 'Guided Wellness and Facility Service Handoff'),
  ('IND-CAP-07', 'Control dining orders and bill settlement through table, KOT, POS, and payment evidence', 'Guided Dining Order and Bill Settlement'),
  ('IND-CAP-08', 'Control kitchen production and dispatch through preparation, packaging, and handoff evidence', 'Guided Kitchen Production and Dispatch'),
  ('IND-CAP-09', 'Run banquet and venue service operations through event setup, service run, and closure evidence', 'Guided Banquet Venue Service Run'),
  ('IND-CAP-10', 'Coordinate MICE event briefs, stakeholder alignment, venue logistics, and post-event closure', 'Guided MICE Event Coordination'),
  ('IND-CAP-11', 'Control air passenger check-in, baggage acceptance, boarding, and load documentation', 'Guided Air Passenger Processing'),
  ('IND-CAP-12', 'Support rail booking, refund, station information, and disruption response through passenger evidence', 'Guided Rail Passenger Booking and Disruption Support'),
  ('IND-CAP-13', 'Control road mobility, vehicle rental inspection, fleet dispatch, and trip completion evidence', 'Guided Road Mobility and Vehicle Rental Control'),
  ('IND-CAP-14', 'Control ferry, cruise, manifest, boarding, and shore-excursion passenger handoffs', 'Guided Ferry and Cruise Passenger Handoff'),
  ('IND-CAP-15', 'Create, confirm, change, and refund bookings through reservation and ticketing evidence', 'Guided Reservation and Ticketing Transaction Control'),
  ('IND-CAP-16', 'Coordinate itinerary suppliers, tour departure files, and traveler handoff readiness', 'Guided Tour Departure and Supplier Handoff'),
  ('IND-CAP-17', 'Stabilize OTA inventory, fare synchronization, API booking errors, and supplier handoffs', 'Guided OTA and API Booking Stabilization'),
  ('IND-CAP-18', 'Align partner rates, allotments, commercial proposals, and distribution handoffs', 'Guided Partner Rate and Allotment Coordination'),
  ('IND-CAP-19', 'Convert tourism data, visitor signals, and program evidence into destination reporting', 'Guided Destination Reporting and Visitor Signal Analysis'),
  ('IND-CAP-20', 'Manage heritage attraction visitor flow, interpretation, and safety handoffs', 'Guided Heritage Attraction Visitor Flow'),
  ('IND-CAP-21', 'Facilitate pilgrimage, cultural, and festival visitor journeys through guide and route evidence', 'Guided Pilgrimage and Festival Visitor Journey'),
  ('IND-CAP-22', 'Deliver private, VIP, and digital tourism experiences through preference, content, and disruption control', 'Guided Private VIP and Digital Experience Delivery'),
  ('IND-CAP-23', 'Control adventure activity registration, safety briefing, incident escalation, and field return', 'Guided Adventure Safety and Field Return'),
  ('IND-CAP-24', 'Coordinate safari dispatch, guide briefing, vehicle breakdown response, and tourist rescue closure', 'Guided Safari Dispatch and Rescue Closure'),
  ('IND-CAP-25', 'Coordinate medical, wellness, and AYUSH travel journeys through provider, appointment, and stay evidence', 'Guided Medical Wellness and AYUSH Journey Coordination'),
  ('IND-CAP-26', 'Govern eco-site visitor conduct, conservation checks, sustainability evidence, and community benefit records', 'Guided Responsible Eco-site Governance'),
  ('IND-CAP-27', 'Manage rural community, homestay, craft, and livelihood experience operations through compliance and host evidence', 'Guided Rural Community and Homestay Operations');

-- Insert OCCUPATIONS (127 records)
INSERT INTO public.occupations (code, name) VALUES
  ('ROLE-HTT-001', 'Reception Staff'),
  ('ROLE-HTT-002', 'Front Desk Agent'),
  ('ROLE-HTT-003', 'Receptionist'),
  ('ROLE-HTT-004', 'Front Office Agent'),
  ('ROLE-HTT-005', 'Front Office Associate'),
  ('ROLE-HTT-006', 'Reservation/Guest Communication Staff'),
  ('ROLE-HTT-007', 'Department Head'),
  ('ROLE-HTT-008', 'Guest-facing Hotel/Restaurant Staff'),
  ('ROLE-HTT-009', 'Guest Support'),
  ('ROLE-HTT-010', 'Security Response Staff'),
  ('ROLE-HTT-011', 'Airline Customer Service'),
  ('ROLE-HTT-012', 'Disruption Desk Agent'),
  ('ROLE-HTT-013', 'Refund and Claims Processing Officer'),
  ('ROLE-HTT-018', 'Housekeeper'),
  ('ROLE-HTT-019', 'Housekeeping Manager'),
  ('ROLE-HTT-020', 'Housekeeping Staff'),
  ('ROLE-HTT-021', 'Housekeeping Attendant'),
  ('ROLE-HTT-022', 'Housekeeping Supervisor'),
  ('ROLE-HTT-023', 'Housekeeping Personnel'),
  ('ROLE-HTT-024', 'Property Manager'),
  ('ROLE-HTT-025', 'Host'),
  ('ROLE-HTT-026', 'Property Partner'),
  ('ROLE-HTT-027', 'Housekeeping Turnover Team'),
  ('ROLE-HTT-028', 'Spa Receptionist'),
  ('ROLE-HTT-029', 'Therapist'),
  ('ROLE-HTT-030', 'Valet'),
  ('ROLE-HTT-031', 'Spa Attendant'),
  ('ROLE-HTT-032', 'Restaurant Cashier'),
  ('ROLE-HTT-033', 'Server'),
  ('ROLE-HTT-034', 'Restaurant Manager'),
  ('ROLE-HTT-035', 'Front Office Cashier'),
  ('ROLE-HTT-036', 'Billing Staff'),
  ('ROLE-HTT-037', 'Kitchen Staff'),
  ('ROLE-HTT-038', 'Expeditor'),
  ('ROLE-HTT-039', 'Banquet Coordinator'),
  ('ROLE-HTT-040', 'Banquet Manager'),
  ('ROLE-HTT-041', 'Event Sales'),
  ('ROLE-HTT-042', 'Banquet Operations Team'),
  ('ROLE-HTT-043', 'MICE Destination Manager'),
  ('ROLE-HTT-044', 'Convention Bureau Coordinator'),
  ('ROLE-HTT-045', 'MICE Marketing Manager'),
  ('ROLE-HTT-046', 'Digital Asset Manager'),
  ('ROLE-HTT-047', 'MICE Coordinator'),
  ('ROLE-HTT-048', 'Event Logistics Coordinator'),
  ('ROLE-HTT-058', 'Rail Ticketing'),
  ('ROLE-HTT-059', 'Refund Processing Clerk'),
  ('ROLE-HTT-060', 'Passenger Support Executive'),
  ('ROLE-HTT-061', 'Rail Reservation Systems Operator'),
  ('ROLE-HTT-062', 'Passenger Information'),
  ('ROLE-HTT-063', 'Booking Support Staff'),
  ('ROLE-HTT-064', 'Rail Operations Controller'),
  ('ROLE-HTT-065', 'Station Master'),
  ('ROLE-HTT-066', 'Car Rental Agent'),
  ('ROLE-HTT-067', 'Vehicle Rental Agent'),
  ('ROLE-HTT-068', 'Ride-hailing Driver'),
  ('ROLE-HTT-069', 'Bus Operations Manager'),
  ('ROLE-HTT-070', 'Passenger Service Officer - Ferry/Cruise Operations'),
  ('ROLE-HTT-071', 'Deckhand'),
  ('ROLE-HTT-072', 'Shore Excursion Manager'),
  ('ROLE-HTT-073', 'Reservation Agent'),
  ('ROLE-HTT-074', 'Rail Reservation Systems Operator'),
  ('ROLE-HTT-075', 'Passenger Information'),
  ('ROLE-HTT-076', 'Booking Support Staff'),
  ('ROLE-HTT-077', 'Travel Industry Research'),
  ('ROLE-HTT-078', 'Capability Analyst'),
  ('ROLE-HTT-079', 'Tour Operations Manager'),
  ('ROLE-HTT-080', 'Tour Operation Executive'),
  ('ROLE-HTT-081', 'Inbound Tour Executive'),
  ('ROLE-HTT-082', 'Shore Excursion Manager'),
  ('ROLE-HTT-083', 'Travel Technology API/Product Operator'),
  ('ROLE-HTT-084', 'Fare Aggregation Product/Operations Analyst'),
  ('ROLE-HTT-085', 'OTA Connectivity Operations Specialist'),
  ('ROLE-HTT-086', 'Travel API Integration Engineer'),
  ('ROLE-HTT-087', 'OTA Product Operations Specialist'),
  ('ROLE-HTT-088', 'Connectivity Operations Specialist'),
  ('ROLE-HTT-089', 'Tourism Analyst'),
  ('ROLE-HTT-090', 'Destination Planner'),
  ('ROLE-HTT-091', 'Tourism Data Analyst'),
  ('ROLE-HTT-092', 'Policy Planner'),
  ('ROLE-HTT-093', 'Ministry/DMO Planning Officer'),
  ('ROLE-HTT-094', 'Tourism Research Analyst'),
  ('ROLE-HTT-095', 'Destination Content Manager'),
  ('ROLE-HTT-096', 'Digital Tourism Product Manager'),
  ('ROLE-HTT-097', 'Tourist Facilitator'),
  ('ROLE-HTT-098', 'Tour Guide'),
  ('ROLE-HTT-099', 'Tourist Facilitator Trainee'),
  ('ROLE-HTT-100', 'Heritage Facilitator'),
  ('ROLE-HTT-101', 'ASI Field Officer'),
  ('ROLE-HTT-102', 'Heritage Site Manager'),
  ('ROLE-HTT-103', 'Heritage Site Operations Manager'),
  ('ROLE-HTT-104', 'Visitor Facility Manager'),
  ('ROLE-HTT-105', 'Monument Amenity Partner Manager'),
  ('ROLE-HTT-106', 'ASI Site Officer'),
  ('ROLE-HTT-107', 'Digital Heritage Content Coordinator'),
  ('ROLE-HTT-108', 'Heritage Visitor Experience Manager'),
  ('ROLE-HTT-109', 'Wildlife Interpretation Coordinator'),
  ('ROLE-HTT-110', 'Local Youth Experience Operator'),
  ('ROLE-HTT-111', 'Adventure Tour Operator'),
  ('ROLE-HTT-112', 'Adventure Guide'),
  ('ROLE-HTT-113', 'Adventure Operations Manager'),
  ('ROLE-HTT-114', 'Trek Guide'),
  ('ROLE-HTT-115', 'Forest Tourism Officer'),
  ('ROLE-HTT-116', 'Rescue Coordinator'),
  ('ROLE-HTT-117', 'Safari Operations Manager'),
  ('ROLE-HTT-118', 'Tiger Reserve Field Officer'),
  ('ROLE-HTT-119', 'Safari Guide'),
  ('ROLE-HTT-120', 'Safari Driver'),
  ('ROLE-HTT-121', 'Gate/Check-post Officer'),
  ('ROLE-HTT-122', 'Medical Tourism Coordinator'),
  ('ROLE-HTT-123', 'Patient Travel Coordinator'),
  ('ROLE-HTT-124', 'AYUSH Tourism Promotion Officer'),
  ('ROLE-HTT-125', 'Medical Value Travel Coordinator'),
  ('ROLE-HTT-126', 'Ecotourism Planner'),
  ('ROLE-HTT-127', 'Destination Sustainability Officer'),
  ('ROLE-HTT-128', 'Sustainable Tourism Manager'),
  ('ROLE-HTT-129', 'Responsible Tourism Coordinator'),
  ('ROLE-HTT-130', 'Sustainability Officer'),
  ('ROLE-HTT-131', 'Community Tourism Coordinator'),
  ('ROLE-HTT-132', 'Responsible Tourism Facilitator'),
  ('ROLE-HTT-133', 'Rural Tourism Development Officer'),
  ('ROLE-HTT-134', 'Homestay Promotion Manager'),
  ('ROLE-HTT-135', 'Rural Tourism Portal Manager'),
  ('ROLE-HTT-136', 'Village Tourism Evaluator'),
  ('ROLE-HTT-137', 'Rural Homestay Coordinator'),
  ('ROLE-HTT-138', 'State Tourism Officer'),
  ('ROLE-HTT-139', 'Homestay Operator'),
  ('ROLE-HTT-140', 'District Tourism Officer');

-- Insert OCCUPATIONS_CONTEXT (Junction: occupation → domain)
INSERT INTO public.occupations_context (occupation_id, domain_id)
SELECT
  o.id,
  d.id
FROM (
  VALUES
  ('ROLE-HTT-001', 'D01'),
  ('ROLE-HTT-002', 'D01'),
  ('ROLE-HTT-003', 'D01'),
  ('ROLE-HTT-004', 'D01'),
  ('ROLE-HTT-005', 'D01'),
  ('ROLE-HTT-006', 'D01'),
  ('ROLE-HTT-007', 'D01'),
  ('ROLE-HTT-008', 'D01'),
  ('ROLE-HTT-009', 'D01'),
  ('ROLE-HTT-010', 'D01'),
  ('ROLE-HTT-011', 'D01'),
  ('ROLE-HTT-012', 'D01'),
  ('ROLE-HTT-013', 'D01'),
  ('ROLE-HTT-018', 'D02'),
  ('ROLE-HTT-019', 'D02'),
  ('ROLE-HTT-020', 'D02'),
  ('ROLE-HTT-021', 'D02'),
  ('ROLE-HTT-022', 'D02'),
  ('ROLE-HTT-023', 'D02'),
  ('ROLE-HTT-024', 'D02'),
  ('ROLE-HTT-025', 'D02'),
  ('ROLE-HTT-026', 'D02'),
  ('ROLE-HTT-027', 'D02'),
  ('ROLE-HTT-028', 'D02'),
  ('ROLE-HTT-029', 'D02'),
  ('ROLE-HTT-030', 'D02'),
  ('ROLE-HTT-031', 'D02'),
  ('ROLE-HTT-032', 'D03'),
  ('ROLE-HTT-033', 'D03'),
  ('ROLE-HTT-034', 'D03'),
  ('ROLE-HTT-035', 'D03'),
  ('ROLE-HTT-036', 'D03'),
  ('ROLE-HTT-037', 'D03'),
  ('ROLE-HTT-038', 'D03'),
  ('ROLE-HTT-039', 'D03'),
  ('ROLE-HTT-040', 'D03'),
  ('ROLE-HTT-041', 'D03'),
  ('ROLE-HTT-042', 'D03'),
  ('ROLE-HTT-043', 'D03'),
  ('ROLE-HTT-044', 'D03'),
  ('ROLE-HTT-045', 'D03'),
  ('ROLE-HTT-046', 'D03'),
  ('ROLE-HTT-047', 'D03'),
  ('ROLE-HTT-048', 'D03'),
  ('ROLE-HTT-058', 'D04'),
  ('ROLE-HTT-059', 'D04'),
  ('ROLE-HTT-060', 'D04'),
  ('ROLE-HTT-061', 'D04'),
  ('ROLE-HTT-062', 'D04'),
  ('ROLE-HTT-063', 'D04'),
  ('ROLE-HTT-064', 'D04'),
  ('ROLE-HTT-065', 'D04'),
  ('ROLE-HTT-066', 'D04'),
  ('ROLE-HTT-067', 'D04'),
  ('ROLE-HTT-068', 'D04'),
  ('ROLE-HTT-069', 'D04'),
  ('ROLE-HTT-070', 'D04'),
  ('ROLE-HTT-071', 'D04'),
  ('ROLE-HTT-072', 'D04'),
  ('ROLE-HTT-073', 'D05'),
  ('ROLE-HTT-074', 'D05'),
  ('ROLE-HTT-075', 'D05'),
  ('ROLE-HTT-076', 'D05'),
  ('ROLE-HTT-077', 'D05'),
  ('ROLE-HTT-078', 'D05'),
  ('ROLE-HTT-079', 'D05'),
  ('ROLE-HTT-080', 'D05'),
  ('ROLE-HTT-081', 'D05'),
  ('ROLE-HTT-082', 'D05'),
  ('ROLE-HTT-083', 'D05'),
  ('ROLE-HTT-084', 'D05'),
  ('ROLE-HTT-085', 'D05'),
  ('ROLE-HTT-086', 'D05'),
  ('ROLE-HTT-087', 'D05'),
  ('ROLE-HTT-088', 'D05'),
  ('ROLE-HTT-089', 'D06'),
  ('ROLE-HTT-090', 'D06'),
  ('ROLE-HTT-091', 'D06'),
  ('ROLE-HTT-092', 'D06'),
  ('ROLE-HTT-093', 'D06'),
  ('ROLE-HTT-094', 'D06'),
  ('ROLE-HTT-095', 'D06'),
  ('ROLE-HTT-096', 'D06'),
  ('ROLE-HTT-097', 'D06'),
  ('ROLE-HTT-098', 'D06'),
  ('ROLE-HTT-099', 'D06'),
  ('ROLE-HTT-100', 'D06'),
  ('ROLE-HTT-101', 'D06'),
  ('ROLE-HTT-102', 'D06'),
  ('ROLE-HTT-103', 'D06'),
  ('ROLE-HTT-104', 'D06'),
  ('ROLE-HTT-105', 'D06'),
  ('ROLE-HTT-106', 'D06'),
  ('ROLE-HTT-107', 'D06'),
  ('ROLE-HTT-108', 'D06'),
  ('ROLE-HTT-109', 'D06'),
  ('ROLE-HTT-110', 'D06'),
  ('ROLE-HTT-111', 'D07'),
  ('ROLE-HTT-112', 'D07'),
  ('ROLE-HTT-113', 'D07'),
  ('ROLE-HTT-114', 'D07'),
  ('ROLE-HTT-115', 'D07'),
  ('ROLE-HTT-116', 'D07'),
  ('ROLE-HTT-117', 'D07'),
  ('ROLE-HTT-118', 'D07'),
  ('ROLE-HTT-119', 'D07'),
  ('ROLE-HTT-120', 'D07'),
  ('ROLE-HTT-121', 'D07'),
  ('ROLE-HTT-122', 'D07'),
  ('ROLE-HTT-123', 'D07'),
  ('ROLE-HTT-124', 'D07'),
  ('ROLE-HTT-125', 'D07'),
  ('ROLE-HTT-126', 'D07'),
  ('ROLE-HTT-127', 'D07'),
  ('ROLE-HTT-128', 'D07'),
  ('ROLE-HTT-129', 'D07'),
  ('ROLE-HTT-130', 'D07'),
  ('ROLE-HTT-131', 'D07'),
  ('ROLE-HTT-132', 'D07'),
  ('ROLE-HTT-133', 'D07'),
  ('ROLE-HTT-134', 'D07'),
  ('ROLE-HTT-135', 'D07'),
  ('ROLE-HTT-136', 'D07'),
  ('ROLE-HTT-137', 'D07'),
  ('ROLE-HTT-138', 'D07'),
  ('ROLE-HTT-139', 'D07'),
  ('ROLE-HTT-140', 'D07')
) AS data(occ_code, domain_code)
JOIN public.occupations o ON o.code = data.occ_code
JOIN public.domains d ON d.code = data.domain_code;

-- Insert RIASEC_PROFILES (One-to-many: occupation → RIASEC profile codes)
INSERT INTO public.riasec_profiles (occupation_id, profile_code)
SELECT
  o.id,
  data.riasec_code
FROM (
  VALUES
  ('ROLE-HTT-001', 'SEC'),
  ('ROLE-HTT-002', 'SEC'),
  ('ROLE-HTT-003', 'SEC'),
  ('ROLE-HTT-004', 'SEC'),
  ('ROLE-HTT-005', 'SEC'),
  ('ROLE-HTT-006', 'SEC'),
  ('ROLE-HTT-007', 'SEC'),
  ('ROLE-HTT-008', 'SEC'),
  ('ROLE-HTT-009', 'SEC'),
  ('ROLE-HTT-010', 'SEC'),
  ('ROLE-HTT-011', 'SEC'),
  ('ROLE-HTT-012', 'SEC'),
  ('ROLE-HTT-013', 'SEC'),
  ('ROLE-HTT-018', 'RC'),
  ('ROLE-HTT-019', 'RC'),
  ('ROLE-HTT-020', 'RC'),
  ('ROLE-HTT-021', 'RC'),
  ('ROLE-HTT-022', 'RC'),
  ('ROLE-HTT-023', 'RC'),
  ('ROLE-HTT-024', 'RSC'),
  ('ROLE-HTT-025', 'RSC'),
  ('ROLE-HTT-026', 'RSC'),
  ('ROLE-HTT-027', 'RSC'),
  ('ROLE-HTT-028', 'SC'),
  ('ROLE-HTT-029', 'SC'),
  ('ROLE-HTT-030', 'SC'),
  ('ROLE-HTT-031', 'SC'),
  ('ROLE-HTT-032', 'RSEC'),
  ('ROLE-HTT-033', 'RSEC'),
  ('ROLE-HTT-034', 'RSEC'),
  ('ROLE-HTT-035', 'RSEC'),
  ('ROLE-HTT-036', 'RSEC'),
  ('ROLE-HTT-037', 'RSC'),
  ('ROLE-HTT-038', 'RSC'),
  ('ROLE-HTT-039', 'SEC'),
  ('ROLE-HTT-040', 'SEC'),
  ('ROLE-HTT-041', 'SEC'),
  ('ROLE-HTT-042', 'SEC'),
  ('ROLE-HTT-043', 'SEC'),
  ('ROLE-HTT-044', 'SEC'),
  ('ROLE-HTT-045', 'SEC'),
  ('ROLE-HTT-046', 'SEC'),
  ('ROLE-HTT-047', 'SEC'),
  ('ROLE-HTT-048', 'SEC'),
  ('ROLE-HTT-058', 'RSC'),
  ('ROLE-HTT-059', 'RSC'),
  ('ROLE-HTT-060', 'RSC'),
  ('ROLE-HTT-061', 'RSC'),
  ('ROLE-HTT-062', 'RSC'),
  ('ROLE-HTT-063', 'RSC'),
  ('ROLE-HTT-064', 'RSC'),
  ('ROLE-HTT-065', 'RSC'),
  ('ROLE-HTT-066', 'RSC'),
  ('ROLE-HTT-067', 'RSC'),
  ('ROLE-HTT-068', 'RSC'),
  ('ROLE-HTT-069', 'RSC'),
  ('ROLE-HTT-070', 'RSC'),
  ('ROLE-HTT-071', 'RSC'),
  ('ROLE-HTT-072', 'RSC'),
  ('ROLE-HTT-073', 'SEC'),
  ('ROLE-HTT-074', 'SEC'),
  ('ROLE-HTT-075', 'SEC'),
  ('ROLE-HTT-076', 'SEC'),
  ('ROLE-HTT-077', 'SEC'),
  ('ROLE-HTT-078', 'SEC'),
  ('ROLE-HTT-079', 'SEC'),
  ('ROLE-HTT-080', 'SEC'),
  ('ROLE-HTT-081', 'SEC'),
  ('ROLE-HTT-082', 'SEC'),
  ('ROLE-HTT-083', 'IEC'),
  ('ROLE-HTT-084', 'IEC'),
  ('ROLE-HTT-085', 'IEC'),
  ('ROLE-HTT-086', 'IEC'),
  ('ROLE-HTT-087', 'IEC'),
  ('ROLE-HTT-088', 'IEC'),
  ('ROLE-HTT-089', 'IAC'),
  ('ROLE-HTT-090', 'IAC'),
  ('ROLE-HTT-091', 'IAC'),
  ('ROLE-HTT-092', 'IAC'),
  ('ROLE-HTT-093', 'IAC'),
  ('ROLE-HTT-094', 'IAC'),
  ('ROLE-HTT-095', 'IAC'),
  ('ROLE-HTT-096', 'IAC'),
  ('ROLE-HTT-097', 'ASC'),
  ('ROLE-HTT-098', 'ASC'),
  ('ROLE-HTT-099', 'ASC'),
  ('ROLE-HTT-100', 'ASC'),
  ('ROLE-HTT-101', 'ASC'),
  ('ROLE-HTT-102', 'ASC'),
  ('ROLE-HTT-103', 'ASC'),
  ('ROLE-HTT-104', 'ASC'),
  ('ROLE-HTT-105', 'ASC'),
  ('ROLE-HTT-106', 'ASC'),
  ('ROLE-HTT-107', 'ASC'),
  ('ROLE-HTT-108', 'ASC'),
  ('ROLE-HTT-109', 'ASC'),
  ('ROLE-HTT-110', 'ASC'),
  ('ROLE-HTT-111', 'RSC'),
  ('ROLE-HTT-112', 'RSC'),
  ('ROLE-HTT-113', 'RSC'),
  ('ROLE-HTT-114', 'RSC'),
  ('ROLE-HTT-115', 'RSC'),
  ('ROLE-HTT-116', 'RSC'),
  ('ROLE-HTT-117', 'RSC'),
  ('ROLE-HTT-118', 'RSC'),
  ('ROLE-HTT-119', 'RSC'),
  ('ROLE-HTT-120', 'RSC'),
  ('ROLE-HTT-121', 'RSC'),
  ('ROLE-HTT-122', 'SC'),
  ('ROLE-HTT-123', 'SC'),
  ('ROLE-HTT-124', 'SC'),
  ('ROLE-HTT-125', 'SC'),
  ('ROLE-HTT-126', 'RASC'),
  ('ROLE-HTT-127', 'RASC'),
  ('ROLE-HTT-128', 'RASC'),
  ('ROLE-HTT-129', 'RASC'),
  ('ROLE-HTT-130', 'RASC'),
  ('ROLE-HTT-131', 'RASC'),
  ('ROLE-HTT-132', 'RASC'),
  ('ROLE-HTT-133', 'RASC'),
  ('ROLE-HTT-134', 'RASC'),
  ('ROLE-HTT-135', 'RASC'),
  ('ROLE-HTT-136', 'RASC'),
  ('ROLE-HTT-137', 'RASC'),
  ('ROLE-HTT-138', 'RASC'),
  ('ROLE-HTT-139', 'RASC'),
  ('ROLE-HTT-140', 'RASC')
) AS data(occ_code, riasec_code)
JOIN public.occupations o ON o.code = data.occ_code;

-- Insert OCCUPATIONS_CAPABILITIES_MASTER (Junction: occupation → capability_master)
INSERT INTO public.occupations_capabilities_master (occupation_id, capability_id)
SELECT
  o.id,
  c.id
FROM (
  VALUES
  ('ROLE-HTT-001', 'IND-CAP-01'),
  ('ROLE-HTT-002', 'IND-CAP-01'),
  ('ROLE-HTT-003', 'IND-CAP-01'),
  ('ROLE-HTT-004', 'IND-CAP-01'),
  ('ROLE-HTT-005', 'IND-CAP-01'),
  ('ROLE-HTT-006', 'IND-CAP-01'),
  ('ROLE-HTT-007', 'IND-CAP-03'),
  ('ROLE-HTT-008', 'IND-CAP-03'),
  ('ROLE-HTT-009', 'IND-CAP-03'),
  ('ROLE-HTT-010', 'IND-CAP-03'),
  ('ROLE-HTT-011', 'IND-CAP-03'),
  ('ROLE-HTT-012', 'IND-CAP-03'),
  ('ROLE-HTT-013', 'IND-CAP-03'),
  ('ROLE-HTT-018', 'IND-CAP-04'),
  ('ROLE-HTT-019', 'IND-CAP-04'),
  ('ROLE-HTT-020', 'IND-CAP-04'),
  ('ROLE-HTT-021', 'IND-CAP-04'),
  ('ROLE-HTT-022', 'IND-CAP-04'),
  ('ROLE-HTT-023', 'IND-CAP-04'),
  ('ROLE-HTT-024', 'IND-CAP-05'),
  ('ROLE-HTT-025', 'IND-CAP-05'),
  ('ROLE-HTT-026', 'IND-CAP-05'),
  ('ROLE-HTT-027', 'IND-CAP-05'),
  ('ROLE-HTT-028', 'IND-CAP-06'),
  ('ROLE-HTT-029', 'IND-CAP-06'),
  ('ROLE-HTT-030', 'IND-CAP-06'),
  ('ROLE-HTT-031', 'IND-CAP-06'),
  ('ROLE-HTT-032', 'IND-CAP-07'),
  ('ROLE-HTT-033', 'IND-CAP-07'),
  ('ROLE-HTT-034', 'IND-CAP-07'),
  ('ROLE-HTT-035', 'IND-CAP-07'),
  ('ROLE-HTT-036', 'IND-CAP-07'),
  ('ROLE-HTT-037', 'IND-CAP-08'),
  ('ROLE-HTT-038', 'IND-CAP-08'),
  ('ROLE-HTT-039', 'IND-CAP-10'),
  ('ROLE-HTT-040', 'IND-CAP-10'),
  ('ROLE-HTT-041', 'IND-CAP-10'),
  ('ROLE-HTT-042', 'IND-CAP-10'),
  ('ROLE-HTT-043', 'IND-CAP-10'),
  ('ROLE-HTT-044', 'IND-CAP-10'),
  ('ROLE-HTT-045', 'IND-CAP-10'),
  ('ROLE-HTT-046', 'IND-CAP-10'),
  ('ROLE-HTT-047', 'IND-CAP-10'),
  ('ROLE-HTT-048', 'IND-CAP-10'),
  ('ROLE-HTT-058', 'IND-CAP-12'),
  ('ROLE-HTT-059', 'IND-CAP-12'),
  ('ROLE-HTT-060', 'IND-CAP-12'),
  ('ROLE-HTT-061', 'IND-CAP-12'),
  ('ROLE-HTT-062', 'IND-CAP-12'),
  ('ROLE-HTT-063', 'IND-CAP-12'),
  ('ROLE-HTT-064', 'IND-CAP-12'),
  ('ROLE-HTT-065', 'IND-CAP-12'),
  ('ROLE-HTT-066', 'IND-CAP-13'),
  ('ROLE-HTT-067', 'IND-CAP-13'),
  ('ROLE-HTT-068', 'IND-CAP-13'),
  ('ROLE-HTT-069', 'IND-CAP-13'),
  ('ROLE-HTT-070', 'IND-CAP-14'),
  ('ROLE-HTT-071', 'IND-CAP-14'),
  ('ROLE-HTT-072', 'IND-CAP-14'),
  ('ROLE-HTT-073', 'IND-CAP-15'),
  ('ROLE-HTT-074', 'IND-CAP-15'),
  ('ROLE-HTT-075', 'IND-CAP-15'),
  ('ROLE-HTT-076', 'IND-CAP-15'),
  ('ROLE-HTT-077', 'IND-CAP-15'),
  ('ROLE-HTT-078', 'IND-CAP-15'),
  ('ROLE-HTT-079', 'IND-CAP-16'),
  ('ROLE-HTT-079', 'IND-CAP-18'),
  ('ROLE-HTT-080', 'IND-CAP-16'),
  ('ROLE-HTT-080', 'IND-CAP-18'),
  ('ROLE-HTT-081', 'IND-CAP-16'),
  ('ROLE-HTT-081', 'IND-CAP-18'),
  ('ROLE-HTT-082', 'IND-CAP-16'),
  ('ROLE-HTT-082', 'IND-CAP-18'),
  ('ROLE-HTT-083', 'IND-CAP-17'),
  ('ROLE-HTT-084', 'IND-CAP-17'),
  ('ROLE-HTT-085', 'IND-CAP-17'),
  ('ROLE-HTT-086', 'IND-CAP-17'),
  ('ROLE-HTT-087', 'IND-CAP-17'),
  ('ROLE-HTT-088', 'IND-CAP-17'),
  ('ROLE-HTT-089', 'IND-CAP-19'),
  ('ROLE-HTT-090', 'IND-CAP-19'),
  ('ROLE-HTT-091', 'IND-CAP-19'),
  ('ROLE-HTT-092', 'IND-CAP-19'),
  ('ROLE-HTT-093', 'IND-CAP-19'),
  ('ROLE-HTT-094', 'IND-CAP-19'),
  ('ROLE-HTT-095', 'IND-CAP-19'),
  ('ROLE-HTT-096', 'IND-CAP-19'),
  ('ROLE-HTT-097', 'IND-CAP-21'),
  ('ROLE-HTT-097', 'IND-CAP-20'),
  ('ROLE-HTT-098', 'IND-CAP-21'),
  ('ROLE-HTT-098', 'IND-CAP-20'),
  ('ROLE-HTT-099', 'IND-CAP-21'),
  ('ROLE-HTT-099', 'IND-CAP-20'),
  ('ROLE-HTT-100', 'IND-CAP-21'),
  ('ROLE-HTT-100', 'IND-CAP-20'),
  ('ROLE-HTT-101', 'IND-CAP-21'),
  ('ROLE-HTT-101', 'IND-CAP-20'),
  ('ROLE-HTT-102', 'IND-CAP-21'),
  ('ROLE-HTT-102', 'IND-CAP-20'),
  ('ROLE-HTT-103', 'IND-CAP-21'),
  ('ROLE-HTT-103', 'IND-CAP-20'),
  ('ROLE-HTT-104', 'IND-CAP-21'),
  ('ROLE-HTT-104', 'IND-CAP-20'),
  ('ROLE-HTT-105', 'IND-CAP-21'),
  ('ROLE-HTT-105', 'IND-CAP-20'),
  ('ROLE-HTT-106', 'IND-CAP-21'),
  ('ROLE-HTT-106', 'IND-CAP-20'),
  ('ROLE-HTT-107', 'IND-CAP-21'),
  ('ROLE-HTT-107', 'IND-CAP-20'),
  ('ROLE-HTT-108', 'IND-CAP-21'),
  ('ROLE-HTT-108', 'IND-CAP-20'),
  ('ROLE-HTT-109', 'IND-CAP-21'),
  ('ROLE-HTT-109', 'IND-CAP-20'),
  ('ROLE-HTT-110', 'IND-CAP-21'),
  ('ROLE-HTT-110', 'IND-CAP-20'),
  ('ROLE-HTT-111', 'IND-CAP-23'),
  ('ROLE-HTT-111', 'IND-CAP-24'),
  ('ROLE-HTT-112', 'IND-CAP-23'),
  ('ROLE-HTT-112', 'IND-CAP-24'),
  ('ROLE-HTT-113', 'IND-CAP-23'),
  ('ROLE-HTT-113', 'IND-CAP-24'),
  ('ROLE-HTT-114', 'IND-CAP-23'),
  ('ROLE-HTT-114', 'IND-CAP-24'),
  ('ROLE-HTT-115', 'IND-CAP-23'),
  ('ROLE-HTT-115', 'IND-CAP-24'),
  ('ROLE-HTT-116', 'IND-CAP-23'),
  ('ROLE-HTT-116', 'IND-CAP-24'),
  ('ROLE-HTT-117', 'IND-CAP-23'),
  ('ROLE-HTT-117', 'IND-CAP-24'),
  ('ROLE-HTT-118', 'IND-CAP-23'),
  ('ROLE-HTT-118', 'IND-CAP-24'),
  ('ROLE-HTT-119', 'IND-CAP-23'),
  ('ROLE-HTT-119', 'IND-CAP-24'),
  ('ROLE-HTT-120', 'IND-CAP-23'),
  ('ROLE-HTT-120', 'IND-CAP-24'),
  ('ROLE-HTT-121', 'IND-CAP-23'),
  ('ROLE-HTT-121', 'IND-CAP-24'),
  ('ROLE-HTT-122', 'IND-CAP-25'),
  ('ROLE-HTT-123', 'IND-CAP-25'),
  ('ROLE-HTT-124', 'IND-CAP-25'),
  ('ROLE-HTT-125', 'IND-CAP-25'),
  ('ROLE-HTT-126', 'IND-CAP-26'),
  ('ROLE-HTT-126', 'IND-CAP-27'),
  ('ROLE-HTT-127', 'IND-CAP-26'),
  ('ROLE-HTT-127', 'IND-CAP-27'),
  ('ROLE-HTT-128', 'IND-CAP-26'),
  ('ROLE-HTT-128', 'IND-CAP-27'),
  ('ROLE-HTT-129', 'IND-CAP-26'),
  ('ROLE-HTT-129', 'IND-CAP-27'),
  ('ROLE-HTT-130', 'IND-CAP-26'),
  ('ROLE-HTT-130', 'IND-CAP-27'),
  ('ROLE-HTT-131', 'IND-CAP-26'),
  ('ROLE-HTT-131', 'IND-CAP-27'),
  ('ROLE-HTT-132', 'IND-CAP-26'),
  ('ROLE-HTT-132', 'IND-CAP-27'),
  ('ROLE-HTT-133', 'IND-CAP-26'),
  ('ROLE-HTT-133', 'IND-CAP-27'),
  ('ROLE-HTT-134', 'IND-CAP-26'),
  ('ROLE-HTT-134', 'IND-CAP-27'),
  ('ROLE-HTT-135', 'IND-CAP-26'),
  ('ROLE-HTT-135', 'IND-CAP-27'),
  ('ROLE-HTT-136', 'IND-CAP-26'),
  ('ROLE-HTT-136', 'IND-CAP-27'),
  ('ROLE-HTT-137', 'IND-CAP-26'),
  ('ROLE-HTT-137', 'IND-CAP-27'),
  ('ROLE-HTT-138', 'IND-CAP-26'),
  ('ROLE-HTT-138', 'IND-CAP-27'),
  ('ROLE-HTT-139', 'IND-CAP-26'),
  ('ROLE-HTT-139', 'IND-CAP-27'),
  ('ROLE-HTT-140', 'IND-CAP-26'),
  ('ROLE-HTT-140', 'IND-CAP-27')
) AS data(occ_code, cap_code)
JOIN public.occupations o ON o.code = data.occ_code
JOIN public.capabilities_master c ON c.code = data.cap_code;

COMMIT;