-- Generated from Rareminds_Pan_India_Fresher_Opportunity_Tracker 4.xlsx.
-- Source rows: 841; generated by scripts/generate-rareminds-opportunity-seed.cjs.
-- Owner/organization setup; opportunity rows are in the following batch migrations.
-- Idempotency key: company_name + job_title + location + application_link.
-- Static values are SQL-escaped by sqlText(); no runtime/user input is executed.

-- Opportunity ownership prefers recruiter krishna@rareminds.in, falls
-- back to organization admin visakh@rareminds.in, and finally to an
-- approved Rareminds recruiter.
-- A Rareminds organization is created only when missing. No auth user or
-- recruiter identity is fabricated. Clean local databases may therefore have
-- NULL ownership until the recruiter user is seeded; learners can still apply.
-- Public application contact: careers@rareminds.in. No password is stored here.

BEGIN;

DO $seed_owner$
DECLARE
  v_organization_id uuid;
  v_recruiter_user_id uuid;
BEGIN
  SELECT r.user_id
    INTO v_recruiter_user_id
  FROM public.recruiters r
  WHERE lower(r.email) IN (lower('krishna@rareminds.in'), lower('visakh@rareminds.in'))
     OR lower(r.name) LIKE '%rareminds%'
  ORDER BY
    CASE lower(r.email)
      WHEN lower('krishna@rareminds.in') THEN 0
      WHEN lower('visakh@rareminds.in') THEN 1
      ELSE 2
    END,
    CASE WHEN COALESCE(r.isactive, TRUE) THEN 0 ELSE 1 END,
    r.createdat NULLS LAST,
    r.id
  LIMIT 1;

  -- Preserve the production association when it already exists. Only resolve
  -- or create the fallback Rareminds organization for an unassociated user.
  SELECT u."organizationId"
    INTO v_organization_id
  FROM public.users u
  WHERE u.id = v_recruiter_user_id;

  -- Krishna was invited by the organization admin. If Krishna's local shadow
  -- user has not received the association yet, inherit Visakh's organization.
  IF v_organization_id IS NULL THEN
    SELECT u."organizationId"
      INTO v_organization_id
    FROM public.recruiters r
    JOIN public.users u ON u.id = r.user_id
    WHERE lower(r.email) = lower('visakh@rareminds.in')
      AND u."organizationId" IS NOT NULL
    ORDER BY r.createdat NULLS LAST, r.id
    LIMIT 1;
  END IF;

  IF v_organization_id IS NULL THEN
    SELECT o.id
      INTO v_organization_id
    FROM public.organizations o
    WHERE lower(o.name) = lower('Rareminds')
    ORDER BY o.created_at NULLS LAST, o.id
    LIMIT 1;
  END IF;

  IF v_organization_id IS NULL THEN
    INSERT INTO public.organizations (
      id, name, description, email, website, verification_status, is_active,
      approval_status, account_status, organization_type, metadata
    ) VALUES (
      '3f43ef6c-e6de-5f5d-a5d1-dfe342a49587',
      'Rareminds',
      'Rareminds opportunity publishing organization',
      'careers@rareminds.in',
      'https://rareminds.in',
      'approved', TRUE, 'approved', 'active', 'company',
      '{"seed_key":"rareminds-opportunity-publisher"}'::jsonb
    )
    ON CONFLICT (id) DO UPDATE SET
      name = EXCLUDED.name,
      updated_at = now()
    RETURNING id INTO v_organization_id;
  END IF;

  -- Fix the missing local association without overwriting a valid production
  -- organization assignment.
  UPDATE public.users
  SET "organizationId" = v_organization_id,
      "updatedAt" = now()
  WHERE id = v_recruiter_user_id
    AND "organizationId" IS NULL;
END
$seed_owner$;

COMMIT;
