-- ============================================================================
-- Seed Data: Capability Master (UNIQUE capabilities only)
-- Source: Master sheet.xlsx - Capability master sheet (UPDATED DESCRIPTIONS)
-- Date: 2026-06-23
-- Table: public.capability_master
-- Note: Stores UNIQUE capabilities only (duplicates removed)
--       Role-to-capability mapping handled in role_capability_sequence
-- ============================================================================


INSERT INTO public.capability_master (
  code, name, description, master_sequence, capability_status,
  primary_riasec, secondary_riasec, work_style_demands, created_at, updated_at
)
VALUES
  (
    'IND-CAP-01',
    'Build governed lakehouse pipeline outputs with contract, quality, and lineage evidence',
    'Cluster covers onboarding source profiling, lineage registration, quality control, reconciliation, and exception evidence required to produce trusted bronze-to-silver data outputs.',
    1,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Build governed lakehouse pipeline outputs with contract, quality, and lineage evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-02',
    'Publish governed gold data products for BI and model consumers',
    'Cluster covers translating metric definitions, joining curated data, reconciling values, registering assets, and packaging consumer-ready query patterns.',
    2,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Publish governed gold data products for BI and model consumers. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-03',
    'Stabilize streaming data contracts and pipeline quality controls',
    'Cluster covers streaming/schema exceptions, parser updates, controlled replay, quality controls, and governed metadata evidence for reliable data operations.',
    3,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Stabilize streaming data contracts and pipeline quality controls. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-04',
    'Certify BI reporting and self-service analytics assets with governed metric evidence',
    'Cluster covers KPI refresh, filter-context review, certified analytics dataset preparation, and semantic measure selection for trusted business reporting.',
    4,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Certify BI reporting and self-service analytics assets with governed metric evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-05',
    'Produce decision recommendations through optimization and forecast review evidence',
    'Cluster covers constraint scenario modeling, feasible optimization output, forecast confidence review, and business override evidence for decision support.',
    5,
    'Core',
    ARRAY['I'],
    ARRAY['E'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, commercial prioritization, vendor/client follow-up, and outcome ownership for Produce decision recommendations through optimization and forecast review evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-06',
    'Construct leakage-safe predictive feature datasets for model experimentation',
    'Cluster covers selecting prediction-aligned sources, building feature datasets, preserving training versions, and preventing leakage before experimentation.',
    6,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Construct leakage-safe predictive feature datasets for model experimentation. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-07',
    'Evaluate statistical experiments and cohort effects for decision evidence',
    'Cluster covers validity checks, effect interpretation, heterogeneous cohort review, and decision evidence for experimentation outcomes.',
    7,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Evaluate statistical experiments and cohort effects for decision evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-08',
    'Train and package deep learning model candidates with evaluation evidence',
    'Cluster covers deep learning training evidence, checkpoint/metric tracking, and package preparation for product or production handoff.',
    8,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Train and package deep learning model candidates with evaluation evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-09',
    'Evaluate NLP and LLM candidates with task metrics, schema compliance, and failure analysis',
    'Cluster covers LLM/NLP metric review, hallucination and unsafe-output failure clustering, schema compliance, and evaluation evidence handoff.',
    9,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Evaluate NLP and LLM candidates with task metrics, schema compliance, and failure analysis. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-10',
    'Operate canary model releases with versioned rollout and rollback evidence',
    'Cluster covers deployment manifests, model package versioning, endpoint telemetry, rollout observation, and rollback decision evidence.',
    10,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Operate canary model releases with versioned rollout and rollback evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-11',
    'Respond to model drift and feature-skew alerts with production action decisions',
    'Cluster covers drift alert investigation, distribution evidence review, upstream data change assessment, and production response decisioning.',
    11,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Respond to model drift and feature-skew alerts with production action decisions. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-12',
    'Deploy edge AI inference and convert IoT anomaly signals into maintenance recommendations',
    'Cluster covers edge inference compatibility and telemetry confirmation together with sensor anomaly translation into maintenance recommendations.',
    12,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Deploy edge AI inference and convert IoT anomaly signals into maintenance recommendations. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-13',
    'Maintain governed lineage, classification, access, and stewardship controls for data assets',
    'Cluster covers lineage dependencies, classifications, retention metadata, owner attestations, entitlement review, and audit-ready governance records.',
    13,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Maintain governed lineage, classification, access, and stewardship controls for data assets. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-14',
    'Approve responsible AI deployment through use-case, privacy, fairness, and residual-risk controls',
    'Cluster covers AI use-case registration, responsible AI assessment, privacy/sensitive-attribute review, mitigation ownership, and gate decisioning.',
    14,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Approve responsible AI deployment through use-case, privacy, fairness, and residual-risk controls. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-15',
    'Test AI security abuse paths and sensitive-output exposure controls',
    'Cluster covers prompt, retrieval, tool-use, and data-exposure abuse path testing with security control evidence.',
    15,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Test AI security abuse paths and sensitive-output exposure controls. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-16',
    'Specify GenAI product features with grounding, output contracts, and release boundaries',
    'Cluster covers user journey, interaction sequence, grounding constraints, owner readiness, scope alignment, and feature specification publication.',
    16,
    'Core',
    ARRAY['A'],
    ARRAY['I'],
    'Requires creative judgement, experience sensitivity, and presentation quality, evidence analysis, exception diagnosis, and quality/risk interpretation for Specify GenAI product features with grounding, output contracts, and release boundaries. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-17',
    'Validate human-AI workflows with user evidence, fallback controls, and product change decisions',
    'Cluster covers workflow acceptance tests, user edit and trust signals, explanation/control needs, prioritized changes, and readiness evidence.',
    17,
    'Core',
    ARRAY['A'],
    ARRAY['I'],
    'Requires creative judgement, experience sensitivity, and presentation quality, evidence analysis, exception diagnosis, and quality/risk interpretation for Validate human-AI workflows with user evidence, fallback controls, and product change decisions. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-18',
    'Configure applied industry AI solutions with domain thresholds, SME review, and handoff guidance',
    'Cluster covers vertical AI thresholds, business action-path mapping, human specialist deferral rules, and deployment handoff documentation.',
    18,
    'Core',
    ARRAY['E'],
    ARRAY['I'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, evidence analysis, exception diagnosis, and quality/risk interpretation for Configure applied industry AI solutions with domain thresholds, SME review, and handoff guidance. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-19',
    'Design enterprise AI adoption roadmaps with operating model, initiative sequencing, and value metrics',
    'Cluster covers transformation roadmap design, candidate initiative inventory, workstream clustering, operating model logic, and value-tracking structure.',
    19,
    'Core',
    ARRAY['E'],
    ARRAY['S'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, high-contact stakeholder communication and service recovery for Design enterprise AI adoption roadmaps with operating model, initiative sequencing, and value metrics. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-20',
    'Control AI-ready training data quality through annotation adjudication and synthetic release evidence',
    'Cluster covers label disagreement adjudication, guideline clarification, synthetic dataset generation, fidelity checks, privacy checks, and release limits.',
    20,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Control AI-ready training data quality through annotation adjudication and synthetic release evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-21',
    'Model and validate semantic knowledge graph relationships for enrichment release',
    'Cluster covers entity and relationship modeling, ontology alignment, graph quality review, correction queue creation, and semantic release decisioning.',
    21,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Model and validate semantic knowledge graph relationships for enrichment release. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-001',
    'Field Crop Season Planning and Establishment Control',
    'Plan and evidence-control field crop season setup from plot history, input readiness and sowing records through early establishment exceptions.',
    1,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for Field Crop Season Planning and Establishment Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-002',
    'Field Crop Scouting, Pest Exception and Harvest Lot Handoff',
    'Monitor crop condition, flag pest/disease or harvest-readiness exceptions, and hand off harvest lots with procurement-quality evidence.',
    2,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for Field Crop Scouting, Pest Exception and Harvest Lot Handoff. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-003',
    'Nursery and Protected Cultivation Crop-Cycle Evidence Control',
    'Manage evidence for nursery propagation and protected cultivation cycles from batch setup through crop-condition exceptions and dispatch/cycle status.',
    3,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Nursery and Protected Cultivation Crop-Cycle Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-004',
    'Orchard, Plantation and Pack-Grade Harvest Readiness Control',
    'Coordinate orchard or plantation block review, action handoff, harvest maturity assessment and pack-grade lot segregation.',
    4,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Orchard, Plantation and Pack-Grade Harvest Readiness Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-005',
    'Dairy and Poultry Farm Output, Feed and Performance Control',
    'Maintain daily dairy and poultry operating evidence across output recording, feed/housing checks, mortality/performance variance and supervisor review.',
    5,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Dairy and Poultry Farm Output, Feed and Performance Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-006',
    'Animal Health, Breeding and Biosecurity Evidence Support',
    'Support vaccination, breeding, disease-observation and biosecurity evidence workflows while preserving veterinary and statutory authority boundaries.',
    6,
    'Core',
    ARRAY['I'],
    ARRAY['R'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, site/operations awareness, safety discipline, and practical execution follow-through for Animal Health, Breeding and Biosecurity Evidence Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-007',
    'Aquaculture Stocking, Feed Cycle and Hatchery Batch Control',
    'Control aquaculture production evidence from pond/cage stocking and feed-cycle monitoring through hatchery batch quality and seed dispatch.',
    7,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for Aquaculture Stocking, Feed Cycle and Hatchery Batch Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-008',
    'Fishery Landing, Harvest Lot and Cold-Chain Handoff Control',
    'Register fishery catch/harvest lots, quality-segregate landing output, and maintain cold-chain handoff evidence through receiving confirmation.',
    8,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for Fishery Landing, Harvest Lot and Cold-Chain Handoff Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-009',
    'Agroforestry, Plantation and Bamboo Field Operations Support',
    'Support agroforestry, plantation and bamboo field activities through activity records, survival observations, harvest-readiness evidence and authorized handoff.',
    9,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Agroforestry, Plantation and Bamboo Field Operations Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-010',
    'NTFP Collection and Forest Monitoring Evidence Preparation',
    'Prepare community forest produce and monitoring evidence through lot registration, quality checks, monitoring entries and authorized review packets.',
    10,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for NTFP Collection and Forest Monitoring Evidence Preparation. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-011',
    'Soil-Test Input Advisory and Dealer Support Evidence Control',
    'Operate support evidence for soil-test advisory, input demand and dealer/farmer product-use interactions while avoiding unsafe or off-label authority.',
    11,
    'Core',
    ARRAY['E'],
    ARRAY['S'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, high-contact stakeholder communication and service recovery for Soil-Test Input Advisory and Dealer Support Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-012',
    'Mechanization, Precision and Digital Advisory Service Coordination',
    'Coordinate machinery service, field demonstrations, drone/remote-sensing observation and digital advisory handoffs with support-only boundaries.',
    12,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for Mechanization, Precision and Digital Advisory Service Coordination. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-013',
    'FPO Aggregation, Procurement and Market Linkage Execution Control',
    'Translate buyer orders into farmer/FPO aggregation plans and maintain procurement, weighment, dispatch and exception evidence.',
    13,
    'Core',
    ARRAY['E'],
    ARRAY['C'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, structured evidence capture, documentation accuracy, and controlled handoffs for FPO Aggregation, Procurement and Market Linkage Execution Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-AFF-014',
    'Packhouse Grading, Cold-Chain and Controlled Quality Documentation Support',
    'Operate packhouse grading, lot segregation, cold-chain logging and controlled quality/traceability documentation without certification authority.',
    14,
    'Core',
    ARRAY['C'],
    ARRAY['R'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, site/operations awareness, safety discipline, and practical execution follow-through for Packhouse Grading, Cold-Chain and Controlled Quality Documentation Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-BANK-001',
    'Execute banking service request intake, fulfilment tracking and audit-ready closure support',
    'Customer service request is captured, routed, tracked, closed or escalated with evidence.',
    1,
    'Core',
    ARRAY['S'],
    ARRAY['C'],
    'Requires high-contact stakeholder communication and service recovery, structured evidence capture, documentation accuracy, and controlled handoffs for Execute banking service request intake, fulfilment tracking and audit-ready closure support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-BANK-002',
    'Maintain customer account, KYC update and periodic-review evidence within regulated service boundaries',
    'Customer KYC / demographic and periodic-review records are checked, updated or escalated with audit trail.',
    2,
    'Core',
    ARRAY['C'],
    ARRAY['S'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, high-contact stakeholder communication and service recovery for Maintain customer account, KYC update and periodic-review evidence within regulated service boundaries. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-BANK-003',
    'Support relationship and SME banking interactions through boundary-safe documentation and handoffs',
    'Relationship / SME interaction is documented, evidence gaps are tracked and service / credit handoffs are prepared without advisory or approval authority.',
    3,
    'Core',
    ARRAY['S'],
    ARRAY['C'],
    'Requires high-contact stakeholder communication and service recovery, structured evidence capture, documentation accuracy, and controlled handoffs for Support relationship and SME banking interactions through boundary-safe documentation and handoffs. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-BANK-004',
    'Register, evidence and prepare banking complaint closure or escalation packets',
    'Banking complaint is categorized, acknowledged, evidenced, followed up and prepared for closure / escalation.',
    4,
    'Core',
    ARRAY['S'],
    ARRAY['C'],
    'Requires high-contact stakeholder communication and service recovery, structured evidence capture, documentation accuracy, and controlled handoffs for Register, evidence and prepare banking complaint closure or escalation packets. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CREDIT-001',
    'Support loan application intake, borrower evidence pre-screen and credit reviewer handoff',
    'Borrower case evidence, credit history, exposure notes and appraisal support packet are prepared for authorized reviewer.',
    5,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Support loan application intake, borrower evidence pre-screen and credit reviewer handoff. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CREDIT-002',
    'Track sanction conditions and prepare loan servicing handoff without disbursement authority',
    'Approved / conditional loan case is checked for pre-disbursement conditions and converted into a servicing handoff pack.',
    6,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Track sanction conditions and prepare loan servicing handoff without disbursement authority. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CREDIT-003',
    'Monitor portfolio early-warning indicators and support conduct-safe delinquency follow-up',
    'Portfolio risk signals are segmented, follow-ups assigned and recovery-conduct issues escalated safely.',
    7,
    'Core',
    ARRAY['I'],
    ARRAY['S'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, high-contact stakeholder communication and service recovery for Monitor portfolio early-warning indicators and support conduct-safe delinquency follow-up. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-PAY-001',
    'Coordinate payment rail product change, readiness and participant onboarding support',
    'Payment rail / participant change is intake-mapped, readiness-checked and handed off with participant ownership clarity.',
    8,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Coordinate payment rail product change, readiness and participant onboarding support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-PAY-002',
    'Support merchant acceptance onboarding and activation bottleneck resolution',
    'Merchant acceptance setup is documented, evidence-checked, bottlenecked issues are routed and activation status is retained.',
    9,
    'Core',
    ARRAY['E'],
    ARRAY['C'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, structured evidence capture, documentation accuracy, and controlled handoffs for Support merchant acceptance onboarding and activation bottleneck resolution. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-PAY-003',
    'Monitor payment product adoption, performance deviations and operations issue handoffs',
    'Payment product performance issue is segmented, evidenced, routed and tracked without changing rail rules.',
    10,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Monitor payment product adoption, performance deviations and operations issue handoffs. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-PAY-004',
    'Support payment settlement exception tracking and transaction reconciliation break closure',
    'Settlement and reconciliation exceptions are evidenced, assigned, investigated and closed or escalated.',
    11,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Support payment settlement exception tracking and transaction reconciliation break closure. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-PAY-005',
    'Support failed transaction, dispute, chargeback and fraud-signal escalation workflows',
    'Failed payment / dispute / fraud-signal case is categorized, evidenced, routed and escalated without liability decision.',
    12,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Support failed transaction, dispute, chargeback and fraud-signal escalation workflows. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CM-001',
    'Support securities trade lifecycle records, back-office enrichment and exception handoffs',
    'Securities trade record is captured, enriched, exception-routed and made client-query ready without trade advice.',
    13,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Support securities trade lifecycle records, back-office enrichment and exception handoffs. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CM-002',
    'Support exchange member, listing, market-data and surveillance evidence handoffs',
    'Exchange/member/surveillance support evidence is captured and routed without market-integrity judgment.',
    14,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Support exchange member, listing, market-data and surveillance evidence handoffs. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CM-003',
    'Support investor grievance intake, evidence handling and SCORES / ODR response preparation',
    'Investor complaint is registered, evidenced, tracked and prepared for response / escalation without adjudication.',
    15,
    'Core',
    ARRAY['S'],
    ARRAY['C'],
    'Requires high-contact stakeholder communication and service recovery, structured evidence capture, documentation accuracy, and controlled handoffs for Support investor grievance intake, evidence handling and SCORES / ODR response preparation. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CM-004',
    'Support securities clearing obligations, shortages, settlement movements and custody handoffs',
    'Clearing / settlement / custody exception evidence is reviewed, handed off and tracked without final clearing authority.',
    16,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Support securities clearing obligations, shortages, settlement movements and custody handoffs. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CM-005',
    'Process depository participant services and securities instruction support records',
    'DP service and demat / remat / pledge / transmission instruction is evidence-checked, statused and escalated.',
    17,
    'Core',
    ARRAY['C'],
    ARRAY['S'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, high-contact stakeholder communication and service recovery for Process depository participant services and securities instruction support records. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-CM-006',
    'Support RTA investor records, corporate action setup and beneficiary-position evidence handling',
    'Corporate action / RTA investor record case is checked, routed, statused and archived without authorization ownership.',
    18,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Support RTA investor records, corporate action setup and beneficiary-position evidence handling. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-X-001',
    'Execute KYC / CDD control review and high-risk onboarding exception support',
    'Cross-sector KYC / CDD and high-risk onboarding exception is checked, documented and handed to authorized owner.',
    19,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Execute KYC / CDD control review and high-risk onboarding exception support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-X-002',
    'Support sanctions screening, AML alert review and suspicious-transaction evidence handoff',
    'Screening / AML alert evidence is compared, summarized and escalated without sanctions or STR filing decision.',
    20,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Support sanctions screening, AML alert review and suspicious-transaction evidence handoff. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-X-003',
    'Prepare regulatory reporting, audit evidence and operational-risk support packs',
    'Report data, audit artifacts and risk-event evidence are prepared and tracked for authorized review.',
    21,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Prepare regulatory reporting, audit evidence and operational-risk support packs. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-001',
    'Execution-Ready Work Front Control',
    'Prepare and release construction work fronts only when design, permits, constraints, materials and site readiness evidence are aligned.',
    1,
    'Core',
    ARRAY['C'],
    ARRAY['R'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, site/operations awareness, safety discipline, and practical execution follow-through for Execution-Ready Work Front Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-002',
    'Inspection, Test and Corrective-Action Closure',
    'Verify constructed work through inspections, tests, NCR/defect decisions and closure evidence before acceptance or handover.',
    2,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Inspection, Test and Corrective-Action Closure. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-003',
    'Project Progress, Schedule and Recovery Control',
    'Maintain project progress visibility by updating schedules, identifying delays, preparing dashboards and issuing recovery actions.',
    3,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Project Progress, Schedule and Recovery Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-004',
    'Measurement, Billing and Contract Variation Control',
    'Convert verified site quantities and contract conditions into bill recommendations, variation records and audit-ready decision trails.',
    4,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Measurement, Billing and Contract Variation Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-005',
    'Design, BIM, RFI and Field-Change Resolution',
    'Resolve design/model/RFI conflicts by tracing affected work packages, coordinating discipline responses and issuing controlled field instructions.',
    5,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Design, BIM, RFI and Field-Change Resolution. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-006',
    'Commissioning and Handover Evidence Control',
    'Compile and validate testing, commissioning, as-built and handover evidence needed for asset acceptance.',
    6,
    'Core',
    ARRAY['C'],
    ARRAY['E'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, commercial prioritization, vendor/client follow-up, and outcome ownership for Commissioning and Handover Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-007',
    'DPR and Technical Design-Basis Validation',
    'Validate DPR assumptions, hydraulic/design calculations, technical sizing and review comments before project approval or procurement.',
    7,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for DPR and Technical Design-Basis Validation. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CIE-CAP-008',
    'Asset-Specific Interface and Authority Constraint Control',
    'Manage statutory, owner, authority, safety and operating-interface constraints that block execution or handover across specialized infrastructure assets.',
    8,
    'Core',
    ARRAY['C'],
    ARRAY['R'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, site/operations awareness, safety discipline, and practical execution follow-through for Asset-Specific Interface and Authority Constraint Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-22',
    'Run remedial intervention cycles using learning-gap diagnosis, practice evidence, and progress review',
    'Deliver and review remedial support by diagnosing learning gaps, assigning targeted practice, tracking learner response, and deciding continuation or closure.',
    22,
    'Core',
    ARRAY['C'],
    ARRAY['S'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, high-contact stakeholder communication and service recovery for Run remedial intervention cycles using learning-gap diagnosis, practice evidence, and progress review. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-23',
    'Convert learner profiles and market evidence into career guidance action plans',
    'Create career guidance plans by interpreting learner interests, evidence, aptitude, role options, pathway constraints, and action commitments.',
    23,
    'Core',
    ARRAY['C'],
    ARRAY['S'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, high-contact stakeholder communication and service recovery for Convert learner profiles and market evidence into career guidance action plans. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-24',
    'Manage language or performance coaching progress through diagnostic evidence, practice cycles, and feedback records',
    'Plan and track coaching interventions by diagnosing language or performance needs, assigning practice activities, monitoring progress evidence, and confirming improvement actions.',
    24,
    'Core',
    ARRAY['C'],
    ARRAY['S'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, high-contact stakeholder communication and service recovery for Manage language or performance coaching progress through diagnostic evidence, practice cycles, and feedback records. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-25',
    'Complete admissions operations through document verification, enrollment coding, and record activation',
    'Run admissions record operations by verifying documents, eligibility, identifiers, program selection, enrollment codes, and activation confirmations.',
    25,
    'Core',
    ARRAY['S'],
    ARRAY['A'],
    'Requires high-contact stakeholder communication and service recovery, creative judgement, experience sensitivity, and presentation quality for Complete admissions operations through document verification, enrollment coding, and record activation. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-26',
    'Produce education MIS reports through institution-code, learner-record, and data-quality controls',
    'Prepare MIS submissions by validating institutional codes, learner records, duplication rules, completeness checks, and final report submission evidence.',
    26,
    'Core',
    ARRAY['S'],
    ARRAY['A'],
    'Requires high-contact stakeholder communication and service recovery, creative judgement, experience sensitivity, and presentation quality for Produce education MIS reports through institution-code, learner-record, and data-quality controls. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-27',
    'Track government or NGO education programs through beneficiary, activity, utilization, and outcome evidence',
    'Monitor public or NGO education program execution by checking beneficiary records, activity completion, resource utilization, partner updates, and outcome reporting.',
    27,
    'Core',
    ARRAY['S'],
    ARRAY['A'],
    'Requires high-contact stakeholder communication and service recovery, creative judgement, experience sensitivity, and presentation quality for Track government or NGO education programs through beneficiary, activity, utilization, and outcome evidence. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-28',
    'Coordinate research and academic publishing cycles through study evidence, review workflow, and publication records',
    'Support research and publishing operations by organizing study materials, review status, manuscript or article records, editorial decisions, and publication closure evidence.',
    28,
    'Core',
    ARRAY['S'],
    ARRAY['A'],
    'Requires high-contact stakeholder communication and service recovery, creative judgement, experience sensitivity, and presentation quality for Coordinate research and academic publishing cycles through study evidence, review workflow, and publication records. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-001',
    'API Batch Quality Evidence Review',
    'Reviews and controls quality evidence for Active Pharmaceutical Ingredient batches. This includes batch records, test results, deviations, approvals, and release-supporting documents to ensure the batch can be assessed against GMP and quality requirements.',
    1,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for API Batch Quality Evidence Review. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-002',
    'API Deviation, OOS and CAPA Evidence Control',
    'Manages evidence related to API manufacturing deviations, out-of-specification results, investigations, root causes, corrective actions, and preventive actions. The capability ensures investigation records are complete, traceable, and ready for QA or regulatory review.',
    2,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for API Deviation, OOS and CAPA Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-003',
    'Finished Dose BMR/BPR Packaging Variance and Release Packet Control',
    'Controls batch manufacturing records, batch packaging records, packaging variances, reconciliation evidence, and final release documentation for finished dosage products. It ensures all production and packaging evidence supports safe batch release.',
    3,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Finished Dose BMR/BPR Packaging Variance and Release Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-004',
    'Stability Study Follow-Up and Change-Control Impact Packet Control',
    'Tracks stability study follow-ups, test outcomes, trends, missed pulls, excursions, and related change-control impacts. This capability ensures stability evidence is complete and linked to product quality decisions.',
    4,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Stability Study Follow-Up and Change-Control Impact Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-005',
    'Biological Product Batch and Comparability Evidence Control',
    'Manages batch evidence for biological products and supports comparability assessments after process, site, material, or method changes. It ensures product quality, consistency, and change impact evidence are properly documented.',
    5,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Biological Product Batch and Comparability Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-006',
    'Vaccine Lot QC, Temperature-Excursion and Cold-Chain Release Packet Control',
    'Controls vaccine lot quality records, QC test evidence, cold-chain logs, temperature excursions, investigations, and release-supporting packets. This capability ensures vaccine lots are assessed for quality and storage compliance before release.',
    6,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Vaccine Lot QC, Temperature-Excursion and Cold-Chain Release Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-007',
    'Advanced Biopharma Evidence Inventory and Authority-Boundary Triage',
    'Organizes evidence for advanced biopharma products and identifies which issues need specialist, QA, regulatory, clinical, or authority-level escalation. It helps learners/workers separate routine documentation from high-risk or authority-bound decisions.',
    7,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Advanced Biopharma Evidence Inventory and Authority-Boundary Triage. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-008',
    'Clinical Trial Startup Records and Monitoring Action Evidence Control',
    'Manages clinical trial startup documentation, site readiness records, ethics/regulatory submissions, monitoring findings, action items, and follow-up evidence. This ensures trial startup and site monitoring activities are inspection-ready.',
    8,
    'Core',
    ARRAY['C'],
    ARRAY['S'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, high-contact stakeholder communication and service recovery for Clinical Trial Startup Records and Monitoring Action Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-009',
    'Pharmacovigilance ICSR and Safety Evidence Handling',
    'Handles Individual Case Safety Reports and supporting safety evidence. This includes intake, seriousness checks, case documentation, follow-up tracking, coding support, and timely handoff for pharmacovigilance processing.',
    9,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Pharmacovigilance ICSR and Safety Evidence Handling. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-010',
    'Clinical Dataset Mapping, Query Reconciliation and Data-Lock Packet Control',
    'Controls clinical data evidence during dataset mapping, query tracking, reconciliation, and data-lock preparation. It ensures clinical data issues are resolved, documented, and ready for analysis or regulatory submission.',
    10,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Clinical Dataset Mapping, Query Reconciliation and Data-Lock Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-011',
    'NGS Run QC, Variant Calling and Genomics Reporting',
    'Manages next-generation sequencing run quality checks, variant calling outputs, QC flags, interpretation support evidence, and genomics reporting packets. This capability ensures genomic test results are evidence-based, traceable, and review-ready.',
    11,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for NGS Run QC, Variant Calling and Genomics Reporting. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-012',
    'Bioservices Sample Result, Assay Run and Research Tool Lot Evidence Control',
    'Controls sample testing records, assay run evidence, result documentation, reagent/tool lot records, and research service outputs. This supports reliable bioservices delivery and traceable laboratory evidence.',
    12,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Bioservices Sample Result, Assay Run and Research Tool Lot Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-013',
    'Biofoundry DBTL Cycle Evidence Execution',
    'Executes and records evidence across the Design-Build-Test-Learn cycle in a biofoundry environment. This includes experiment design inputs, build records, test outputs, learning notes, and iteration evidence.',
    13,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Biofoundry DBTL Cycle Evidence Execution. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-014',
    'Industrial Bioprocess Scale-Up and Product Evidence Handoff',
    'Manages evidence during bioprocess scale-up from lab or pilot stage to larger production scale. It includes process parameters, batch observations, yield data, deviations, and handoff documents for manufacturing or tech transfer.',
    14,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Industrial Bioprocess Scale-Up and Product Evidence Handoff. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-015',
    'Agri-Biotech Trait, Field Trial and Stewardship Evidence Packet Control',
    'Controls evidence related to biotech traits, field trials, agronomic observations, trial deviations, stewardship obligations, and performance records. This supports responsible agri-biotech product development and review.',
    15,
    'Core',
    ARRAY['I'],
    ARRAY['R'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, site/operations awareness, safety discipline, and practical execution follow-through for Agri-Biotech Trait, Field Trial and Stewardship Evidence Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-016',
    'Agri-Biotech License-to-Operate Evidence Coordination',
    'Coordinates documents and evidence needed for agri-biotech regulatory, environmental, stewardship, biosafety, and market authorization requirements. This capability supports compliance and continued permission to operate.',
    16,
    'Core',
    ARRAY['I'],
    ARRAY['R'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, site/operations awareness, safety discipline, and practical execution follow-through for Agri-Biotech License-to-Operate Evidence Coordination. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-017',
    'Medical Device Technical File, QMS and Post-Market Evidence Control',
    'Manages medical device technical files, quality management system records, risk documentation, complaints, vigilance, and post-market surveillance evidence. It ensures device documentation remains audit- and compliance-ready.',
    17,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Medical Device Technical File, QMS and Post-Market Evidence Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-018A',
    'Device QC Test Report and Biomedical Equipment Nonconformance Packet Control',
    'Controls quality test reports, equipment inspection records, failed test evidence, nonconformance reports, investigation notes, and disposition packets for medical devices or biomedical equipment.',
    18,
    'Core',
    ARRAY['R'],
    ARRAY['I'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, evidence analysis, exception diagnosis, and quality/risk interpretation for Device QC Test Report and Biomedical Equipment Nonconformance Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-018B',
    'IVD Performance, Diagnostic Evidence and PMS Packet Control',
    'Manages in-vitro diagnostic performance evidence, analytical/clinical validation support, diagnostic result evidence, complaints, and post-market surveillance records. This ensures IVD products are supported by traceable performance and safety evidence.',
    19,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for IVD Performance, Diagnostic Evidence and PMS Packet Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-018C',
    'SaMD Lifecycle, V&V and Cybersecurity Evidence Index Control',
    'Controls evidence for Software as a Medical Device across lifecycle documentation, verification and validation, risk controls, cybersecurity evidence, change records, and release-supporting indexes.',
    20,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for SaMD Lifecycle, V&V and Cybersecurity Evidence Index Control. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-01',
    'Residential Buyer Documentation and Project Disclosure Evidence Support',
    'Prepare a supervisor-ready residential buyer documentation and project disclosure evidence pack for RERA-backed project sales support.',
    1,
    'Core',
    ARRAY['E'],
    ARRAY['S'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, high-contact stakeholder communication and service recovery for Residential Buyer Documentation and Project Disclosure Evidence Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-02',
    'RERA Project Disclosure Evidence Gap Support',
    'Compile, cross-reference and gap-log RERA project disclosure evidence for compliance-support review without legal interpretation.',
    2,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for RERA Project Disclosure Evidence Gap Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-03',
    'Office Occupier Requirement and Site-Option Evidence Support',
    'Convert office occupier requirements into site-option comparison evidence packs for leasing lead review.',
    3,
    'Core',
    ARRAY['E'],
    ARRAY['C'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, structured evidence capture, documentation accuracy, and controlled handoffs for Office Occupier Requirement and Site-Option Evidence Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-04',
    'Office Occupier Service Handoff Coordination',
    'Route and evidence office occupier service handoffs across leasing, property and asset-support owners while preserving ownership accountability.',
    4,
    'Core',
    ARRAY['E'],
    ARRAY['C'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, structured evidence capture, documentation accuracy, and controlled handoffs for Office Occupier Service Handoff Coordination. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-05',
    'Tenant and Owner Property Service Case Coordination',
    'Classify, route, evidence and close tenant/owner property service cases while keeping property-management ownership separate from FM work-order closure.',
    5,
    'Core',
    ARRAY['E'],
    ARRAY['C'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, structured evidence capture, documentation accuracy, and controlled handoffs for Tenant and Owner Property Service Case Coordination. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-06',
    'Property Occupancy, Service-Charge and Asset-Record Evidence Support',
    'Collect, reconcile and prepare property occupancy, service-charge and rent-roll evidence updates for supervised property operations review.',
    6,
    'Core',
    ARRAY['E'],
    ARRAY['C'],
    'Requires commercial prioritization, vendor/client follow-up, and outcome ownership, structured evidence capture, documentation accuracy, and controlled handoffs for Property Occupancy, Service-Charge and Asset-Record Evidence Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-07',
    'FM Hard-Services Work Order and Maintenance Evidence Coordination',
    'Coordinate FM hard-services work orders from equipment/location classification through vendor or engineering action, exception escalation and supervised closure evidence.',
    7,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for FM Hard-Services Work Order and Maintenance Evidence Coordination. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-08',
    'FM Soft-Services and Workplace Experience Coordination',
    'Coordinate FM soft-services and workplace-experience issues using vendor roster context, service evidence and repeat-failure escalation.',
    8,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for FM Soft-Services and Workplace Experience Coordination. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-09',
    'Facility Inspection, Safety, SLA and Vendor-Performance Evidence Support',
    'Prepare facility inspection, safety exception, SLA and vendor-performance evidence for FM review and escalation.',
    9,
    'Core',
    ARRAY['R'],
    ARRAY['C'],
    'Requires site/operations awareness, safety discipline, and practical execution follow-through, structured evidence capture, documentation accuracy, and controlled handoffs for Facility Inspection, Safety, SLA and Vendor-Performance Evidence Support. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'CAP-REF-10',
    'Valuation and Asset Evidence Pack Preparation',
    'Assemble, reconcile and gap-note rent-roll, property and asset evidence packs for valuation/advisory review without final judgement.',
    10,
    'Core',
    ARRAY['I'],
    ARRAY['C'],
    'Requires evidence analysis, exception diagnosis, and quality/risk interpretation, structured evidence capture, documentation accuracy, and controlled handoffs for Valuation and Asset Evidence Pack Preparation. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  ),
  (
    'IND-CAP-29',
    'Review supplier ESG and packaging compliance evidence through documentation, risk tracking, corrective request, and decision proof',
    'Reviews supplier ESG and packaging compliance by checking documentation, mapping regulatory or policy requirements, identifying evidence gaps, requesting corrective proof, and recording risk or approval decisions.',
    29,
    'Core',
    ARRAY['C'],
    ARRAY['I'],
    'Requires structured evidence capture, documentation accuracy, and controlled handoffs, evidence analysis, exception diagnosis, and quality/risk interpretation for Review supplier ESG and packaging compliance evidence through documentation, risk tracking, corrective request, and decision proof. Work must be evidence-backed, supervisor-reviewable, and bounded by role authority.',
    now(),
    now()
  );

