-- ============================================================================
-- Seed Data: Skill-Capability Mapping (M:N Relationship)
-- Source: Master sheet_csv.csv
-- Date: 2026-06-24
-- Table: public.skill_capability_mapping
-- Total: 1190 unique mappings
-- ============================================================================

INSERT INTO public.skill_capability_mapping (skill_id, capability_id)
SELECT 
  s.id as skill_id,
  c.id as capability_id
FROM public.skills s,
  public.capability_master c,
  (VALUES
    ('Academic Activation Input Check', 'IND-CAP-03'),
    ('Academic Activation Standards and Evidence Audit', 'IND-CAP-03'),
    ('Academic Activation Standards and Staff Coaching', 'IND-CAP-03'),
    ('Academic Activation Work Loop Routine Execution', 'IND-CAP-03'),
    ('Academic Record Closure Documentation', 'IND-CAP-03'),
    ('Account and KYC Update Handling', 'CAP-BANK-002'),
    ('Activated Learner Academic Review Evidence Preparation', 'IND-CAP-03'),
    ('Ad Tag Url Duration Validation', 'IND-CAP-19'),
    ('Ad-server Delivery Contractual Obligation', 'IND-CAP-20'),
    ('Adjudicate Labeled Data Disagreements Quality', 'IND-CAP-20'),
    ('Adjudicate Labeled Data Disagreements With', 'IND-CAP-20'),
    ('Administer Joiner-mover-leaver Checklists', 'IND-CAP-14'),
    ('Admissions Document and Activation Evidence Audit', 'IND-CAP-25'),
    ('Admissions Document and Activation Routine Execution', 'IND-CAP-25'),
    ('Admissions Document and Activation Staff Coaching', 'IND-CAP-25'),
    ('Admissions File Closure Documentation', 'IND-CAP-25'),
    ('Admissions Record Input Check', 'IND-CAP-25'),
    ('Adult Learner Pathway Design Evidence Audit', 'IND-CAP-04'),
    ('Adult Learner Pathway Design Routine Execution', 'IND-CAP-04'),
    ('Adult Learner Pathway Design Staff Coaching', 'IND-CAP-04'),
    ('Advanced Biopharma Inventory and Evidence Inventory', 'CAP-007'),
    ('Advanced Biopharma Inventory and Exception Handoff', 'CAP-007'),
    ('Agri-biotech License-to-operate Coordination', 'CAP-016'),
    ('Agri-biotech License-to-operate Coordination Exception', 'CAP-016'),
    ('Agri-biotech Trait Field Trial Controlled Intake', 'CAP-015'),
    ('Agri-biotech Trait Field Trial Exception Readiness', 'CAP-015'),
    ('Agroforestry and Plantation Activity', 'CAP-AFF-009'),
    ('AI Explanation Control Check', 'IND-CAP-17'),
    ('AI Output Mapping', 'IND-CAP-18'),
    ('AI Use Case Registration', 'IND-CAP-14'),
    ('Air Passenger Ground Handling Capture', 'IND-CAP-11'),
    ('Air Passenger Ground Handling Confirmation', 'IND-CAP-11'),
    ('Air Passenger Ground Handling Reconciliation', 'IND-CAP-11'),
    ('Align Product Model Governance and', 'IND-CAP-16'),
    ('Align Product Model Governance Evidence Coaching', 'IND-CAP-16'),
    ('Align Product Model Governance Quality Improvement', 'IND-CAP-16'),
    ('Aligned Vocational Batch File Evidence Preparation', 'IND-CAP-09'),
    ('Alternative Stay Property Operations Capture', 'IND-CAP-05'),
    ('Alternative Stay Property Operations Confirmation', 'IND-CAP-05'),
    ('Alternative Stay Property Operations Reconciliation', 'IND-CAP-05'),
    ('AML Alert Chronology', 'CAP-X-002'),
    ('Annotate Timeline Gaps Missing Pickups', 'IND-CAP-03'),
    ('API Batch Quality Review Artifact Completeness', 'CAP-001'),
    ('API Batch Quality Review Exception Readiness', 'CAP-001'),
    ('API Batch Quality Review Handoff Packet', 'CAP-001'),
    ('API Deviation OOS and Artifact Completeness', 'CAP-002'),
    ('API Deviation OOS and Exception Readiness', 'CAP-002'),
    ('API Deviation OOS and Handoff Packet', 'CAP-002'),
    ('Approve Promo Packet With Hook', 'IND-CAP-01'),
    ('Aquaculture Stocking and Feed-cycle Log', 'CAP-AFF-007'),
    ('Archive Pitch Copy Submission Timestamp', 'IND-CAP-23'),
    ('Assess Privacy Consent and Evidence Coaching', 'IND-CAP-14'),
    ('Assess Privacy Consent and Quality Improvement', 'IND-CAP-14'),
    ('Assess Privacy Consent and Sensitive-attribute', 'IND-CAP-14'),
    ('Assess Responsible AI Deployment Quality Improvement', 'IND-CAP-14'),
    ('Assess Responsible AI Deployment Risk', 'IND-CAP-14'),
    ('Assessment Blueprint and Item Evidence Audit', 'IND-CAP-17'),
    ('Assessment Blueprint and Item Routine Execution', 'IND-CAP-17'),
    ('Assessment Blueprint and Item Staff Coaching', 'IND-CAP-17'),
    ('Assessment Blueprint Input Check', 'IND-CAP-17'),
    ('Assessment Blueprint Review Evidence Preparation', 'IND-CAP-17'),
    ('Asset-specific Pack Review', 'CIE-CAP-001'),
    ('Asset-specific Pack Review', 'CIE-CAP-002'),
    ('Asset-specific Pack Review', 'CIE-CAP-006'),
    ('Asset-specific Pack Review', 'CIE-CAP-008'),
    ('Assign Severity Frequency Affected Feature', 'IND-CAP-15'),
    ('Assignment Change Control L1 Evidence Review', 'IND-CAP-06'),
    ('Assignment Change Control L1 Execution', 'IND-CAP-06'),
    ('Assignment Change Control L2 Evidence Review', 'IND-CAP-06'),
    ('Assignment Change Control L2 Execution', 'IND-CAP-06'),
    ('Assignment Change Control L3 Evidence Review', 'IND-CAP-06'),
    ('Assignment Change Control L3 Execution', 'IND-CAP-06'),
    ('Assignment Change Control L4 Evidence Review', 'IND-CAP-06'),
    ('Assignment Change Control L4 Execution', 'IND-CAP-06'),
    ('Assignment Change Control L5 Evidence Review', 'IND-CAP-06'),
    ('Assignment Change Control L5 Execution', 'IND-CAP-06'),
    ('Assortment Shelf Space Planogram Validation', 'IND-CAP-12'),
    ('ATS-HRIS Sync Recovery L1 Evidence Review', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L1 Execution', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L2 Evidence Review', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L2 Execution', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L3 Evidence Review', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L3 Execution', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L4 Evidence Review', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L4 Execution', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L5 Evidence Review', 'IND-CAP-16'),
    ('ATS-HRIS Sync Recovery L5 Execution', 'IND-CAP-16'),
    ('Attach Classification Sensitivity and Evidence Coaching', 'IND-CAP-13'),
    ('Attach Classification Sensitivity and Quality', 'IND-CAP-13'),
    ('Attach Classification Sensitivity and Retention', 'IND-CAP-13'),
    ('Attach Reference Edit LUT Note', 'IND-CAP-05'),
    ('Attendee Registration Fields Ticket Capture', 'IND-CAP-22'),
    ('Authority ROW and Operating-interface Tracking', 'CIE-CAP-008'),
    ('Authority ROW and Operating-interface Tracking', 'CIE-CAP-001'),
    ('Baggage Overweight Id Mismatch Resolution', 'IND-CAP-11'),
    ('Bamboo Stand and Lot', 'CAP-AFF-009'),
    ('Banking Complaint Registration and Capture', 'CAP-BANK-004'),
    ('Banking Service Review', 'CAP-BANK-001'),
    ('Banking Ticket Routing', 'CAP-BANK-001'),
    ('Banquet Venue Operations Eligibility Confirmation', 'IND-CAP-09'),
    ('Banquet Venue Operations Reconciliation', 'IND-CAP-09'),
    ('Banquet Venue Operations Work Capture', 'IND-CAP-09'),
    ('BI Query Pattern Packaging', 'IND-CAP-02'),
    ('BIM/VDC Coordination and Digital Handover', 'CIE-CAP-005'),
    ('BIM/VDC Coordination and Digital Handover', 'CIE-CAP-008'),
    ('Biofoundry DBTL Cycle Execution Controlled Intake', 'CAP-013'),
    ('Biofoundry DBTL Cycle Execution Exception Readiness', 'CAP-013'),
    ('Biological Product Batch and Artifact Completeness', 'CAP-005'),
    ('Biological Product Batch and Cross-artifact', 'CAP-005'),
    ('Biological Product Batch and Exception Readiness', 'CAP-005'),
    ('Biological Product Batch and Handoff Packet', 'CAP-005'),
    ('Biosecurity Breach Observation and Escalation', 'CAP-AFF-006'),
    ('Bioservices Sample Result Assay Controlled Intake', 'CAP-012'),
    ('Bioservices Sample Result Assay Exception Readiness', 'CAP-012'),
    ('Boarding Count Mismatch Resolution', 'IND-CAP-14'),
    ('Boarding Gate Status Update', 'IND-CAP-11'),
    ('Book Campaign Commitment Into Revenue', 'IND-CAP-20'),
    ('BOPIS Allocation Store Pick Validation', 'IND-CAP-03'),
    ('BOPIS Order Preparation Exceptions Resolution', 'IND-CAP-03'),
    ('BOPIS Order Preparation Quality Evidence Audit', 'IND-CAP-03'),
    ('BOPIS Order Preparation Triggers Interpretation', 'IND-CAP-03'),
    ('Borderline Scene Timestamping', 'IND-CAP-18'),
    ('Borrower Document Pre-screen', 'CAP-CREDIT-001'),
    ('Boundary-safe Relationship Interaction', 'CAP-BANK-003'),
    ('Breaking Event Route Handoff', 'IND-CAP-03'),
    ('Broken Texture Paths Rig Resolution', 'IND-CAP-08'),
    ('Bronze Source Profiling', 'IND-CAP-01'),
    ('Build Buyer Order Form With', 'IND-CAP-21'),
    ('Build Delivery Manifest Listing Asset', 'IND-CAP-09'),
    ('Build Workforce Gap Registers L1 Evidence', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L1 Execution', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L2 Evidence', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L2 Execution', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L3 Evidence', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L3 Execution', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L4 Evidence', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L4 Execution', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L5 Evidence', 'IND-CAP-19'),
    ('Build Workforce Gap Registers L5 Execution', 'IND-CAP-19'),
    ('Buyer Return Request Return Validation', 'IND-CAP-07'),
    ('Candidate Screening L1 Evidence Review', 'IND-CAP-02'),
    ('Candidate Screening L1 Execution', 'IND-CAP-02'),
    ('Candidate Screening L2 Evidence Review', 'IND-CAP-02'),
    ('Candidate Screening L2 Execution', 'IND-CAP-02'),
    ('Candidate Screening L3 Evidence Review', 'IND-CAP-02'),
    ('Candidate Screening L3 Execution', 'IND-CAP-02'),
    ('Candidate Screening L4 Evidence Review', 'IND-CAP-02'),
    ('Candidate Screening L4 Execution', 'IND-CAP-02'),
    ('Candidate Screening L5 Evidence Review', 'IND-CAP-02'),
    ('Candidate Screening L5 Execution', 'IND-CAP-02'),
    ('Captions Packaging', 'IND-CAP-10'),
    ('Career Guidance Action Plan Evidence Preparation', 'IND-CAP-23'),
    ('Career Guidance Action Planning Evidence Audit', 'IND-CAP-23'),
    ('Career Guidance Action Planning Routine Execution', 'IND-CAP-23'),
    ('Career Guidance Action Planning Staff Coaching', 'IND-CAP-23'),
    ('Career Guidance Closure Documentation', 'IND-CAP-23'),
    ('Career Guidance Input Check', 'IND-CAP-23'),
    ('Case Escalation Reason Recovery Validation', 'IND-CAP-22'),
    ('Catch Landing Segregation and Auction', 'CAP-AFF-008'),
    ('Category Performance and Assortment Evidence Audit', 'IND-CAP-09'),
    ('Category Performance and Assortment Interpretation', 'IND-CAP-09'),
    ('Category Performance and Assortment Resolution', 'IND-CAP-09'),
    ('Category Performance Dashboard Tool Use', 'IND-CAP-09'),
    ('Chargeback and Dispute Response Evidence Audit', 'IND-CAP-28'),
    ('Chargeback and Dispute Response Interpretation', 'IND-CAP-28'),
    ('Chargeback and Dispute Response Resolution', 'IND-CAP-28'),
    ('Chargeback Dispute Case File Tool Use', 'IND-CAP-28'),
    ('Check Audio Availability Date Rights', 'IND-CAP-23'),
    ('Check Audio File Naming Duration', 'IND-CAP-04'),
    ('Check Character Limits Reading Speed', 'IND-CAP-10'),
    ('Check Frame Range Resolution Color', 'IND-CAP-05'),
    ('Check Generated Outputs for Evidence Coaching', 'IND-CAP-15'),
    ('Check Generated Outputs for Quality Improvement', 'IND-CAP-15'),
    ('Check Generated Outputs for Sensitive', 'IND-CAP-15'),
    ('Check Install First Launch Login', 'IND-CAP-13'),
    ('Check Privacy Declarations Data Collection', 'IND-CAP-14'),
    ('Check Title Thumbnail Description and', 'IND-CAP-18'),
    ('Ci Test Run Monitoring', 'IND-CAP-16'),
    ('Classify Response Path As Removal', 'IND-CAP-17'),
    ('Clearing Obligation and Movement Review', 'CAP-CM-004'),
    ('Clinical Dataset Mapping Query Controlled Intake', 'CAP-010'),
    ('Clinical Dataset Mapping Query Exception Readiness', 'CAP-010'),
    ('Clinical Trial Startup and Artifact Completeness', 'CAP-008'),
    ('Clinical Trial Startup and Cross-artifact', 'CAP-008'),
    ('Clinical Trial Startup and Exception Readiness', 'CAP-008'),
    ('Clinical Trial Startup and Handoff Packet', 'CAP-008'),
    ('Close Case With History Final', 'IND-CAP-17'),
    ('Close Cut-change Cycle After Production', 'IND-CAP-06'),
    ('Close Employee Master-data Changes L1 Evidence', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L1 Execution', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L2 Evidence', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L2 Execution', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L3 Evidence', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L3 Execution', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L4 Evidence', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L4 Execution', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L5 Evidence', 'IND-CAP-13'),
    ('Close Employee Master-data Changes L5 Execution', 'IND-CAP-13'),
    ('Close Sales Operations Cycle After', 'IND-CAP-20'),
    ('Cluster Initiatives Into Near-term Pilots', 'IND-CAP-19'),
    ('Cluster Initiatives Near-term Pilots Evidence Coaching', 'IND-CAP-19'),
    ('Cluster Initiatives Near-term Pilots Quality', 'IND-CAP-19'),
    ('Coaching Progress Input Check', 'IND-CAP-24'),
    ('Coaching Progress Tracker Review Evidence Preparation', 'IND-CAP-24'),
    ('Coaching Tracker Closure Documentation', 'IND-CAP-24'),
    ('Cohort Scheduling Input Check', 'IND-CAP-01'),
    ('Cohort Session Scheduling Standards Evidence Audit', 'IND-CAP-01'),
    ('Cohort Session Scheduling Standards Staff Coaching', 'IND-CAP-01'),
    ('Cohort Session Scheduling Work Routine Execution', 'IND-CAP-01'),
    ('Cold Item Wrong Recipe Resolution', 'IND-CAP-08'),
    ('Cold-chain Log and Controlled', 'CAP-AFF-014'),
    ('Collect Final Video Audio Captions', 'IND-CAP-09'),
    ('Color Level Mismatch Check', 'IND-CAP-07'),
    ('Commissioning and Handover Dossier Assembly', 'CIE-CAP-006'),
    ('Compare Claimant Against Channel License', 'IND-CAP-17'),
    ('Compare In-app Purchase Ad Disclosure', 'IND-CAP-14'),
    ('Compare Partner Delivery Spec Against', 'IND-CAP-09'),
    ('Compile Episode Title Description Guest', 'IND-CAP-04'),
    ('Complaint Escalation and -pack Review', 'CAP-BANK-004'),
    ('Complaint Fact Dispute Resolution', 'IND-CAP-03'),
    ('Complete Background Screening Decisions L1 Evidence', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L1 Execution', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L2 Evidence', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L2 Execution', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L3 Evidence', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L3 Execution', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L4 Evidence', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L4 Execution', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L5 Evidence', 'IND-CAP-27'),
    ('Complete Background Screening Decisions L5 Execution', 'IND-CAP-27'),
    ('Conduct-safe Delinquency Escalation', 'CAP-CREDIT-003'),
    ('Confirm AI Solution Owner Evidence Coaching', 'IND-CAP-16'),
    ('Construct Leakage-safe Model Feature Dataset', 'IND-CAP-06'),
    ('Construct Leakage-safe Model Feature Evidence Coaching', 'IND-CAP-06'),
    ('Construct Leakage-safe Model Feature Quality', 'IND-CAP-06'),
    ('Content Sources Retrieval Constraints Input', 'IND-CAP-16'),
    ('Contract Variation Evidence', 'CIE-CAP-004'),
    ('Convert Engagement Survey Insights L1 Evidence', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L1 Execution', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L2 Evidence', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L2 Execution', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L3 Evidence', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L3 Execution', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L4 Evidence', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L4 Execution', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L5 Evidence', 'IND-CAP-24'),
    ('Convert Engagement Survey Insights L5 Execution', 'IND-CAP-24'),
    ('Convert Iot Equipment Anomaly Evidence Coaching', 'IND-CAP-12'),
    ('Convert Iot Equipment Anomaly Into', 'IND-CAP-12'),
    ('Convert Iot Equipment Anomaly Quality Improvement', 'IND-CAP-12'),
    ('Convert Training Needs Prioritized L1 Evidence', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L1 Execution', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L2 Evidence', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L2 Execution', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L3 Evidence', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L3 Execution', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L4 Evidence', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L4 Execution', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L5 Evidence', 'IND-CAP-21'),
    ('Convert Training Needs Prioritized L5 Execution', 'IND-CAP-21'),
    ('Coordinate BOPIS Order Preparation Handoffs', 'IND-CAP-03'),
    ('Coordinate Category Performance and Assortment', 'IND-CAP-09'),
    ('Coordinate Chargeback and Dispute Response', 'IND-CAP-28'),
    ('Coordinate Customer Issue Intake and', 'IND-CAP-21'),
    ('Coordinate Customer Pickup and Handoffs', 'IND-CAP-04'),
    ('Coordinate Distributor Stock and Credit', 'IND-CAP-16'),
    ('Coordinate Escalation and Case Handoffs', 'IND-CAP-22'),
    ('Coordinate GTIN and Barcode Governance', 'IND-CAP-17'),
    ('Coordinate Inventory Cycle Count and', 'IND-CAP-19'),
    ('Coordinate Loyalty Reward Correction Handoffs', 'IND-CAP-24'),
    ('Coordinate Marketplace Catalog and Product', 'IND-CAP-08'),
    ('Coordinate Marketplace Inventory Availability', 'IND-CAP-06'),
    ('Coordinate Online Fulfillment Release Handoffs', 'IND-CAP-05'),
    ('Coordinate Outlet Distribution Expansion Handoffs', 'IND-CAP-13'),
    ('Coordinate Planogram and Shelf Compliance', 'IND-CAP-12'),
    ('Coordinate Price and Promotion Rule', 'IND-CAP-11'),
    ('Coordinate Product Data Traceability Handoffs', 'IND-CAP-18'),
    ('Coordinate Product Recall Risk Evaluation', 'IND-CAP-25'),
    ('Coordinate Recall Corrective Handoffs Stakeholder', 'IND-CAP-26'),
    ('Coordinate Replenishment Exception Handoffs Stakeholder', 'IND-CAP-20'),
    ('Coordinate Return and Exchange Processing', 'IND-CAP-23'),
    ('Coordinate Secondary Sales Follow-up Handoffs', 'IND-CAP-14'),
    ('Coordinate Seller-fulfilled Return Authorization', 'IND-CAP-07'),
    ('Coordinate Shrink Investigation and Loss', 'IND-CAP-27'),
    ('Coordinate Supplier ESG and Packaging', 'IND-CAP-29'),
    ('Coordinate Trade Promotion Execution Handoffs', 'IND-CAP-15'),
    ('Coordinate Vendor Commercial and Promotion', 'IND-CAP-10'),
    ('Corporate Learning Needs and Evidence Audit', 'IND-CAP-12'),
    ('Corporate Learning Needs and Routine Execution', 'IND-CAP-12'),
    ('Corporate Learning Needs and Staff Coaching', 'IND-CAP-12'),
    ('Corporate Setup', 'CAP-CM-006'),
    ('Correct Hidden Fee Wrong Seat/tier', 'IND-CAP-21'),
    ('Corrective Action Recall Communication Validation', 'IND-CAP-26'),
    ('Create Event Listing With Venue', 'IND-CAP-21'),
    ('Create Live Channel Event With', 'IND-CAP-11'),
    ('Creator Video Policy Screening', 'IND-CAP-02'),
    ('Credential Issuance Closure Documentation', 'IND-CAP-19'),
    ('Credential Issuance Verification Standards Evidence', 'IND-CAP-19'),
    ('Credential Issuance Verification Standards Staff', 'IND-CAP-19'),
    ('Credential Issuance Verification Work Routine Execution', 'IND-CAP-19'),
    ('Credential Verification Input Check', 'IND-CAP-19'),
    ('Credit Reviewer Packet Preparation', 'CAP-CREDIT-001'),
    ('Crm Profile Tool Use', 'IND-CAP-24'),
    ('Crop Scouting and Pest Exception', 'CAP-AFF-002'),
    ('Curriculum Alignment Mapping Standards Evidence Audit', 'IND-CAP-05'),
    ('Curriculum Alignment Mapping Standards Staff Coaching', 'IND-CAP-05'),
    ('Curriculum Alignment Mapping Work Routine Execution', 'IND-CAP-05'),
    ('Curriculum Map Review Evidence Preparation', 'IND-CAP-05'),
    ('Curriculum Mapping Input Check', 'IND-CAP-05'),
    ('Customer Issue Intake and Evidence Audit', 'IND-CAP-21'),
    ('Customer Issue Intake and Interpretation', 'IND-CAP-21'),
    ('Customer Issue Intake and Resolution', 'IND-CAP-21'),
    ('Customer Pickup and Closure Interpretation', 'IND-CAP-04'),
    ('Customer Pickup and Closure Resolution', 'IND-CAP-04'),
    ('Customer Pickup Handoff and Evidence Audit', 'IND-CAP-04'),
    ('Customer Ticket Issue Type Validation', 'IND-CAP-21'),
    ('Cut Change Identification', 'IND-CAP-06'),
    ('Cycle Count Batch Physical Validation', 'IND-CAP-19'),
    ('Dairy Output and Feed-use', 'CAP-AFF-005'),
    ('Data Contract Exceptions', 'IND-CAP-01'),
    ('Data Quality Controls', 'IND-CAP-01'),
    ('Define Human-AI Interaction Sequence Including', 'IND-CAP-16'),
    ('Define Human-AI Interaction Sequence Quality', 'IND-CAP-16'),
    ('Delivery Dashboard Closure Documentation', 'IND-CAP-10'),
    ('Delivery Monitoring Dashboard Review Evidence', 'IND-CAP-10'),
    ('Demand Signal Stock Level Validation', 'IND-CAP-20'),
    ('Deployment Handoff Package Configuration Evidence', 'IND-CAP-18'),
    ('Depository Instruction Handling', 'CAP-CM-005'),
    ('Design Enterprise AI Adoption Quality Improvement', 'IND-CAP-19'),
    ('Design Enterprise AI Adoption Roadmap', 'IND-CAP-19'),
    ('Device QC Test Report Artifact Completeness', 'CAP-018A'),
    ('Device QC Test Report Exception Readiness', 'CAP-018A'),
    ('Device QC Test Report Handoff Packet', 'CAP-018A'),
    ('Diagnose Access Failure', 'IND-CAP-15'),
    ('Diagnose Attendance Shortfall', 'IND-CAP-02'),
    ('Diagnose Beneficiary Duplication', 'IND-CAP-27'),
    ('Diagnose Broken Media Link', 'IND-CAP-06'),
    ('Diagnose Candidate Mismatch', 'IND-CAP-20'),
    ('Diagnose Document Mismatch', 'IND-CAP-25'),
    ('Diagnose Duplicate Learner', 'IND-CAP-26'),
    ('Diagnose Eligibility Mismatch', 'IND-CAP-11'),
    ('Diagnose Facilitator Clash', 'IND-CAP-01'),
    ('Diagnose Inactive Learner', 'IND-CAP-14'),
    ('Diagnose Incorrect Gap Diagnosis', 'IND-CAP-22'),
    ('Diagnose Misdiagnosed Classroom Gap', 'IND-CAP-07'),
    ('Diagnose Misdiagnosed Language Level', 'IND-CAP-24'),
    ('Diagnose Misrouted Learner Need', 'IND-CAP-16'),
    ('Diagnose Missing Completion Proof', 'IND-CAP-19'),
    ('Diagnose Missing Eligibility Proof', 'IND-CAP-03'),
    ('Diagnose Missing Ethics', 'IND-CAP-28'),
    ('Diagnose Outdated Market', 'IND-CAP-23'),
    ('Diagnose Practice Shortfall', 'IND-CAP-10'),
    ('Diagnose QP Mismatch', 'IND-CAP-09'),
    ('Diagnose Recall-heavy Item Mix', 'IND-CAP-17'),
    ('Diagnose Rubric Ambiguity', 'IND-CAP-18'),
    ('Diagnose Standard-outcome Mismatch', 'IND-CAP-05'),
    ('Diagnose Unrecognized Accessibility Need', 'IND-CAP-21'),
    ('Diagnose Unsafe Material Use', 'IND-CAP-08'),
    ('Diagnose Unverified Prior Learning', 'IND-CAP-04'),
    ('Diagnose Wrong Cohort Enrolled', 'IND-CAP-13'),
    ('Digital Learner Engagement Nudging Evidence Audit', 'IND-CAP-14'),
    ('Digital Learner Engagement Nudging Routine Execution', 'IND-CAP-14'),
    ('Digital Learner Engagement Nudging Staff Coaching', 'IND-CAP-14'),
    ('Dispute Chargeback and Fraud-signal', 'CAP-PAY-005'),
    ('Dispute Reason Code Due Validation', 'IND-CAP-28'),
    ('Distribution Readiness Coaching', 'IND-CAP-09'),
    ('Distributor Inventory Order Proposal Validation', 'IND-CAP-16'),
    ('Distributor Ledger and Credit Tool Use', 'IND-CAP-16'),
    ('Distributor Stock and Credit Evidence Audit', 'IND-CAP-16'),
    ('Distributor Stock and Credit Interpretation', 'IND-CAP-16'),
    ('Distributor Stock and Credit Resolution', 'IND-CAP-16'),
    ('Document Aligned Vocational Batch File', 'IND-CAP-09'),
    ('Document Assessment Blueprint for Standard', 'IND-CAP-17'),
    ('Document Curriculum Map for Standard', 'IND-CAP-05'),
    ('Document Domain Exceptions Where Evidence Coaching', 'IND-CAP-18'),
    ('Document Individual Learning Pathway Plan', 'IND-CAP-04'),
    ('Document Learner Engagement Monitoring Log', 'IND-CAP-14'),
    ('Document Learner Plan for Standard', 'IND-CAP-21'),
    ('Document Matched Internship/apprenticeship Placement', 'IND-CAP-11'),
    ('Document Misuse Bias and Evidence Coaching', 'IND-CAP-14'),
    ('Document Misuse Bias and Quality Improvement', 'IND-CAP-14'),
    ('Document Misuse Bias and Transparency', 'IND-CAP-14'),
    ('Document Progression Review File and', 'IND-CAP-02'),
    ('Document QA With Screenshots Tag', 'IND-CAP-19'),
    ('Document Research/publishing Tracker for Standard', 'IND-CAP-28'),
    ('Document Resourced Project Cycle Plan', 'IND-CAP-08'),
    ('Document Session Timetable and Confirmation', 'IND-CAP-01'),
    ('Document TNA and Transfer- Tracker', 'IND-CAP-12'),
    ('Document Tutoring Case for Standard', 'IND-CAP-16'),
    ('Document Validated Education MIS Report', 'IND-CAP-26'),
    ('DP Service Request Processing', 'CAP-CM-005'),
    ('DPR and Design-basis Checking', 'CIE-CAP-007'),
    ('Draft Playlist Pitch With Story', 'IND-CAP-23'),
    ('Driver No-show Route Deviation Resolution', 'IND-CAP-13'),
    ('E-Learning Package Closure Documentation', 'IND-CAP-06'),
    ('E-Learning Release Input Check', 'IND-CAP-06'),
    ('E-learning Release QA Evidence Audit', 'IND-CAP-06'),
    ('E-learning Release QA Quality Pattern Review', 'IND-CAP-06'),
    ('E-learning Release QA Routine Execution', 'IND-CAP-06'),
    ('E-learning Release QA Staff Coaching', 'IND-CAP-06'),
    ('Education MIS Input Check', 'IND-CAP-26'),
    ('Education MIS Reporting Standards Evidence Audit', 'IND-CAP-26'),
    ('Education MIS Reporting Standards Staff Coaching', 'IND-CAP-26'),
    ('Education MIS Reporting Work Routine Execution', 'IND-CAP-26'),
    ('EOR Payroll Changes L1 Evidence Review', 'IND-CAP-08'),
    ('EOR Payroll Changes L1 Execution', 'IND-CAP-08'),
    ('EOR Payroll Changes L2 Evidence Review', 'IND-CAP-08'),
    ('EOR Payroll Changes L2 Execution', 'IND-CAP-08'),
    ('EOR Payroll Changes L3 Evidence Review', 'IND-CAP-08'),
    ('EOR Payroll Changes L3 Execution', 'IND-CAP-08'),
    ('EOR Payroll Changes L4 Evidence Review', 'IND-CAP-08'),
    ('EOR Payroll Changes L4 Execution', 'IND-CAP-08'),
    ('EOR Payroll Changes L5 Evidence Review', 'IND-CAP-08'),
    ('EOR Payroll Changes L5 Execution', 'IND-CAP-08'),
    ('EOR Worker Setup L1 Evidence Review', 'IND-CAP-07'),
    ('EOR Worker Setup L1 Execution', 'IND-CAP-07'),
    ('EOR Worker Setup L2 Evidence Review', 'IND-CAP-07'),
    ('EOR Worker Setup L2 Execution', 'IND-CAP-07'),
    ('EOR Worker Setup L3 Evidence Review', 'IND-CAP-07'),
    ('EOR Worker Setup L3 Execution', 'IND-CAP-07'),
    ('EOR Worker Setup L4 Evidence Review', 'IND-CAP-07'),
    ('EOR Worker Setup L4 Execution', 'IND-CAP-07'),
    ('EOR Worker Setup L5 Evidence Review', 'IND-CAP-07'),
    ('EOR Worker Setup L5 Execution', 'IND-CAP-07'),
    ('Escalate Academic Activation Exceptions With', 'IND-CAP-03'),
    ('Escalate Admissions Document and Activation', 'IND-CAP-25'),
    ('Escalate Adult Learner Pathway Design', 'IND-CAP-04'),
    ('Escalate Assessment Blueprint and Item', 'IND-CAP-17'),
    ('Escalate Career Guidance Planning Exceptions', 'IND-CAP-23'),
    ('Escalate Cohort Session Scheduling Exceptions', 'IND-CAP-01'),
    ('Escalate Corporate Learning Needs and', 'IND-CAP-12'),
    ('Escalate Credential Issuance Verification Exceptions', 'IND-CAP-19'),
    ('Escalate Curriculum Alignment Mapping Exceptions', 'IND-CAP-05'),
    ('Escalate Digital Learner Engagement Nudging', 'IND-CAP-14'),
    ('Escalate E-learning Content Release Exceptions', 'IND-CAP-06'),
    ('Escalate Education MIS Reporting Exceptions', 'IND-CAP-26'),
    ('Escalate Exam Operations Exceptions With', 'IND-CAP-20'),
    ('Escalate Internship and Apprenticeship Matching', 'IND-CAP-11'),
    ('Escalate Language and Performance Coaching', 'IND-CAP-24'),
    ('Escalate Learner Plan Creation Exceptions', 'IND-CAP-21'),
    ('Escalate Learner Progression Routing Exceptions', 'IND-CAP-02'),
    ('Escalate Lms Course Shell Launch', 'IND-CAP-13'),
    ('Escalate Remedial Intervention Cycle Exceptions', 'IND-CAP-22'),
    ('Escalate Remote Cohort Facilitation Exceptions', 'IND-CAP-15'),
    ('Escalate Research and Publishing Cycle', 'IND-CAP-28'),
    ('Escalate Rubric-based Learner Evaluation Exceptions', 'IND-CAP-18'),
    ('Escalate Safety VIP Accessibility Or', 'IND-CAP-22'),
    ('Escalate Skilling Delivery and Placement', 'IND-CAP-10'),
    ('Escalate Steam Maker-lab Learning Cycle', 'IND-CAP-08'),
    ('Escalate Teacher Development Intervention Exceptions', 'IND-CAP-07'),
    ('Escalate Tutoring Routing Exceptions With', 'IND-CAP-16'),
    ('Escalate Vocational Batch Alignment Exceptions', 'IND-CAP-09'),
    ('Escalation and Case Quality Evidence Audit', 'IND-CAP-22'),
    ('Evaluate Forecast Recommendation Confidence Evidence', 'IND-CAP-05'),
    ('Evaluate Forecast Recommendation Confidence Quality', 'IND-CAP-05'),
    ('Evaluate Forecast Recommendation With Confidence', 'IND-CAP-05'),
    ('Evaluate Statistical Experiment Result Evidence', 'IND-CAP-07'),
    ('Evaluate Statistical Experiment Result Quality', 'IND-CAP-07'),
    ('Evaluate Statistical Experiment Result With', 'IND-CAP-07'),
    ('Event Space Ready Service Release', 'IND-CAP-09'),
    ('Exam Operations Closure Documentation', 'IND-CAP-20'),
    ('Exam Operations File Review Evidence Preparation', 'IND-CAP-20'),
    ('Exam Operations Input Check', 'IND-CAP-20'),
    ('Exam Operations Standards and Evidence Audit', 'IND-CAP-20'),
    ('Exam Operations Standards and Staff Coaching', 'IND-CAP-20'),
    ('Exam Operations Work Loop Routine Execution', 'IND-CAP-20'),
    ('Exception Handling', 'IND-CAP-02'),
    ('Exchange Member/listing Ticket Handling', 'CAP-CM-002'),
    ('Execute BOPIS Order Preparation With', 'IND-CAP-03'),
    ('Execute Category Performance and Assortment', 'IND-CAP-09'),
    ('Execute Chargeback and Dispute Response', 'IND-CAP-28'),
    ('Execute Customer Issue Intake and', 'IND-CAP-21'),
    ('Execute Customer Pickup and With', 'IND-CAP-04'),
    ('Execute Distributor Stock and Credit', 'IND-CAP-16'),
    ('Execute Escalation and Case With', 'IND-CAP-22'),
    ('Execute GTIN and Barcode Governance', 'IND-CAP-17'),
    ('Execute Inventory Cycle Count and', 'IND-CAP-19'),
    ('Execute Loyalty Reward Correction With', 'IND-CAP-24'),
    ('Execute Marketplace Catalog and Product', 'IND-CAP-08'),
    ('Execute Marketplace Inventory Availability Monitoring', 'IND-CAP-06'),
    ('Execute Online Fulfillment Release With', 'IND-CAP-05'),
    ('Execute Outlet Distribution Expansion With', 'IND-CAP-13'),
    ('Execute Planogram and Shelf Compliance', 'IND-CAP-12'),
    ('Execute Price and Promotion Rule', 'IND-CAP-11'),
    ('Execute Product Data Traceability With', 'IND-CAP-18'),
    ('Execute Product Recall Risk Evaluation', 'IND-CAP-25'),
    ('Execute Recall Corrective With Operating', 'IND-CAP-26'),
    ('Execute Replenishment Exception With Operating', 'IND-CAP-20'),
    ('Execute Return and Exchange Processing', 'IND-CAP-23'),
    ('Execute Secondary Sales Follow-up With', 'IND-CAP-14'),
    ('Execute Seller-fulfilled Return Authorization With', 'IND-CAP-07'),
    ('Execute Shrink Investigation and Loss', 'IND-CAP-27'),
    ('Execute Supplier ESG and Packaging', 'IND-CAP-29'),
    ('Execute Trade Promotion Execution With', 'IND-CAP-15'),
    ('Execute Vendor Commercial and Promotion', 'IND-CAP-10'),
    ('Exit Offboarding Closure L1 Evidence Review', 'IND-CAP-28'),
    ('Exit Offboarding Closure L1 Execution', 'IND-CAP-28'),
    ('Exit Offboarding Closure L2 Evidence Review', 'IND-CAP-28'),
    ('Exit Offboarding Closure L2 Execution', 'IND-CAP-28'),
    ('Exit Offboarding Closure L3 Evidence Review', 'IND-CAP-28'),
    ('Exit Offboarding Closure L3 Execution', 'IND-CAP-28'),
    ('Exit Offboarding Closure L4 Evidence Review', 'IND-CAP-28'),
    ('Exit Offboarding Closure L4 Execution', 'IND-CAP-28'),
    ('Exit Offboarding Closure L5 Evidence Review', 'IND-CAP-28'),
    ('Exit Offboarding Closure L5 Execution', 'IND-CAP-28'),
    ('F&B Transaction Closure', 'IND-CAP-07'),
    ('Facility Inspection Safety SLA Intake Validation', 'CAP-REF-09'),
    ('Facility Inspection Safety SLA Quality Review', 'CAP-REF-09'),
    ('Facility Inspection Safety SLA Standards Coaching', 'CAP-REF-09'),
    ('Failed Transaction Classification', 'CAP-PAY-005'),
    ('Field-wise Crop Calendar and Planning', 'CAP-AFF-001'),
    ('Finished Dose BMR/BPR Packaging Artifact Completeness', 'CAP-003'),
    ('Finished Dose BMR/BPR Packaging Exception Readiness', 'CAP-003'),
    ('Finished Dose BMR/BPR Packaging Handoff Packet', 'CAP-003'),
    ('Fix Broken VAST Response Incorrect', 'IND-CAP-19'),
    ('Fix Missing Disclosure Incorrect Screenshot', 'IND-CAP-14'),
    ('Flag Discrepancy Where Billed Amount', 'IND-CAP-20'),
    ('Flag Timestamped Policy Risks With', 'IND-CAP-02'),
    ('FM Hard-services Work Order Intake Validation', 'CAP-REF-07'),
    ('FM Hard-services Work Order Quality Review', 'CAP-REF-07'),
    ('FM Hard-services Work Order Standards Coaching', 'CAP-REF-07'),
    ('FM Soft-services and Workplace Intake Validation', 'CAP-REF-08'),
    ('FM Soft-services and Workplace Quality Review', 'CAP-REF-08'),
    ('FM Soft-services and Workplace Standards Coaching', 'CAP-REF-08'),
    ('Forest Monitoring Pack Preparation', 'CAP-AFF-010'),
    ('FPO Aggregation Order Planning and', 'CAP-AFF-013'),
    ('Gameplay Scenario Stress Testing', 'IND-CAP-15'),
    ('Gameplay Stress Testing Coaching', 'IND-CAP-15'),
    ('Gate Scans Monitoring', 'IND-CAP-22'),
    ('Generate Synthetic Dataset Statistical Evidence', 'IND-CAP-20'),
    ('Generate Synthetic Dataset Statistical Quality', 'IND-CAP-20'),
    ('Generate Synthetic Dataset With Statistical', 'IND-CAP-20'),
    ('Go-live Status Signal Notes and', 'IND-CAP-11'),
    ('Gold Metric Grain Mapping', 'IND-CAP-02'),
    ('Governed Analytics Dataset for Evidence Coaching', 'IND-CAP-04'),
    ('Governed Analytics Dataset for Evidence Preparation', 'IND-CAP-04'),
    ('Governed Analytics Dataset for Quality Improvement', 'IND-CAP-04'),
    ('Governed Lineage Owners Classifications Evidence', 'IND-CAP-13'),
    ('Governed Lineage Owners Classifications Quality', 'IND-CAP-13'),
    ('Governed Metadata Registration', 'IND-CAP-01'),
    ('Government/NGO Program Escalation', 'IND-CAP-27'),
    ('Government/NGO Program Evidence Audit', 'IND-CAP-27'),
    ('Government/NGO Program Input Identification', 'IND-CAP-27'),
    ('Government/NGO Program Quality Review', 'IND-CAP-27'),
    ('Government/NGO Program Routine Execution', 'IND-CAP-27'),
    ('Government/NGO Program Staff Coaching', 'IND-CAP-27'),
    ('GTIN and Barcode Governance Evidence Audit', 'IND-CAP-17'),
    ('GTIN and Barcode Governance Interpretation', 'IND-CAP-17'),
    ('GTIN and Barcode Governance Resolution', 'IND-CAP-17'),
    ('Guest Arrival Resolution', 'IND-CAP-04'),
    ('Guest Identity Hold Resolution', 'IND-CAP-01'),
    ('Guest Reception', 'IND-CAP-01'),
    ('Harvest and Procurement Lot', 'CAP-AFF-002'),
    ('Hatchery Seed Batch and Dispatch', 'CAP-AFF-007'),
    ('High-risk Onboarding Exception', 'CAP-X-001'),
    ('Host Issue Escalation', 'IND-CAP-05'),
    ('Human-AI Workflow Validation', 'IND-CAP-17'),
    ('Identify Content Sources Retrieval Evidence Coaching', 'IND-CAP-16'),
    ('Identify Content Sources Retrieval Quality Improvement', 'IND-CAP-16'),
    ('Improve Pattern Analysis for Activated', 'IND-CAP-03'),
    ('Improve Pattern Analysis for Aligned', 'IND-CAP-09'),
    ('Improve Pattern Analysis for Assessment', 'IND-CAP-17'),
    ('Improve Pattern Analysis for Career', 'IND-CAP-23'),
    ('Improve Pattern Analysis for Coaching', 'IND-CAP-24'),
    ('Improve Pattern Analysis for Curriculum', 'IND-CAP-05'),
    ('Improve Pattern Analysis for Delivery', 'IND-CAP-10'),
    ('Improve Pattern Analysis for Exam', 'IND-CAP-20'),
    ('Improve Pattern Analysis for Individual', 'IND-CAP-04'),
    ('Improve Pattern Analysis for Launch-ready', 'IND-CAP-13'),
    ('Improve Pattern Analysis for Learner', 'IND-CAP-14'),
    ('Improve Pattern Analysis for Matched', 'IND-CAP-11'),
    ('Improve Pattern Analysis for Program', 'IND-CAP-27'),
    ('Improve Pattern Analysis for Progression', 'IND-CAP-02'),
    ('Improve Pattern Analysis for Release-ready', 'IND-CAP-06'),
    ('Improve Pattern Analysis for Remedial', 'IND-CAP-22'),
    ('Improve Pattern Analysis for Remote', 'IND-CAP-15'),
    ('Improve Pattern Analysis for Research/publishing', 'IND-CAP-28'),
    ('Improve Pattern Analysis for Resourced', 'IND-CAP-08'),
    ('Improve Pattern Analysis for Scored', 'IND-CAP-18'),
    ('Improve Pattern Analysis for Session', 'IND-CAP-01'),
    ('Improve Pattern Analysis for Teacher', 'IND-CAP-07'),
    ('Improve Pattern Analysis for TNA', 'IND-CAP-12'),
    ('Improve Pattern Analysis for Tutoring', 'IND-CAP-16'),
    ('Improve Pattern Analysis for Validated', 'IND-CAP-25'),
    ('Improve Pattern Analysis for Verified', 'IND-CAP-19'),
    ('Incorrect Package Missing Item Resolution', 'IND-CAP-08'),
    ('Incorrect Platform Advice/Resolution', 'IND-CAP-12'),
    ('Individual Learning Pathway Plan Evidence Preparation', 'IND-CAP-04'),
    ('Industrial Bioprocess Scale-up and Controlled Intake', 'CAP-014'),
    ('Industrial Bioprocess Scale-up and Exception Readiness', 'CAP-014'),
    ('Ingest Editorial Plates Into VFX', 'IND-CAP-05'),
    ('Input Dealer Demand and Product-use', 'CAP-AFF-011'),
    ('Input Routing Mapping', 'IND-CAP-11'),
    ('Inspect Failed Test Logs Screenshots', 'IND-CAP-16'),
    ('Inspect Sample Segments for Audio', 'IND-CAP-12'),
    ('Inspection and Test Validation', 'CIE-CAP-002'),
    ('Internship and Apprenticeship Matching Evidence Audit', 'IND-CAP-11'),
    ('Internship and Apprenticeship Matching Input', 'IND-CAP-11'),
    ('Internship and Apprenticeship Matching Routine', 'IND-CAP-11'),
    ('Internship and Apprenticeship Matching Staff Coaching', 'IND-CAP-11'),
    ('Interpret Heterogeneous Effects Across Evidence', 'IND-CAP-07'),
    ('Interview Scorecard L1 Evidence Review', 'IND-CAP-03'),
    ('Interview Scorecard L1 Execution', 'IND-CAP-03'),
    ('Interview Scorecard L2 Evidence Review', 'IND-CAP-03'),
    ('Interview Scorecard L2 Execution', 'IND-CAP-03'),
    ('Interview Scorecard L3 Evidence Review', 'IND-CAP-03'),
    ('Interview Scorecard L3 Execution', 'IND-CAP-03'),
    ('Interview Scorecard L4 Evidence Review', 'IND-CAP-03'),
    ('Interview Scorecard L4 Execution', 'IND-CAP-03'),
    ('Interview Scorecard L5 Evidence Review', 'IND-CAP-03'),
    ('Interview Scorecard L5 Execution', 'IND-CAP-03'),
    ('Inventory Candidate AI Initiatives By', 'IND-CAP-19'),
    ('Inventory Cycle Count and Evidence Audit', 'IND-CAP-19'),
    ('Inventory Cycle Count and Interpretation', 'IND-CAP-19'),
    ('Inventory Cycle Count and Resolution', 'IND-CAP-19'),
    ('Inventory Ledger Tool Use', 'IND-CAP-19'),
    ('Investor Grievance Case Registration', 'CAP-CM-003'),
    ('Issue Governance Gate Decision Evidence Coaching', 'IND-CAP-14'),
    ('Issue Governance Gate Decision With', 'IND-CAP-14'),
    ('Item Hierarchy GTIN Assignment Validation', 'IND-CAP-17'),
    ('IVD Performance Diagnostic and Controlled Intake', 'CAP-018B'),
    ('IVD Performance Diagnostic and Exception Readiness', 'CAP-018B'),
    ('Kitchen Prep Sequencing', 'IND-CAP-08'),
    ('Kitchen Production Coordination Eligibility', 'IND-CAP-08'),
    ('Kitchen Production Coordination Reconciliation', 'IND-CAP-08'),
    ('Kitchen Production Coordination Work Capture', 'IND-CAP-08'),
    ('Knowledge Graph Modeling', 'IND-CAP-21'),
    ('KYC CDD Checklist Handling', 'CAP-X-001'),
    ('Language and Performance Coaching Evidence Audit', 'IND-CAP-24'),
    ('Language and Performance Coaching Routine Execution', 'IND-CAP-24'),
    ('Language and Performance Coaching Staff Coaching', 'IND-CAP-24'),
    ('Launch Encoding Job With Source', 'IND-CAP-12'),
    ('Launch-ready LMS Shell Review Evidence Preparation', 'IND-CAP-13'),
    ('Learner Engagement Input Check', 'IND-CAP-14'),
    ('Learner Engagement Monitoring Log Evidence Preparation', 'IND-CAP-14'),
    ('Learner Plan Creation Standards Evidence Audit', 'IND-CAP-21'),
    ('Learner Plan Creation Standards Staff Coaching', 'IND-CAP-21'),
    ('Learner Plan Creation Work Routine Execution', 'IND-CAP-21'),
    ('Learner Plan Input Check', 'IND-CAP-21'),
    ('Learner Plan Review Evidence Preparation', 'IND-CAP-21'),
    ('Learner Progression Input Check', 'IND-CAP-02'),
    ('Learner Progression Routing Evidence Audit', 'IND-CAP-02'),
    ('Learner Progression Routing Quality Pattern Review', 'IND-CAP-02'),
    ('Learner Progression Routing Routine Execution', 'IND-CAP-02'),
    ('Learner Progression Routing Staff Coaching', 'IND-CAP-02'),
    ('Learning Needs Input Check', 'IND-CAP-12'),
    ('Lms Course Shell Launch Evidence Audit', 'IND-CAP-13'),
    ('Lms Course Shell Launch Routine Execution', 'IND-CAP-13'),
    ('Lms Course Shell Launch Staff Coaching', 'IND-CAP-13'),
    ('LMS Launch Input Check', 'IND-CAP-13'),
    ('LMS Shell Closure Documentation', 'IND-CAP-13'),
    ('Load Assigned QA Build On', 'IND-CAP-15'),
    ('Local Smoke Build Testing', 'IND-CAP-13'),
    ('Log Release-gate Defect With Environment', 'IND-CAP-13'),
    ('Loyalty Reward Correction Exceptions Resolution', 'IND-CAP-24'),
    ('Loyalty Reward Correction Quality Evidence Audit', 'IND-CAP-24'),
    ('Loyalty Reward Correction Triggers Interpretation', 'IND-CAP-24'),
    ('Machinery Demo and Service Job', 'CAP-AFF-012'),
    ('Maintain Governed Lineage With Owners', 'IND-CAP-13'),
    ('Manage Workplace Investigation Cases L1 Evidence', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L1 Execution', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L2 Evidence', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L2 Execution', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L3 Evidence', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L3 Execution', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L4 Evidence', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L4 Execution', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L5 Evidence', 'IND-CAP-26'),
    ('Manage Workplace Investigation Cases L5 Execution', 'IND-CAP-26'),
    ('Map AI Output to Evidence Coaching', 'IND-CAP-18'),
    ('Map AI Output to Quality Improvement', 'IND-CAP-18'),
    ('Marketplace Catalog and Product Evidence Audit', 'IND-CAP-08'),
    ('Marketplace Catalog and Product Interpretation', 'IND-CAP-08'),
    ('Marketplace Catalog and Product Resolution', 'IND-CAP-08'),
    ('Marketplace Inventory Availability Monitoring', 'IND-CAP-06'),
    ('Marketplace Inventory Availability Monitoring Evidence', 'IND-CAP-06'),
    ('Marketplace Seller Portal Tool Use', 'IND-CAP-08'),
    ('Marketplace Stock Signal FBA/seller Validation', 'IND-CAP-06'),
    ('Matched Internship/apprenticeship Placement File', 'IND-CAP-11'),
    ('Medical Device Technical File Artifact Completeness', 'CAP-017'),
    ('Medical Device Technical File Cross-artifact', 'CAP-017'),
    ('Medical Device Technical File Exception Readiness', 'CAP-017'),
    ('Medical Device Technical File Handoff Packet', 'CAP-017'),
    ('Member Profile Points Accrual Validation', 'IND-CAP-24'),
    ('Merchant Activation Bottleneck Tracking', 'CAP-PAY-002'),
    ('Merchant Onboarding', 'CAP-PAY-002'),
    ('Mice Coordination Event Logistics Capture', 'IND-CAP-10'),
    ('Mice Coordination Event Logistics Confirmation', 'IND-CAP-10'),
    ('Mice Coordination Event Logistics Reconciliation', 'IND-CAP-10'),
    ('MICE Stakeholder Dependency Resolution', 'IND-CAP-10'),
    ('Missed Gate Wrong Queue Resolution', 'IND-CAP-02'),
    ('Missing Audio Unstable Bitrate Resolution', 'IND-CAP-11'),
    ('Missing Passenger Wrong Count Resolution', 'IND-CAP-11'),
    ('Model Drift Response', 'IND-CAP-11'),
    ('Model Edge Version Control', 'IND-CAP-10'),
    ('NCR Defect and Punch-list', 'CIE-CAP-002'),
    ('NCR Defect and Punch-list', 'CIE-CAP-006'),
    ('NGS Run QC Variant Artifact Completeness', 'CAP-011'),
    ('NGS Run QC Variant Cross-artifact Reconciliation', 'CAP-011'),
    ('NGS Run QC Variant Exception Readiness', 'CAP-011'),
    ('NGS Run QC Variant Handoff Packet', 'CAP-011'),
    ('NLP/LLM Candidate Evaluation', 'IND-CAP-09'),
    ('NLP/LLM Evaluation Quality Review', 'IND-CAP-09'),
    ('Notify Producer of Accepted Platform', 'IND-CAP-24'),
    ('NTFP Collection Lot Registration and', 'CAP-AFF-010'),
    ('Nursery Batch and Planting-material', 'CAP-AFF-003'),
    ('Offer Handoff L1 Evidence Review', 'IND-CAP-04'),
    ('Offer Handoff L1 Execution', 'IND-CAP-04'),
    ('Offer Handoff L2 Evidence Review', 'IND-CAP-04'),
    ('Offer Handoff L2 Execution', 'IND-CAP-04'),
    ('Offer Handoff L3 Evidence Review', 'IND-CAP-04'),
    ('Offer Handoff L3 Execution', 'IND-CAP-04'),
    ('Offer Handoff L4 Evidence Review', 'IND-CAP-04'),
    ('Offer Handoff L4 Execution', 'IND-CAP-04'),
    ('Offer Handoff L5 Evidence Review', 'IND-CAP-04'),
    ('Offer Handoff L5 Execution', 'IND-CAP-04'),
    ('Office Occupier Requirement and Intake Validation', 'CAP-REF-03'),
    ('Office Occupier Requirement and Quality Review', 'CAP-REF-03'),
    ('Office Occupier Requirement and Standards Coaching', 'CAP-REF-03'),
    ('Office Occupier Service Handoff Intake Validation', 'CAP-REF-04'),
    ('Office Occupier Service Handoff Quality Review', 'CAP-REF-04'),
    ('Office Occupier Service Handoff Standards Coaching', 'CAP-REF-04'),
    ('Oms Pickup Order Tool Use', 'IND-CAP-03'),
    ('Online Fulfillment Release Control Interpretation', 'IND-CAP-05'),
    ('Online Fulfillment Release Control Resolution', 'IND-CAP-05'),
    ('Online Fulfillment Release Quality Evidence Audit', 'IND-CAP-05'),
    ('Open Character Shot With Assigned', 'IND-CAP-08'),
    ('Open Finishing Project With Correct', 'IND-CAP-07'),
    ('Open Rights Claim Case With', 'IND-CAP-17'),
    ('Operate Canary Model Release Evidence Coaching', 'IND-CAP-10'),
    ('Operate Canary Model Release Quality Improvement', 'IND-CAP-10'),
    ('Operate Canary Model Release With', 'IND-CAP-10'),
    ('Operate Learning Program Setup L1 Evidence', 'IND-CAP-22'),
    ('Operate Learning Program Setup L1 Execution', 'IND-CAP-22'),
    ('Operate Learning Program Setup L2 Evidence', 'IND-CAP-22'),
    ('Operate Learning Program Setup L2 Execution', 'IND-CAP-22'),
    ('Operate Learning Program Setup L3 Evidence', 'IND-CAP-22'),
    ('Operate Learning Program Setup L3 Execution', 'IND-CAP-22'),
    ('Operate Learning Program Setup L4 Evidence', 'IND-CAP-22'),
    ('Operate Learning Program Setup L4 Execution', 'IND-CAP-22'),
    ('Operate Learning Program Setup L5 Evidence', 'IND-CAP-22'),
    ('Operate Learning Program Setup L5 Execution', 'IND-CAP-22'),
    ('Operational Risk Audit', 'CAP-X-003'),
    ('Optimization of Academic Activation Quality Pattern', 'IND-CAP-03'),
    ('Optimization of Admissions Document Quality Pattern', 'IND-CAP-25'),
    ('Optimization of Adult Learner Quality Pattern', 'IND-CAP-04'),
    ('Optimization of Assessment Blueprint Quality Pattern', 'IND-CAP-17'),
    ('Optimization of Career Guidance Quality Pattern', 'IND-CAP-23'),
    ('Optimization of Cohort Session Quality Pattern', 'IND-CAP-01'),
    ('Optimization of Corporate Learning Quality Pattern', 'IND-CAP-12'),
    ('Optimization of Credential Issuance Quality Pattern', 'IND-CAP-19'),
    ('Optimization of Curriculum Alignment Quality Pattern', 'IND-CAP-05'),
    ('Optimization of Digital Learner Quality Pattern', 'IND-CAP-14'),
    ('Optimization of Education MIS Quality Pattern', 'IND-CAP-26'),
    ('Optimization of Exam Operations Quality Pattern', 'IND-CAP-20'),
    ('Optimization of Internship and Quality Pattern', 'IND-CAP-11'),
    ('Optimization of Language and Quality Pattern', 'IND-CAP-24'),
    ('Optimization of Learner Plan Quality Pattern', 'IND-CAP-21'),
    ('Optimization of LMS Course Quality Pattern', 'IND-CAP-13'),
    ('Optimization of Remedial Intervention Quality Pattern', 'IND-CAP-22'),
    ('Optimization of Remote Cohort Quality Pattern', 'IND-CAP-15'),
    ('Optimization of Research and Quality Pattern', 'IND-CAP-28'),
    ('Optimization of Rubric-based Learner Quality Pattern', 'IND-CAP-18'),
    ('Optimization of STEAM Maker-lab Quality Pattern', 'IND-CAP-08'),
    ('Optimization of Tutoring Routing Quality Pattern', 'IND-CAP-16'),
    ('Optimization of Vocational Batch Quality Pattern', 'IND-CAP-09'),
    ('Orchard and Plantation Block Condition', 'CAP-AFF-004'),
    ('Order Management System Tool Use', 'IND-CAP-05'),
    ('Organization Change Communication Impact L1 Evidence', 'IND-CAP-18'),
    ('Organization Change Communication Impact L2 Evidence', 'IND-CAP-18'),
    ('Organization Change Communication Impact L3 Evidence', 'IND-CAP-18'),
    ('Organization Change Communication Impact L4 Evidence', 'IND-CAP-18'),
    ('Organization Change Communication Impact L5 Evidence', 'IND-CAP-18'),
    ('Organization Change Communication L1 Execution', 'IND-CAP-18'),
    ('Organization Change Communication L2 Execution', 'IND-CAP-18'),
    ('Organization Change Communication L3 Execution', 'IND-CAP-18'),
    ('Organization Change Communication L4 Execution', 'IND-CAP-18'),
    ('Organization Change Communication L5 Execution', 'IND-CAP-18'),
    ('Outlet Distribution Expansion Exceptions Resolution', 'IND-CAP-13'),
    ('Outlet Distribution Expansion Quality Evidence Audit', 'IND-CAP-13'),
    ('Outlet Distribution Expansion Triggers Interpretation', 'IND-CAP-13'),
    ('Outlet Priority List Retailer Validation', 'IND-CAP-13'),
    ('Outlet Visit Plan Tool Use', 'IND-CAP-13'),
    ('Pack-grade Harvest Segregation and Lot', 'CAP-AFF-004'),
    ('Packhouse Intake Grading and Lot', 'CAP-AFF-014'),
    ('Paid Online Order Inventory Validation', 'IND-CAP-05'),
    ('Participant Exception', 'CAP-PAY-001'),
    ('Passenger Terminal Frontline Service Capture', 'IND-CAP-02'),
    ('Passenger Terminal Frontline Service Confirmation', 'IND-CAP-02'),
    ('Passenger Terminal Frontline Service Reconciliation', 'IND-CAP-02'),
    ('Patch Test Locator Fixture Or', 'IND-CAP-16'),
    ('Pathway Design Input Check', 'IND-CAP-04'),
    ('Payment Break Investigation', 'CAP-PAY-004'),
    ('Payment Operations Issue Triage', 'CAP-PAY-003'),
    ('Payment Product Performance Segmentation', 'CAP-PAY-003'),
    ('Payment Rail Coordination', 'CAP-PAY-001'),
    ('Payment Settlement File and Obligation', 'CAP-PAY-004'),
    ('Payroll Exception Correction L1 Evidence Review', 'IND-CAP-10'),
    ('Payroll Exception Correction L1 Execution', 'IND-CAP-10'),
    ('Payroll Exception Correction L2 Evidence Review', 'IND-CAP-10'),
    ('Payroll Exception Correction L2 Execution', 'IND-CAP-10'),
    ('Payroll Exception Correction L3 Evidence Review', 'IND-CAP-10'),
    ('Payroll Exception Correction L3 Execution', 'IND-CAP-10'),
    ('Payroll Exception Correction L4 Evidence Review', 'IND-CAP-10'),
    ('Payroll Exception Correction L4 Execution', 'IND-CAP-10'),
    ('Payroll Exception Correction L5 Evidence Review', 'IND-CAP-10'),
    ('Payroll Exception Correction L5 Execution', 'IND-CAP-10'),
    ('Payroll Input Validation L1 Evidence Review', 'IND-CAP-09'),
    ('Payroll Input Validation L1 Execution', 'IND-CAP-09'),
    ('Payroll Input Validation L2 Evidence Review', 'IND-CAP-09'),
    ('Payroll Input Validation L2 Execution', 'IND-CAP-09'),
    ('Payroll Input Validation L3 Evidence Review', 'IND-CAP-09'),
    ('Payroll Input Validation L3 Execution', 'IND-CAP-09'),
    ('Payroll Input Validation L4 Evidence Review', 'IND-CAP-09'),
    ('Payroll Input Validation L4 Execution', 'IND-CAP-09'),
    ('Payroll Input Validation L5 Evidence Review', 'IND-CAP-09'),
    ('Payroll Input Validation L5 Execution', 'IND-CAP-09'),
    ('Performance Metric Gap Diagnosis', 'IND-CAP-12'),
    ('Periodic-review Gap and Audit-pack Preparation', 'CAP-BANK-002'),
    ('Pharmacovigilance ICSR and Safety Artifact Completeness', 'CAP-009'),
    ('Pharmacovigilance ICSR and Safety Exception Readiness', 'CAP-009'),
    ('Pharmacovigilance ICSR and Safety Handoff Packet', 'CAP-009'),
    ('Pickup Customer Identity Order Validation', 'IND-CAP-04'),
    ('PIM Feed Traceability Maintenance', 'IND-CAP-18'),
    ('PIM Merchant Feed Maintenance', 'IND-CAP-17'),
    ('Pipeline Change Review', 'IND-CAP-11'),
    ('Placement Device Targeting Frequency Configuration', 'IND-CAP-19'),
    ('Placement Monitoring Input Check', 'IND-CAP-10'),
    ('Placement Readiness Monitoring Evidence Audit', 'IND-CAP-10'),
    ('Placement Readiness Monitoring Quality Pattern Review', 'IND-CAP-10'),
    ('Placement Readiness Monitoring Routine Execution', 'IND-CAP-10'),
    ('Placement Readiness Monitoring Staff Coaching', 'IND-CAP-10'),
    ('Planogram and Shelf Compliance Evidence Audit', 'IND-CAP-12'),
    ('Planogram and Shelf Compliance Interpretation', 'IND-CAP-12'),
    ('Planogram and Shelf Compliance Resolution', 'IND-CAP-12'),
    ('Planogram File Tool Use', 'IND-CAP-12'),
    ('Platform Rejection Response', 'IND-CAP-24'),
    ('Play Critical Tutorial Economy Session', 'IND-CAP-15'),
    ('Portal Rejection Resolution', 'IND-CAP-09'),
    ('Portfolio Early-warning Segmentation', 'CAP-CREDIT-003'),
    ('POS Terminal Tool Use', 'IND-CAP-07'),
    ('Poultry Flock Performance and Mortality', 'CAP-AFF-005'),
    ('Prep Station Sequencing', 'IND-CAP-07'),
    ('Preview Episode Entry for Title', 'IND-CAP-24'),
    ('Price and Promotion Rule Evidence Audit', 'IND-CAP-11'),
    ('Price and Promotion Rule Interpretation', 'IND-CAP-11'),
    ('Price and Promotion Rule Resolution', 'IND-CAP-11'),
    ('Price Rule Discount Setup Validation', 'IND-CAP-11'),
    ('Pricing Engine Tool Use', 'IND-CAP-11'),
    ('Prioritize Product Changes for Evidence Coaching', 'IND-CAP-17'),
    ('Prioritize Product Changes for Quality Improvement', 'IND-CAP-17'),
    ('Prioritize Product Changes for Response', 'IND-CAP-17'),
    ('Procurement Weighment and Dispatch', 'CAP-AFF-013'),
    ('Product Attributes GTIN Variant Validation', 'IND-CAP-08'),
    ('Product Data Traceability Control Interpretation', 'IND-CAP-18'),
    ('Product Data Traceability Control Resolution', 'IND-CAP-18'),
    ('Product Data Traceability Quality Evidence Audit', 'IND-CAP-18'),
    ('Product Master Package Metadata Validation', 'IND-CAP-18'),
    ('Product Recall Risk Evaluation Evidence Audit', 'IND-CAP-25'),
    ('Product Recall Risk Evaluation Interpretation', 'IND-CAP-25'),
    ('Product Recall Risk Evaluation Resolution', 'IND-CAP-25'),
    ('Program Tracking Closure Documentation', 'IND-CAP-27'),
    ('Program Tracking Report Review Evidence Preparation', 'IND-CAP-27'),
    ('Progress Schedule Update and Delay', 'CIE-CAP-003'),
    ('Progression Review File and Evidence Preparation', 'IND-CAP-02'),
    ('Property Occupancy Service-charge and Intake Validation', 'CAP-REF-06'),
    ('Property Occupancy Service-charge and Quality Review', 'CAP-REF-06'),
    ('Property Occupancy Service-charge and Standards', 'CAP-REF-06'),
    ('Protected Cultivation Crop-cycle Log', 'CAP-AFF-003'),
    ('Public Listing Readiness Confirmation', 'IND-CAP-21'),
    ('Publish Automation Gate Result With', 'IND-CAP-16'),
    ('Publish Feature Specification With Output', 'IND-CAP-16'),
    ('Publishing Cycle Input Check', 'IND-CAP-28'),
    ('Pull Release Branch and Verify', 'IND-CAP-13'),
    ('Quarantine Mismatched Plates and Request', 'IND-CAP-05'),
    ('Rail Station Passenger Operations Capture', 'IND-CAP-12'),
    ('Rail Station Passenger Operations Confirmation', 'IND-CAP-12'),
    ('Rail Station Passenger Operations Reconciliation', 'IND-CAP-12'),
    ('Recall Corrective Action Closure Interpretation', 'IND-CAP-26'),
    ('Recall Corrective Action Closure Resolution', 'IND-CAP-26'),
    ('Recall Corrective Action Quality Evidence Audit', 'IND-CAP-26'),
    ('Recall Register and Affected Tool Use', 'IND-CAP-25'),
    ('Recall Scope Register Tool Use', 'IND-CAP-26'),
    ('Receive Campaign Trafficking Sheet With', 'IND-CAP-19'),
    ('Refresh and Certify KPI Quality Improvement', 'IND-CAP-04'),
    ('Refresh and Certify KPI Reporting', 'IND-CAP-04'),
    ('Refund Eligibility Escalation', 'IND-CAP-03'),
    ('Regulatory Report Evidence', 'CAP-X-003'),
    ('Rejection Remediation Handoff', 'IND-CAP-14'),
    ('Release Pass Conditional Pass Recommendation', 'IND-CAP-15'),
    ('Release-ready E-learning Package Review Evidence', 'IND-CAP-06'),
    ('Remedial Intervention Closure Documentation', 'IND-CAP-22'),
    ('Remedial Intervention Cycle Standards Evidence Audit', 'IND-CAP-22'),
    ('Remedial Intervention Cycle Standards Staff Coaching', 'IND-CAP-22'),
    ('Remedial Intervention Cycle Work Routine Execution', 'IND-CAP-22'),
    ('Remedial Intervention Input Check', 'IND-CAP-22'),
    ('Remedial Intervention Log Review Evidence Preparation', 'IND-CAP-22'),
    ('Remote Cohort Facilitation Standards Evidence Audit', 'IND-CAP-15'),
    ('Remote Cohort Facilitation Standards Staff Coaching', 'IND-CAP-15'),
    ('Remote Cohort Facilitation Work Routine Execution', 'IND-CAP-15'),
    ('Remote Facilitation Input Check', 'IND-CAP-15'),
    ('Remote Session Log Closure Documentation', 'IND-CAP-15'),
    ('Remote Session Log Review Evidence Preparation', 'IND-CAP-15'),
    ('Render Package Evidence Coaching', 'IND-CAP-08'),
    ('Render Queue Frame Submission', 'IND-CAP-08'),
    ('Rendition Generation Monitoring', 'IND-CAP-12'),
    ('Rendition Recovery Coaching', 'IND-CAP-12'),
    ('Replay Controlled Event Sample Evidence Coaching', 'IND-CAP-03'),
    ('Replenishment Exception Control Exceptions Resolution', 'IND-CAP-20'),
    ('Replenishment Exception Control Triggers Interpretation', 'IND-CAP-20'),
    ('Replenishment Exception Quality and Evidence Audit', 'IND-CAP-20'),
    ('Replenishment Proposal and Service-level Tool Use', 'IND-CAP-20'),
    ('Report Launch Status Tracking Limitations', 'IND-CAP-19'),
    ('Requisition Launch L1 Evidence Review', 'IND-CAP-01'),
    ('Requisition Launch L1 Execution', 'IND-CAP-01'),
    ('Requisition Launch L2 Evidence Review', 'IND-CAP-01'),
    ('Requisition Launch L2 Execution', 'IND-CAP-01'),
    ('Requisition Launch L3 Evidence Review', 'IND-CAP-01'),
    ('Requisition Launch L3 Execution', 'IND-CAP-01'),
    ('Requisition Launch L4 Evidence Review', 'IND-CAP-01'),
    ('Requisition Launch L4 Execution', 'IND-CAP-01'),
    ('Requisition Launch L5 Evidence Review', 'IND-CAP-01'),
    ('Requisition Launch L5 Execution', 'IND-CAP-01'),
    ('RERA Project Disclosure Gap Intake Validation', 'CAP-REF-02'),
    ('RERA Project Disclosure Gap Quality Review', 'CAP-REF-02'),
    ('RERA Project Disclosure Gap Standards Coaching', 'CAP-REF-02'),
    ('Research and Publishing Cycle Evidence Audit', 'IND-CAP-28'),
    ('Research and Publishing Cycle Routine Execution', 'IND-CAP-28'),
    ('Research and Publishing Cycle Staff Coaching', 'IND-CAP-28'),
    ('Research/publishing Tracker Review Evidence Preparation', 'IND-CAP-28'),
    ('Residential Buyer Documentation and Intake Validation', 'CAP-REF-01'),
    ('Residential Buyer Documentation and Quality Review', 'CAP-REF-01'),
    ('Residential Buyer Documentation and Standards Coaching', 'CAP-REF-01'),
    ('Resolve Employee Grievances Severity L1 Evidence', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L1 Execution', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L2 Evidence', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L2 Execution', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L3 Evidence', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L3 Execution', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L4 Evidence', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L4 Execution', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L5 Evidence', 'IND-CAP-25'),
    ('Resolve Employee Grievances Severity L5 Execution', 'IND-CAP-25'),
    ('Resolve Employee Hr Service L1 Evidence', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L1 Execution', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L2 Evidence', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L2 Execution', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L3 Evidence', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L3 Execution', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L4 Evidence', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L4 Execution', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L5 Evidence', 'IND-CAP-15'),
    ('Resolve Employee Hr Service L5 Execution', 'IND-CAP-15'),
    ('Resourced Project Cycle Plan Evidence Preparation', 'IND-CAP-08'),
    ('Return and Exchange Processing Evidence Audit', 'IND-CAP-23'),
    ('Return and Exchange Processing Interpretation', 'IND-CAP-23'),
    ('Return and Exchange Processing Resolution', 'IND-CAP-23'),
    ('Return Eligibility Item Condition Validation', 'IND-CAP-23'),
    ('Review App Store Metadata Fields', 'IND-CAP-14'),
    ('Review Flagged Video Against Advertiser', 'IND-CAP-18'),
    ('Review Governed Data Access Against', 'IND-CAP-13'),
    ('Review Governed Data Access Evidence Coaching', 'IND-CAP-13'),
    ('Review Governed Data Access Quality Improvement', 'IND-CAP-13'),
    ('Review Hallucination Unsafe Content Evidence Coaching', 'IND-CAP-09'),
    ('Review Hallucination Unsafe Content Or', 'IND-CAP-09'),
    ('Review Hallucination Unsafe Content Quality Improvement', 'IND-CAP-09'),
    ('Review Release Metadata Artist Positioning', 'IND-CAP-23'),
    ('Review Slicer Behavior and Evidence Coaching', 'IND-CAP-04'),
    ('Review Slicer Behavior and Filter', 'IND-CAP-04'),
    ('Review Slicer Behavior and Quality Improvement', 'IND-CAP-04'),
    ('Road Mobility Vehicle Rental Capture', 'IND-CAP-13'),
    ('Road Mobility Vehicle Rental Confirmation', 'IND-CAP-13'),
    ('Road Mobility Vehicle Rental Reconciliation', 'IND-CAP-13'),
    ('Roll Out Edge Inference Package', 'IND-CAP-12'),
    ('Roll Out Edge Inference Quality Improvement', 'IND-CAP-12'),
    ('Room Readiness Housekeeping Eligibility Confirmation', 'IND-CAP-04'),
    ('Room Readiness Housekeeping Reconciliation', 'IND-CAP-04'),
    ('Room Readiness Housekeeping Work Capture', 'IND-CAP-04'),
    ('Room Released Despite Defect Resolution', 'IND-CAP-04'),
    ('Rough Promo Cut Review', 'IND-CAP-01'),
    ('RSS Feed Url Enclosure Validation', 'IND-CAP-24'),
    ('RTA Investor Update', 'CAP-CM-006'),
    ('Rubric Evaluation Input Check', 'IND-CAP-18'),
    ('Rubric-based Learner Evaluation Standards Evidence', 'IND-CAP-18'),
    ('Rubric-based Learner Evaluation Standards Staff', 'IND-CAP-18'),
    ('Rubric-based Learner Evaluation Work Routine Execution', 'IND-CAP-18'),
    ('Run Decision Optimization Scenario Evidence Coaching', 'IND-CAP-05'),
    ('Run Decision Optimization Scenario Quality Improvement', 'IND-CAP-05'),
    ('Run Decision Optimization Scenario With', 'IND-CAP-05'),
    ('Run Performance Cycle Setup L1 Evidence', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L1 Execution', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L2 Evidence', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L2 Execution', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L3 Evidence', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L3 Execution', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L4 Evidence', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L4 Execution', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L5 Evidence', 'IND-CAP-23'),
    ('Run Performance Cycle Setup L5 Execution', 'IND-CAP-23'),
    ('Run Pre-live Checklist With Stream', 'IND-CAP-11'),
    ('Safety Signal Affected Lot Validation', 'IND-CAP-25'),
    ('Sales Margin Assortment and Validation', 'IND-CAP-09'),
    ('SaMD Lifecycle V&V and Evidence Inventory', 'CAP-018C'),
    ('SaMD Lifecycle V&V and Exception Handoff', 'CAP-018C'),
    ('Sanction Condition Tracking', 'CAP-CREDIT-002'),
    ('Sanctions and Watchlist Screening Triage', 'CAP-X-002'),
    ('Scene Timestamping Coaching', 'IND-CAP-18'),
    ('Scheme Terms Outlet Display Validation', 'IND-CAP-15'),
    ('Scored Evaluation Closure Documentation', 'IND-CAP-18'),
    ('Scored Evaluation File Review Evidence Preparation', 'IND-CAP-18'),
    ('SCORES ODR Response Preparation', 'CAP-CM-003'),
    ('Seat Baggage Boarding Update', 'IND-CAP-11'),
    ('Secondary Sales Follow-up Exceptions Resolution', 'IND-CAP-14'),
    ('Secondary Sales Follow-up Quality Evidence Audit', 'IND-CAP-14'),
    ('Secondary Sales Follow-up Triggers Interpretation', 'IND-CAP-14'),
    ('Securities Trade Intake', 'CAP-CM-001'),
    ('Select Certified Tables and Semantic', 'IND-CAP-04'),
    ('Seller-fulfilled Return Authorization Exceptions', 'IND-CAP-07'),
    ('Seller-fulfilled Return Authorization Quality Evidence', 'IND-CAP-07'),
    ('Seller-fulfilled Return Authorization Triggers', 'IND-CAP-07'),
    ('Served Item Bill Confirmation', 'IND-CAP-08'),
    ('Service Delay Resolution', 'IND-CAP-07'),
    ('Service Recovery Customer Support Capture', 'IND-CAP-03'),
    ('Service Recovery Customer Support Confirmation', 'IND-CAP-03'),
    ('Service Recovery Customer Support Reconciliation', 'IND-CAP-03'),
    ('Service Resource Allocation', 'IND-CAP-01'),
    ('Service Station Sequencing', 'IND-CAP-07'),
    ('Servicing Review', 'CAP-CREDIT-002'),
    ('Session Timetable and Confirmation Evidence Preparation', 'IND-CAP-01'),
    ('Share Ingress Summary With Promoter', 'IND-CAP-22'),
    ('Shortage Auction and Custody Exception', 'CAP-CM-004'),
    ('Shortlisted Hooks Mapping', 'IND-CAP-01'),
    ('Shrink Investigation and Loss Evidence Audit', 'IND-CAP-27'),
    ('Shrink Investigation and Loss Interpretation', 'IND-CAP-27'),
    ('Shrink Investigation and Loss Resolution', 'IND-CAP-27'),
    ('Shrink Investigation Case File Tool Use', 'IND-CAP-27'),
    ('Shrink Variance Inventory Security Validation', 'IND-CAP-27'),
    ('Signed Sales Order Parsing', 'IND-CAP-20'),
    ('Signing Certificate Build Variant Application', 'IND-CAP-13'),
    ('Silver Table Key Join', 'IND-CAP-02'),
    ('SME Gap and', 'CAP-BANK-003'),
    ('Source Value Reconciliation', 'IND-CAP-01'),
    ('Sowing and Early Establishment', 'CAP-AFF-001'),
    ('Specify Genai Product Feature With', 'IND-CAP-16'),
    ('Spot-check First Line Last Line', 'IND-CAP-10'),
    ('Stability Study Follow-up and Artifact Completeness', 'CAP-004'),
    ('Stability Study Follow-up and Exception Readiness', 'CAP-004'),
    ('Stability Study Follow-up and Handoff Packet', 'CAP-004'),
    ('Statutory Contribution Filings L1 Execution', 'IND-CAP-12'),
    ('Statutory Contribution Filings L2 Execution', 'IND-CAP-12'),
    ('Statutory Contribution Filings L3 Execution', 'IND-CAP-12'),
    ('Statutory Contribution Filings L4 Execution', 'IND-CAP-12'),
    ('Statutory Contribution Filings L5 Execution', 'IND-CAP-12'),
    ('Statutory Contribution Filings Wage-base L1 Evidence', 'IND-CAP-12'),
    ('Statutory Contribution Filings Wage-base L2 Evidence', 'IND-CAP-12'),
    ('Statutory Contribution Filings Wage-base L3 Evidence', 'IND-CAP-12'),
    ('Statutory Contribution Filings Wage-base L4 Evidence', 'IND-CAP-12'),
    ('Statutory Contribution Filings Wage-base L5 Evidence', 'IND-CAP-12'),
    ('STEAM Maker-Lab Input Check', 'IND-CAP-08'),
    ('Steam Maker-lab Learning Cycle Evidence Audit', 'IND-CAP-08'),
    ('Steam Maker-lab Learning Cycle Routine Execution', 'IND-CAP-08'),
    ('Steam Maker-lab Learning Cycle Staff Coaching', 'IND-CAP-08'),
    ('Store Opening', 'IND-CAP-01'),
    ('Stream Parser Patch', 'IND-CAP-03'),
    ('Structure Shared Project Bins By', 'IND-CAP-03'),
    ('Structured Output Compliance', 'IND-CAP-09'),
    ('Structured Output Evidence Coaching', 'IND-CAP-09'),
    ('Structured Output Quality Review', 'IND-CAP-09'),
    ('Supplier Declaration and Packaging Tool Use', 'IND-CAP-29'),
    ('Supplier Declaration Esg Packaging Validation', 'IND-CAP-29'),
    ('Supplier ESG and Packaging Evidence Audit', 'IND-CAP-29'),
    ('Supplier Esg and Packaging Interpretation', 'IND-CAP-29'),
    ('Supplier Esg and Packaging Resolution', 'IND-CAP-29'),
    ('Supplier Proposal Promotion Plan Validation', 'IND-CAP-10'),
    ('Support Escalation and Case Interpretation', 'IND-CAP-22'),
    ('Support Escalation and Case Resolution', 'IND-CAP-22'),
    ('Support Ticketing System Tool Use', 'IND-CAP-21'),
    ('Surveillance Packet Preparation', 'CAP-CM-002'),
    ('Takedown Appeal Coaching', 'IND-CAP-17'),
    ('Target Variance Outlet Performance Validation', 'IND-CAP-14'),
    ('Teacher Development Closure Documentation', 'IND-CAP-07'),
    ('Teacher Development Facilitation Evidence Audit', 'IND-CAP-07'),
    ('Teacher Development Facilitation Evidence Preparation', 'IND-CAP-07'),
    ('Teacher Development Facilitation Quality Pattern Review', 'IND-CAP-07'),
    ('Teacher Development Facilitation Routine Execution', 'IND-CAP-07'),
    ('Teacher Development Facilitation Staff Coaching', 'IND-CAP-07'),
    ('Teacher Development Input Check', 'IND-CAP-07'),
    ('Tenant and Owner Property Intake Validation', 'CAP-REF-05'),
    ('Tenant and Owner Property Quality Review', 'CAP-REF-05'),
    ('Tenant and Owner Property Standards Coaching', 'CAP-REF-05'),
    ('Test AI Security Abuse Path', 'IND-CAP-15'),
    ('Test AI Security Abuse Quality Improvement', 'IND-CAP-15'),
    ('Test Feed Preview for Missing', 'IND-CAP-04'),
    ('Ticket Tiers Inventory Caps Configuration', 'IND-CAP-21'),
    ('Ticket/refund Position Communicated Release', 'IND-CAP-12'),
    ('TNA and Transfer- Tracker Evidence Preparation', 'IND-CAP-12'),
    ('Track Editorial Review Status Playlist', 'IND-CAP-23'),
    ('Trade Back-office Enrichment and Exception', 'CAP-CM-001'),
    ('Trade Promotion Execution Exceptions Resolution', 'IND-CAP-15'),
    ('Trade Promotion Execution Quality Evidence Audit', 'IND-CAP-15'),
    ('Trade Promotion Execution Triggers Interpretation', 'IND-CAP-15'),
    ('Train Deep Learning Model Candidate', 'IND-CAP-08'),
    ('Train Deep Learning Model Quality Improvement', 'IND-CAP-08'),
    ('Translate Manager People-advisory Requests L1 Evidence', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L1 Execution', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L2 Evidence', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L2 Execution', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L3 Evidence', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L3 Execution', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L4 Evidence', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L4 Execution', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L5 Evidence', 'IND-CAP-17'),
    ('Translate Manager People-advisory Requests L5 Execution', 'IND-CAP-17'),
    ('Translate Workforce Scenarios Accountable L1 Evidence', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L1 Execution', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L2 Evidence', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L2 Execution', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L3 Evidence', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L3 Execution', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L4 Evidence', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L4 Execution', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L5 Evidence', 'IND-CAP-20'),
    ('Translate Workforce Scenarios Accountable L5 Execution', 'IND-CAP-20'),
    ('Trigger Automation Suite Against Selected', 'IND-CAP-16'),
    ('Tutoring Case Review Evidence Preparation', 'IND-CAP-16'),
    ('Tutoring Routing Input Check', 'IND-CAP-16'),
    ('Tutoring Routing Standards and Evidence Audit', 'IND-CAP-16'),
    ('Tutoring Routing Standards and Staff Coaching', 'IND-CAP-16'),
    ('Tutoring Routing Work Loop Routine Execution', 'IND-CAP-16'),
    ('Unclean Unit Key Issue Resolution', 'IND-CAP-05'),
    ('Unrecorded Damage/Fuel Resolution', 'IND-CAP-13'),
    ('Update Artist Marketing Plan With', 'IND-CAP-23'),
    ('Update Attendance Status After Manual', 'IND-CAP-22'),
    ('Update Benefits Eligibility and L1 Evidence', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L1 Execution', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L2 Evidence', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L2 Execution', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L3 Evidence', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L3 Execution', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L4 Evidence', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L4 Execution', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L5 Evidence', 'IND-CAP-11'),
    ('Update Benefits Eligibility and L5 Execution', 'IND-CAP-11'),
    ('Update Cut Report With Affected', 'IND-CAP-06'),
    ('Update Seat Baggage/Boarding', 'IND-CAP-14'),
    ('Upstream Source Assets Transformation Input', 'IND-CAP-13'),
    ('User Trust Signal Capture', 'IND-CAP-17'),
    ('Vaccine Lot QC Temperature-excursion Artifact', 'CAP-006'),
    ('Vaccine Lot QC Temperature-excursion Exception', 'CAP-006'),
    ('Vaccine Lot QC Temperature-excursion Handoff Packet', 'CAP-006'),
    ('Valet Item Safety Resolution', 'IND-CAP-06'),
    ('Validated Admissions File Review Evidence Preparation', 'IND-CAP-25'),
    ('Validated Education MIS Report Evidence Preparation', 'IND-CAP-26'),
    ('Valuation and Asset Pack Intake Validation', 'CAP-REF-10'),
    ('Valuation and Asset Pack Quality Review', 'CAP-REF-10'),
    ('Valuation and Asset Pack Standards Coaching', 'CAP-REF-10'),
    ('Vendor Commercial and Promotion Evidence Audit', 'IND-CAP-10'),
    ('Vendor Commercial and Promotion Interpretation', 'IND-CAP-10'),
    ('Vendor Commercial and Promotion Resolution', 'IND-CAP-10'),
    ('Vendor Gap Budget Mismatch Resolution', 'IND-CAP-09'),
    ('Vendor No-show Delegate Flow Resolution', 'IND-CAP-10'),
    ('Vendor Scorecard and Promotion Tool Use', 'IND-CAP-10'),
    ('Verified Boarding Manifest Vessel Release', 'IND-CAP-14'),
    ('Verified Credential Issuance Review Evidence', 'IND-CAP-19'),
    ('Verify Artwork Dimensions Explicit-content Flag', 'IND-CAP-04'),
    ('Vertical AI Guardrail Setup', 'IND-CAP-18'),
    ('Visitor Query Routing Resolution', 'IND-CAP-01'),
    ('Vocational Batch Alignment Standards Evidence Audit', 'IND-CAP-09'),
    ('Vocational Batch Alignment Standards Staff Coaching', 'IND-CAP-09'),
    ('Vocational Batch Alignment Work Routine Execution', 'IND-CAP-09'),
    ('Vocational Batch Input Check', 'IND-CAP-09'),
    ('Water Transport Operations', 'IND-CAP-14'),
    ('Wellness Appointment Error Resolution', 'IND-CAP-06'),
    ('Wellness Leisure Facility Services Capture', 'IND-CAP-06'),
    ('Wellness Leisure Facility Services Confirmation', 'IND-CAP-06'),
    ('Wellness Leisure Facility Services Reconciliation', 'IND-CAP-06'),
    ('Work-Front Readiness', 'CIE-CAP-001'),
    ('Worker Deployment L1 Evidence Review', 'IND-CAP-05'),
    ('Worker Deployment L1 Execution', 'IND-CAP-05'),
    ('Worker Deployment L2 Evidence Review', 'IND-CAP-05'),
    ('Worker Deployment L2 Execution', 'IND-CAP-05'),
    ('Worker Deployment L3 Evidence Review', 'IND-CAP-05'),
    ('Worker Deployment L3 Execution', 'IND-CAP-05'),
    ('Worker Deployment L4 Evidence Review', 'IND-CAP-05'),
    ('Worker Deployment L4 Execution', 'IND-CAP-05'),
    ('Worker Deployment L5 Evidence Review', 'IND-CAP-05'),
    ('Worker Deployment L5 Execution', 'IND-CAP-05'),
    ('Wrong Layout Menu Shortage Resolution', 'IND-CAP-09'),
    ('Wrong Order Allergen Miss Resolution', 'IND-CAP-07'),
    ('Wrong Refund Rule/Resolution', 'IND-CAP-12')
  ) AS pairs(skill_name, cap_code)
WHERE s.name = pairs.skill_name
  AND c.code = pairs.cap_code
  AND NOT EXISTS (
    SELECT 1 FROM public.skill_capability_mapping scm2 
    WHERE scm2.skill_id = s.id AND scm2.capability_id = c.id
  );
