-- Seed data for industries table
-- Populated with all 35 industry categories for SkillPassport career guidance

INSERT INTO public.industries (industry_id, name, description, is_active, created_at, updated_at)
VALUES
  ('IND001', 'Agriculture, Forestry & Fishing', 'Cultivation of crops, livestock farming, forestry management, and fishing operations including aquaculture and sustainable agriculture practices.', true, NOW(), NOW()),
  ('IND002', 'Mining, Metals & Minerals', 'Extraction and processing of metallic ores, minerals, and gemstones. Includes mining operations, mineral refining, and metal production facilities.', true, NOW(), NOW()),
  ('IND003', 'Oil, Gas & Petrochemicals', 'Exploration, extraction, refining, and distribution of crude oil and natural gas. Includes petrochemical manufacturing and downstream operations.', true, NOW(), NOW()),
  ('IND004', 'Utilities, Power & Water', 'Generation, distribution, and supply of electricity, water, and gas services. Includes renewable energy utilities and water treatment facilities.', true, NOW(), NOW()),
  ('IND005', 'Chemicals & Advanced Materials', 'Manufacturing of chemical compounds, polymers, specialty chemicals, and advanced materials including composites and nanotech applications.', true, NOW(), NOW()),
  ('IND006', 'Construction, Infrastructure & Engineering', 'Design and construction of buildings, roads, bridges, and infrastructure projects. Includes civil engineering, project management, and facility development.', true, NOW(), NOW()),
  ('IND007', 'Industrial Manufacturing', 'Production of machinery, equipment, and industrial goods. Includes manufacturing plants, factories, and heavy equipment production facilities.', true, NOW(), NOW()),
  ('IND008', 'Automotive, Mobility & EV', 'Manufacturing and design of automobiles, commercial vehicles, electric vehicles, and mobility solutions. Includes automotive components and EV technology.', true, NOW(), NOW()),
  ('IND009', 'Aerospace, Defense & Space', 'Design and manufacturing of aircraft, defense systems, aerospace components, and space exploration technology. Includes aviation and satellite operations.', true, NOW(), NOW()),
  ('IND010', 'Transportation, Logistics & Supply Chain', 'Transportation services, warehouse management, supply chain optimization, and logistics operations including freight, shipping, and distribution networks.', true, NOW(), NOW()),
  ('IND011', 'Wholesale & Distribution', 'Distribution of goods to retailers and businesses. Includes wholesale trading, distribution centers, and supply chain intermediaries.', true, NOW(), NOW()),
  ('IND012', 'Retail, Consumer Goods & E-commerce', 'Retail stores, online shopping platforms, and consumer goods distribution. Includes e-commerce, omnichannel retail, and consumer product sales.', true, NOW(), NOW()),
  ('IND013', 'Banking, Capital Markets & Payments', 'Financial institutions, banking services, investment management, stock exchanges, and payment systems. Includes digital banking and fintech.', true, NOW(), NOW()),
  ('IND014', 'Insurance', 'Insurance services including life, health, property, casualty, and specialty insurance. Includes insurance underwriting and claims management.', true, NOW(), NOW()),
  ('IND015', 'Real Estate & Facilities', 'Property development, real estate transactions, property management, and facility services including commercial and residential real estate.', true, NOW(), NOW()),
  ('IND016', 'Healthcare Providers & Services', 'Hospitals, clinics, medical practices, diagnostic centers, and healthcare delivery services. Includes telemedicine and healthcare support services.', true, NOW(), NOW()),
  ('IND017', 'Pharma, Biotech & MedTech', 'Pharmaceutical manufacturing, biotechnology research, medical device development, and drug discovery. Includes clinical trials and healthcare innovation.', true, NOW(), NOW()),
  ('IND018', 'Education & Skilling', 'Educational institutions, online learning platforms, vocational training, and skill development programs. Includes K-12, higher education, and corporate training.', true, NOW(), NOW()),
  ('IND019', 'Information Technology, Software & Data', 'Software development, IT services, cloud computing, data analytics, and technology solutions. Includes SaaS, enterprise software, and IT consulting.', true, NOW(), NOW()),
  ('IND020', 'Telecommunications & Connectivity', 'Telecom services, broadband providers, cellular networks, and communications infrastructure. Includes 5G, ISPs, and connectivity solutions.', true, NOW(), NOW()),
  ('IND021', 'Media, Entertainment & Gaming', 'Film, television, streaming services, music production, gaming, and digital content creation. Includes sports media and entertainment platforms.', true, NOW(), NOW()),
  ('IND022', 'Hospitality, Travel & Tourism', 'Hotels, resorts, restaurants, tour operators, and travel services. Includes event management, leisure services, and tourism infrastructure.', true, NOW(), NOW()),
  ('IND023', 'Government, Public Sector & Smart Cities', 'Government agencies, public services, municipal administration, and smart city initiatives. Includes public policy and civic technology.', true, NOW(), NOW()),
  ('IND024', 'Legal, Consulting & Professional Services', 'Law firms, management consulting, accounting services, and professional advisory. Includes strategic consulting and business services.', true, NOW(), NOW()),
  ('IND025', 'Nonprofit, CSR & Social Impact', 'Nonprofit organizations, NGOs, charity services, and social impact initiatives. Includes corporate social responsibility and community development.', true, NOW(), NOW()),
  ('IND026', 'Food & Beverage', 'Food processing, beverage manufacturing, restaurants, food services, and culinary operations. Includes food safety and nutrition services.', true, NOW(), NOW()),
  ('IND027', 'Energy (Generation & Renewables)', 'Renewable energy generation including solar, wind, hydro, and biomass. Includes energy storage and sustainable power solutions.', true, NOW(), NOW()),
  ('IND028', 'Data & AI', 'Data science, artificial intelligence, machine learning, and advanced analytics. Includes AI research, data platforms, and intelligent automation.', true, NOW(), NOW()),
  ('IND029', 'Cybersecurity', 'Cybersecurity services, threat detection, data protection, and security infrastructure. Includes security consulting and compliance services.', true, NOW(), NOW()),
  ('IND030', 'Gaming', 'Video game development, esports, gaming platforms, and interactive entertainment. Includes game publishing and gaming technology.', true, NOW(), NOW()),
  ('IND031', 'Creator Economy', 'Content creation, influencer platforms, digital publishing, and creator services. Includes podcasting, streaming, and digital content monetization.', true, NOW(), NOW()),
  ('IND032', 'HR & Workforce Services', 'Human resources services, recruitment, staffing agencies, and talent management. Includes payroll, training, and workforce consulting.', true, NOW(), NOW()),
  ('IND033', 'Defense Manufacturing', 'Defense equipment manufacturing, military technology, and government defense contracting. Includes defense systems and secure manufacturing.', true, NOW(), NOW()),
  ('IND034', 'Sports', 'Sports management, fitness services, athletic events, and sports entertainment. Includes sports facilities, coaching, and sports technology.', true, NOW(), NOW()),
  ('IND035', 'Space Economy', 'Space exploration, satellite services, space technology, and commercial space ventures. Includes launch services and space-based applications.', true, NOW(), NOW());
