-- Generated from: Company Data for engg Team (1).xlsx
-- Recruiter IDs are set to NULL; recruiter emails are stored in created_by.
-- Salary values expressed as LPA were converted to annual INR integers.
-- Status mapping: Active -> open, On Hold -> on_hold, Closed -> closed, blank -> draft.
-- Non-date deadline notes (for example, "20 days") are stored in schedule_note.

BEGIN;

INSERT INTO public.opportunities (
  title,
  company_name,
  employment_type,
  location,
  mode,
  experience_required,
  skills_required,
  description,
  deadline,
  is_active,
  department,
  experience_level,
  salary_range_min,
  salary_range_max,
  status,
  requirements,
  responsibilities,
  benefits,
  applications_count,
  job_title,
  recruiter_id,
  created_by,
  schedule_note
) VALUES
  ('Solution Engineer', 'Flick Networks', 'Full-time', 'Remote', 'Offline', '3 Years', '["Solution Design", "Presales", "ERP", "API Integration", "XML", "JSON", "E-invoice", "EDI"]'::jsonb, 'Pre-Sales Experience 
Minimum 4+ years in Pre-Sales / Solution Engineer / Solution Consulting.
Should have handled client calls, demos, technical discussions and sales cycles.
ERP & Finance Knowledge
Understanding of ERP systems and finance processes.
Knowledge of AR/AP, invoicing and tax determination.
SAP / Oracle / Dynamics is an advantage.
API & Integration Skills
Good understanding of REST APIs, JSON and XML.
Hands-on experience with Postman.
Should understand ERP/API integration and data flow.
Solution Design & Documentation
Experience creating Solution Design Documents, architecture diagrams, RFP responses, scoping and effort estimates.
Should be able to convert customer requirements into a technical solution.
Client-Facing & UAT Experience
Excellent English communication and client-handling skills.
Experience defining UAT scope, test scenarios and acceptance criteria.
Should be comfortable explaining technical solutions to both technical and business stakeholders', '2026-09-10 00:00:00+00', TRUE, 'Tech', 'Senior Executive', 500000, 1300000, 'open', '["2+ years of Pre-Sales experience", "ERP knowledge/experience", "API Integration experience", "REST API, JSON & XML knowledge", "Client-facing experience – demos, technical discussions & requirement gathering"]'::jsonb, '["Pre-Sales: Handle client calls, understand requirements, and support the sales team.", "Product Demo: Conduct technical/product demos for clients.", "ERP Integration: Understand the client''s ERP system and integration requirements.", "API Integration: Work with REST APIs, JSON, XML and Postman for integration discussions.", "Solution Design: Prepare solution design documents, data flow and architecture."]'::jsonb, '["PF"]'::jsonb, 5, 'Solution Engineer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Support Lead', 'Flick Networks', 'Full-time', 'Remote', 'Offline', '5 Years', '["Technical Support / Service Delivery – 5+ years", "Team Leadership – 2+ years in Lead/Manager role", "SLA & Ticket Management – P1/P2/P3", "triage & escalation", "API & Integration Support – REST API", "Webhooks", "Middleware", "Technical Troubleshooting – API errors", "HTTP codes", "XML/UBL validation", "SaaS / B2B Support – Enterprise client support", "Freshdesk / Jira Service Management"]'::jsonb, 'Technical Support Experience – 5+ years in technical support/service delivery, with 2+ years in a Lead/Manager role.
Team Management – Manage L1 & L2 Support teams, conduct performance reviews, 1:1s and capacity planning.
SLA & Ticket Management – Handle P1/P2/P3 tickets, SLA tracking, ticket triage and escalation management.
API & Technical Knowledge – Experience with REST APIs, webhooks, middleware, API errors, HTTP codes and XML/UBL validation.
Support Operations – Build support processes, knowledge base, runbooks and escalation frameworks; monitor support KPIs like resolution time, ticket volume and CSAT.', '2026-08-29 00:00:00+00', TRUE, 'Tech', 'Senior / Head', 600000, 1500000, 'open', '["Technical Support Experience – 5+ years in technical support/service delivery, with 2+ years in a Lead/Manager role.", "Team Management – Manage L1 & L2 Support teams"]'::jsonb, '["Manage Support Team – Lead and manage L1 & L2 Support Engineers.", "Ticket Management – Monitor tickets, prioritize P1/P2/P3 issues, and ensure timely resolution.", "SLA Management – Define and track response and resolution SLAs.", "Technical Escalation – Handle escalations to Product/Engineering and ensure issues are properly resolved.", "API Support – Understand REST APIs, webhooks, HTTP errors, API logs and XML/UBL validation issues.", "Client Support – Communicate with enterprise clients and provide updates on technical issues."]'::jsonb, '["PF"]'::jsonb, 4, 'Support Lead', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Dynamics365 F&O Technical Consultant', 'Flick Networks', 'Full-time', 'Remote', 'Offline', '4 Years', '["Dynamic 365", "X++ Development", "Dynamics AX 2012", "e-invoicing"]'::jsonb, 'Position: Dynamics 365 - F&O technical Consultant
Requirement:
Must have experience in X++ development
Must have work experience in Dynamics AX 2012
Must have experience doing e-invoicing integration
Joining should be within 1 month max', '2026-07-29 00:00:00+00', FALSE, 'Tech', 'Mid Level', 700000, 1300000, 'closed', '["Dynamics 365 - F&O Technical Consultant", "Must have experience in X++ development"]'::jsonb, '["Must have experience in X++ development", "Must have work experience in Dynamics AX 2012", "Must have experience doing e-invoicing integration"]'::jsonb, '["PF"]'::jsonb, 5, 'Dynamics365 F&O Technical Consultant', NULL, 'varalakshmi@rareminds.in', NULL),
  ('L1 Support Analyst', 'Flick Networks', 'Full-time', 'Remote', 'Offline', '1 Year', '["Technical Support / Helpdesk – 1–2 years experience", "Ticket Management – Freshdesk / Zendesk / Jira Service Management", "Basic API & Integration Knowledge – APIs", "web portals", "software integrations", "Troubleshooting – Login", "access", "invoice status", "configuration issues", "Customer Support – Good written English & client communication", "SLA Management – Ticket prioritization and timely response", "Basic XML / JSON Knowledge – Advantage", "SaaS Support – Experience in a technology/SaaS environment", "ERP / eInvoicing Knowledge"]'::jsonb, 'Technical Support Experience 
1–2 years experience in Technical Support / Helpdesk / Customer Support.
SaaS or technology company experience is preferred.
Basic Technical Knowledge
Understanding of web portals, APIs and software integrations.
Basic knowledge of XML / JSON is an advantage.
Ticket & Helpdesk Management
Experience handling support tickets, ticket categorization, SLA and follow-ups.
Freshdesk, Zendesk, Jira Service Management or similar tools are preferred.
Customer Communication 
Good written English.
Should be comfortable communicating with enterprise clients and handling queries professionally.
Troubleshooting & Escalation
Able to resolve basic issues like login, password, MFA, user access, invoice status and configuration.', '2026-06-29 00:00:00+00', FALSE, 'Tech', 'Junior Level', 300000, 600000, 'closed', '["1–2 years experience in Technical Support / Helpdesk / Customer Support.", "SaaS or technology company experience is preferred."]'::jsonb, '["Handle Support Tickets – Receive, categorize, and respond to client tickets within SLA.", "Resolve Basic Issues – Handle login, password, MFA, user access, invoice status, and basic configuration issues.", "Collect Issue Details – Gather error messages, screenshots, invoice IDs, and ERP details before escalation.", "Escalate to L2 – Escalate API, Peppol, XML/UBL, ERP, and complex technical issues to L2.", "Follow Up with Clients – Keep clients updated and confirm the issue is resolved.", "Maintain Ticket Records – Update ticket status, notes, actions, and resolutions in the CRM.", "Follow Runbooks – Use the knowledge base and documented processes to resolve issues.", "Identify Repeated Issues – Report recurring problems to the Support Lead for process/runbook improvements."]'::jsonb, '["PF"]'::jsonb, 4, 'L1 Support Analyst', NULL, 'varalakshmi@rareminds.in', NULL),
  ('BSV', 'SCV QA Executive', 'Full-time', 'Ambernath', 'Offline', '2 years', '["GMP & CSV Compliance", "Strong knowledge of GAMP 5", "Data Integrity", "21 CFR Part 11", "EU GMP Annex 11"]'::jsonb, 'CSV Experience
2–5 years of hands-on Computer System Validation experience.
GMP & CSV Compliance
Strong knowledge of GAMP 5
Data Integrity
21 CFR Part 11
EU GMP Annex 11
Knowledge of Data Integrity / ALCOA+
Electronic records and e-signature compliance.
QA Documentation & Validation
Experience preparing/executing CSV validation documents.
Periodic review and requalification of computerized systems.
QA Quality Systems
Hands-on experience with Change Control, CAPA, Deviations, Risk Assessment & Investigations.', NULL, TRUE, 'Production', 'Senior Executive', 300000, 600000, 'open', '["CSV Experience", "2–5 years of hands-on Computer System Validation experience.", "GMP & CSV Compliance", "Strong knowledge of GAMP 5", "21 CFR Part 11", "EU GMP Annex 11", "Data Integrity"]'::jsonb, '["Computer System Validation (CSV) – Plan, execute, and document validation activities for computerized systems.", "Validation Documentation – Prepare and maintain CSV documents as per GAMP 5.", "Regulatory Compliance – Ensure systems comply with 21 CFR Part 11 and EU GMP Annex 11.", "Data Integrity – Ensure ALCOA+, electronic records, and e-signatures are properly maintained.", "Periodic Review – Conduct periodic review and requalification of computerized systems.", "Change Control & CAPA – Manage Change Controls, CAPA, Deviations, and Investigations."]'::jsonb, '["PF"]'::jsonb, 10, 'BSV', NULL, 'varalakshmi@rareminds.in', '20 days'),
  ('AI Developer', 'Talpro', 'Contract', 'Remote', 'Offline', '5 Years', '["1. Langchain", "2. Aws lambda", "Sns", "sqs", "api gateway", "3. Fast api", "4. Pg vector database", "5. Postman", "6. Git"]'::jsonb, 'Python + AI/ML 
5+ years Python experience with AI/ML.
TensorFlow, PyTorch, Scikit-learn.
LLM / RAG / LangChain 
Hands-on experience with LLMs, RAG and LangChain.
AWS Bedrock experience is highly preferred/required.
AWS Services 
Lambda, SNS, SQS, API Gateway
AWS Bedrock, S3, SageMaker, ECS/EKS, IAM.
FastAPI & Backend Development 
Strong experience building REST APIs using FastAPI.
Microservices and API integration knowledge.
Vector Database 
Hands-on experience with PGVector / PostgreSQL for AI/RAG applications.', '2026-09-10 00:00:00+00', TRUE, 'Tech', 'Senior leave', 600000, 1200000, 'open', '["Python + AI/ML", "5+ years Python experience with AI/ML.", "TensorFlow, PyTorch, Scikit-learn.", "LLM / RAG / LangChain", "Hands-on experience with LLMs, RAG and LangChain.", "AWS Bedrock experience is highly preferred/required.", "AWS Services"]'::jsonb, '["Experience: 5+ years in Python development with AI/ML.", "LangChain & LLM: Hands-on experience with LangChain, LLMs and RAG.", "AWS: Strong experience with AWS Bedrock, Lambda, SNS, SQS & API Gateway.", "Backend: Strong FastAPI experience and REST API development.", "Database: Hands-on experience with PostgreSQL / PGVector.", "API Testing: Experience with Postman.", "DevOps: Good knowledge of Git, Docker, Kubernetes and CI/CD.", "AI/ML: Knowledge of TensorFlow/PyTorch/Scikit-learn, NLP and ML models.", "Data Engineering: Exposure to ETL, Airflow/Spark/AWS Glue."]'::jsonb, '["PF"]'::jsonb, 8, 'AI Developer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Domino Platform L3 Support', 'Talpro', 'Contract', 'Remote', 'Offline', '3 Years', '["Domino Data Lab", "L3 Production Support & Troubleshooting", "Kubernetes & Docker", "Python / R", "GitHub / GitLab / Bitbucket", "AWS / SageMaker / Azure ML", "AI/ML & Data Science Platform Support", "Incident Management & RCA"]'::jsonb, 'Domino Data Lab  – Mandatory
Strong hands-on experience with the Domino Data Lab platform.
Experience supporting data science/AI-ML platforms.
L3 Production Support 
Strong L3 support and troubleshooting experience.
Incident management, RCA, permanent fixes and SLA/KPI handling.
Kubernetes & Docker 
Hands-on experience with Kubernetes and Docker.
Container/platform troubleshooting is important.
Python/R + Git
Experience supporting Python/R environments, notebooks and data science workspaces.
GitHub/GitLab/Bitbucket experience.
Cloud & AI/ML Platforms
Experience with AWS / SageMaker / Azure ML.
Understanding of ML workflows such as model training, execution and deployment.
Experience', '2026-07-12 00:00:00+00', TRUE, 'Tech', 'Mid Level', NULL, NULL, 'on_hold', '["Domino Data Lab – Hands-on experience is mandatory.", "L3 Production Support – Strong troubleshooting, incident management and RCA experience.", "Kubernetes & Docker – Hands-on container/platform support experience.", "Python / R + Git – Experience supporting data science environments and ML workflows.", "Cloud – AWS / SageMaker or Azure ML experience.", "Experience – 7–10 years overall, with 4+ years in Data Science / AI/ML / Analytics platform support.", "Pharma/Life Sciences – Experience in GxP or regulated environments is preferred."]'::jsonb, '["L3 Support – Handle complex production issues escalated from L1/L2 teams.", "Domino Platform Support – Manage and maintain the Domino Data Lab platform.", "Troubleshooting & RCA – Troubleshoot platform issues and identify the root cause."]'::jsonb, '["PF"]'::jsonb, 2, 'Domino Platform L3 Support', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Unix / C++ Developer', 'Untengle Tech', 'Contract', 'Chennai', 'Online/ offline', '5 Years', '["C++ Development", "UNIX / Linux", "Shell Scripting – Bash / Korn / POSIX", "HSM Integration – Thales / SafeNet / Utimaco", "PKCS#11", "Cryptography & Encryption", "Digital Signing & Key Management", "API Integration", "System Automation & Monitoring"]'::jsonb, 'C++ Development 
Strong hands-on experience in C++ application development on UNIX/Linux systems.
UNIX / Shell Scripting 
Good knowledge of UNIX/Linux.
Experience with Bash, Korn Shell or POSIX Shell scripting.
Cryptography & Security 
Experience with cryptographic protocols, data encryption and security.
HSM Integration 
Hands-on experience with Hardware Security Modules (HSM) such as Thales, SafeNet or Utimaco.
Knowledge of PKCS#11 or vendor APIs.
System Automation & Monitoring
Experience in automation, batch processing, data manipulation and system monitoring using UNIX scripts.', '2026-07-18 00:00:00+00', TRUE, 'Tech', 'Junior Level', 800000, 1200000, 'on_hold', '["C++ Development", "Strong hands-on experience in C++ application development on UNIX/Linux systems.", "UNIX / Shell Scripting", "Good knowledge of UNIX/Linux.", "Experience with Bash, Korn Shell or POSIX Shell scripting."]'::jsonb, '["C++ Development – Develop and maintain C++ applications for UNIX-based systems.", "UNIX Scripting – Create and maintain Bash/Korn/POSIX shell scripts for automation.", "System Automation – Automate batch processing, data manipulation and system monitoring.", "Security & Encryption – Implement cryptographic protocols to protect sensitive data.", "HSM Integration – Configure and integrate HSMs such as Thales, SafeNet or Utimaco.", "Key Management – Handle secure key generation, storage and digital signing.", "API Integration – Work with PKCS#11 and HSM vendor APIs.", "Troubleshooting – Identify and resolve application, UNIX and security-related issues."]'::jsonb, '["PF,ESI"]'::jsonb, 4, 'Unix / C++ Developer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Java Developer', 'Untengle Tech', 'Contract', 'Pune', 'Online/ offline', '8 Years', '["Core Java 21+", "Multithreading & Concurrency", "Microservices – Core Java without Spring/Spring Boot", "JUnit / Unit Testing", "Java Application Development", "Docker", "Kubernetes", "Client/Stakeholder Management"]'::jsonb, 'Java Experience 
9+ years of strong Java development experience.
Expert-level Core Java 21+; Java 25 LTS exposure is an advantage.
Core Java & Multithreading 
Strong hands-on experience in Core Java, multithreading and concurrency.
Microservices 
Experience building microservices using Core Java without Spring/Spring Boot.
Unit Testing
Strong experience with JUnit and unit testing practices.
Docker & Kubernetes
Knowledge of Docker and Kubernetes as secondary skills.
Important Conditions', '2026-07-25 00:00:00+00', TRUE, 'Tech', 'Mid Level', 800000, 1500000, 'on_hold', '["9+ years of Java experience", "Expert Core Java 21+ – Java 25 LTS is an advantage.", "Multithreading & Concurrency – Strong hands-on experience.", "Microservices using Core Java – Without Spring/Spring Boot", "JUnit / Unit Testing – Good experience.", "Docker & Kubernetes – Secondary skills.", "Individual Contributor – Direct client/stakeholder interaction."]'::jsonb, '["9+ years of Java experience", "Expert Core Java 21+ – Java 25 LTS is an advantage.", "Multithreading & Concurrency – Strong hands-on experience.", "Microservices using Core Java – Without Spring/Spring Boot", "JUnit / Unit Testing – Good experience.", "Docker & Kubernetes – Secondary skills.", "Individual Contributor – Direct client/stakeholder interaction."]'::jsonb, '["PF,ESI"]'::jsonb, 8, 'Java Developer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('AI Engineer', 'Untengle Tech', 'Contract', 'Bnagalore  / Pune / Hyd', 'Online/ offline', '10 Years', '["Python", "Generative AI (GenAI) & LLMs", "RAG (Retrieval-Augmented Generation)", "LangChain / LangGraph / Semantic Kernel – Any one", "REST APIs & API Integration", "Vector Databases", "Embeddings & Chunking", "Prompt Engineering", "Azure OpenAI / OpenAI APIs / AWS Bedrock – Any one", "Azure or AWS Cloud"]'::jsonb, 'Python – Strong hands-on experience.
GenAI & LLM – Experience building Generative AI / LLM applications.
RAG  – Hands-on experience developing Retrieval-Augmented Generation pipelines.
AI Framework – Any one of LangChain / LangGraph / Semantic Kernel.
REST APIs – API development and integration with enterprise applications.
Vector Databases – Experience with embeddings, chunking and vector search.
AI Cloud Platform – Any one: Azure OpenAI / OpenAI APIs / AWS Bedrock.
Cloud – Azure or AWS experience.
AI/ML Integration – Ability to integrate AI models into enterprise applications.', '2026-07-28 00:00:00+00', TRUE, 'Tech', 'Senior Level', 1800000, 2400000, 'on_hold', '["Python – Strong hands-on experience.", "GenAI & LLM – Experience building Generative AI / LLM applications.", "RAG  – Hands-on experience developing Retrieval-Augmented Generation pipelines."]'::jsonb, '["Develop AI Applications – Build AI-powered solutions for enterprise applications.", "GenAI / LLM Development – Develop and deploy Generative AI and LLM-based applications.", "Build RAG Solutions – Design and implement RAG pipelines using embeddings, chunking and vector databases.", "API Integration – Develop and integrate REST APIs to connect AI solutions with enterprise systems.", "AI Frameworks – Work with LangChain, LangGraph or Semantic Kernel.", "Cloud AI Integration – Integrate Azure OpenAI, OpenAI APIs or AWS Bedrock.", "Develop PoCs – Create Proof of Concepts and automation workflows for AI use cases."]'::jsonb, '["PF,ESI"]'::jsonb, 11, 'AI Engineer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Data Moduller', 'Untengle Tech', 'Contract', 'Delhi', 'Online/ offline', '10 years', '["Python + GenAI/LLM + RAG + LangChain/LangGraph/Semantic Kernel + REST API + Vector Database + Azure OpenAI/AWS Bedrock"]'::jsonb, 'Python 
Generative AI (GenAI) & LLMs 
RAG (Retrieval-Augmented Generation) 
LangChain / LangGraph / Semantic Kernel – Any one
REST APIs & API Integration
Vector Databases
Embeddings & Chunking
Prompt Engineering
Azure OpenAI / OpenAI APIs / AWS Bedrock – Any one
Azure or AWS Cloud', '2026-07-22 00:00:00+00', TRUE, 'Tech', 'Senior Level', 1500000, 1800000, 'on_hold', '["Generative AI (GenAI) & LLMs", "RAG (Retrieval-Augmented Generation)", "LangChain / LangGraph / Semantic Kernel – Any one"]'::jsonb, '["Vector Databases", "Embeddings & Chunking", "Prompt Engineering", "Azure OpenAI / OpenAI APIs / AWS Bedrock – Any one", "Azure or AWS Cloud"]'::jsonb, '["PF,ESI"]'::jsonb, 2, 'Data Moduller', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Senior Data Engineer', 'Teamlease - Simplify', 'Contract', 'Pune', 'Online/ offline', '4 Years', '["SQL + Python/PySpark", "Strong SQL / T-SQL / MS SQL / Stored Procedures.", "Experience with Python / PySpark.", "ETL/ELT & Data Pipelines"]'::jsonb, 'Azure Data Engineering 
Strong hands-on experience with Azure Data Factory, Azure Databricks, Azure Functions and Azure DevOps.
Data Warehouse & Data Lake 
Experience building and maintaining Data Warehouse / Data Lake.
Strong knowledge of Data Modelling, Dimensional Modelling and Schema Design.
SQL + Python/PySpark 
Strong SQL / T-SQL / MS SQL / Stored Procedures.
Experience with Python / PySpark.
ETL/ELT & Data Pipelines 
Experience designing ETL/ELT pipelines and data integration.
Knowledge of SSIS, REST APIs, Webhooks and batch/streaming pipelines.
Team Leadership 
Experience leading a technical data engineering team, mentoring engineers and coordinating with stakeholders.', '2026-07-21 00:00:00+00', TRUE, 'IT Services', 'Junior Level', 1200000, 1500000, 'on_hold', '["Data Warehouse & Data Lake", "Experience building and maintaining Data Warehouse / Data Lake.", "Strong knowledge of Data Modelling, Dimensional Modelling and Schema Design."]'::jsonb, '["Lead Data Engineering Team – Manage, mentor and guide the data engineering team.", "Build Data Pipelines – Design and maintain scalable ETL/ELT data pipelines.", "Azure Data Platform – Work on Azure Data Factory, Databricks, Azure Functions and Azure DevOps.", "Data Warehouse & Data Lake – Develop and maintain the organization''s Data Warehouse and Data Lake.", "Data Modelling – Design data models, schemas and dimensional models for reporting and analytics.", "Data Integration – Integrate data from different sources using APIs, Webhooks, SSIS and automated pipelines."]'::jsonb, '["PF,ESI"]'::jsonb, 5, 'Senior Data Engineer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('M 365 Senior Engineer', 'Teamlease - Simplify', 'Contract', 'Pune', 'Online/ offline', '6 Years', '["Microsoft 365 Suite", "Microsoft Intune – Device & Application Management", "Exchange Online", "SharePoint & Microsoft Teams", "Entra ID / Azure AD & Active Directory", "Microsoft Defender – Endpoint / Office / Identity", "PowerShell Scripting & Automation", "Azure AD Connect", "SSO & MFA", "Purview & Privileged Identity Management (PIM)", "DNS", "DHCP", "GPO & Networking"]'::jsonb, 'Microsoft 365 – Mandatory 
Minimum 2–3 years experience in designing, configuring and supporting M365.
Exchange Online, SharePoint, Teams, OneDrive, Purview.
Intune & Device Management 
Hands-on Microsoft Intune experience.
Windows device and application management.
Microsoft Security 
Defender for Endpoint, Defender for Office, Defender for Identity.
Knowledge of security, compliance and least-privilege access.
Azure AD / Active Directory 
Azure AD/Entra ID, AD Connect, Active Directory, DNS, DHCP, GPO, SSO and MFA.
PowerShell & Automation
PowerShell scripting for automation and process improvement.', '2026-07-28 00:00:00+00', TRUE, 'IT Services', 'Senior Level', 1200000, 1800000, 'on_hold', '["Minimum 2–3 years experience in designing, configuring and supporting M365.", "Exchange Online, SharePoint, Teams, OneDrive, Purview.", "Intune & Device Management", "Hands-on Microsoft Intune experience.", "Windows device and application management."]'::jsonb, '["Microsoft 365 Management – Configure, manage and support Exchange Online, SharePoint, Teams and OneDrive.", "Intune Management – Manage Windows devices, applications, policies and configurations through Microsoft Intune.", "Security & Compliance – Manage Defender, Purview, MFA, PIM and security policies to keep systems secure and compliant.", "Azure AD / Active Directory – Manage Entra ID/Azure AD, AD Connect, SSO, DNS, DHCP and GPOs.", "L2 Technical Support – Act as an escalation point for Service Desk and resolve complex M365/Modern Workplace issues."]'::jsonb, '["PF ESI"]'::jsonb, 4, 'M 365 Senior Engineer', NULL, 'varalakshmi@rareminds.in', NULL),
  ('Rewards Lead / Manager', 'BSV', 'Full-time', 'Mumbai', 'On-site', '5–8 yrs', '["Compensation & Benefits", "Total Rewards", "Rewards Management", "HR"]'::jsonb, 'Lead Rewards / Compensation & Benefits activities with focus on total rewards.', '2026-06-17 00:00:00+00', TRUE, 'Compensation & Benefits', 'Mid-Senior', 1000000, 1500000, 'on_hold', '["5–8 yrs C&B / Total Rewards experience"]'::jsonb, '["Manage compensation & benefits and rewards-related activities; stakeholder management and program execution."]'::jsonb, '["ESI, PF"]'::jsonb, 3, 'Rewards Lead / Manager', NULL, 'subiksha@rareminds.in', NULL),
  ('Store Manager', 'Titan Eye+', 'Full-time', 'Mathikere & Thanisandra, Bengaluru', 'On-site', '7–13 yrs', '["Retail Operations", "Store Management", "Team Management", "Sales", "Customer Service"]'::jsonb, 'Store management position for Titan Eye+ retail operations.', '2026-04-08 00:00:00+00', TRUE, 'Retail & Store Operations', 'Mid-Senior', 300000, 400000, 'open', '["7–13 yrs relevant store / retail management experience."]'::jsonb, '["Manage store operations, team, sales, customer service and store performance."]'::jsonb, '["ESI, PF"]'::jsonb, 0, 'Store Manager', NULL, 'subiksha@rareminds.in', NULL),
  ('D&C Executive', 'Teamlease - Simplify', 'Full-time', 'Pune', 'On-site', '3 yrs', '["HR Operations", "People Operations", "Employee Lifecycle", "Documentation"]'::jsonb, 'HR / People Operations role supporting day-to-day employee and HR processes.', '2026-08-17 00:00:00+00', TRUE, 'People Operations', 'Executive', 500000, 800000, 'on_hold', '["HR / People Operations experience; exact requirements not available."]'::jsonb, '["Support HR operations, employee lifecycle processes, documentation and related activities."]'::jsonb, '["ESI, PF"]'::jsonb, 0, 'D&C Executive', NULL, 'subiksha@rareminds.in', NULL),
  ('Data Quality Analyst', 'Teamlease - Simplify', 'Full-time', 'Pune', 'On-site', '5 yrs', '["Data Quality", "Data Engineering", "Data Validation", "Data Analysis"]'::jsonb, 'Data quality-focused position; candidates with Data Engineering backgrounds were evaluated for their actual data quality exposure.', '2026-08-20 00:00:00+00', TRUE, 'Data & Analytics', 'Mid-Level', 1000000, 1500000, 'open', '["Data Quality / Data Engineering experience with relevant data quality work."]'::jsonb, '["Monitor, validate and improve data quality; identify and resolve data issues."]'::jsonb, '["ESI, PF"]'::jsonb, 4, 'Data Quality Analyst', NULL, 'subiksha@rareminds.in', NULL),
  ('Marketing Communications Specialist / Marcom Specialist', 'Radiall', 'Full-time', 'Bengaluru', 'On-site', '3 yrs', '["3D Visualization", "2D Motion Graphics", "Adobe After Effects", "Marketing Communications"]'::jsonb, 'Marketing communications role with strong emphasis on visual communication and multimedia content.', '2026-08-31 00:00:00+00', TRUE, 'Marketing & Communications', 'Mid-Level', 600000, 900000, 'open', '["3D visualization, 2D motion graphics and After Effects are important."]'::jsonb, '["Develop marketing communication materials, visual content and multimedia assets."]'::jsonb, '["ESI, PF"]'::jsonb, 5, 'Marketing Communications Specialist / Marcom Specialist', NULL, 'subiksha@rareminds.in', NULL),
  ('Regional Sales Manager / Zonal Sales Manager', 'Deltax Broking', 'Full-time', 'Surat', 'On-site', '5–10+ yrs', '["B2B Sales", "Stock Broking", "Capital Markets", "Business Development", "Team Management"]'::jsonb, 'Regional / zonal B2B sales leadership role within stock broking / capital markets.', '2026-08-20 00:00:00+00', TRUE, 'Business Development', 'Mid-Senior', 300000, 400000, 'on_hold', '["5–10+ yrs mandatory; Stock Broking / Capital Markets experience."]'::jsonb, '["Drive regional sales, business development, client acquisition and team / territory performance."]'::jsonb, '["ESI, PF"]'::jsonb, 1, 'Regional Sales Manager / Zonal Sales Manager', NULL, 'subiksha@rareminds.in', NULL),
  ('Manager – Recycled Polyolefins Sales', 'Plastics For Change (PFC)', 'Full-time', 'Remote; preferably South India', 'Remote', '5 yrs', '["Recycled Polyolefins", "PP", "HDPE", "LDPE", "B2B Sales", "Business Development"]'::jsonb, 'Sales management role focused specifically on recycled polyolefins.', '2026-07-20 00:00:00+00', TRUE, 'Business Development', 'Managerial', 1000000, 1200000, 'on_hold', '["Experience with recycled PP, HDPE and/or LDPE; sales/business development background."]'::jsonb, '["Develop sales opportunities, manage customers and drive business for recycled polyolefin products."]'::jsonb, '["ESI, PF"]'::jsonb, 2, 'Manager – Recycled Polyolefins Sales', NULL, 'subiksha@rareminds.in', NULL),
  ('Tech Lead cum Technical Project Manager', 'Teamlease - Simplify', 'Full-time', 'Pune / Hyderabad / Bengaluru', 'Hybrid', '9–12 yrs', '["Core Java", "JVM Optimisation", "Low-Latency Coding", "Microservices", "Kubernetes", "REST", "MSSQL/Oracle", "DevOps", "Docker/Podman", "GCP/AWS"]'::jsonb, 'Technical leadership and project management role requiring strong Core Java and low-latency development expertise.', '2026-08-31 00:00:00+00', TRUE, 'IT', 'Senior / Lead', 1000000, 1200000, 'on_hold', '["9–12 yrs IT; 5–8 yrs Core Java; Java v25; Microservices; Kubernetes; REST; databases; DevOps; Docker/Podman; Cloud."]'::jsonb, '["Lead technical development, project execution, architecture / coding, performance optimisation and technical team coordination."]'::jsonb, '["ESI, PF"]'::jsonb, 0, 'Tech Lead cum Technical Project Manager', NULL, 'subiksha@rareminds.in', NULL),
  ('Quality Head', 'Nahata Plastics Pvt. Ltd.', 'Full-time', 'Kundli, Haryana', 'On-site', '10 yrs', '["QA", "QC", "Quality Laboratory", "Quality Systems", "Audits", "Polymer / Plastics Quality", "Customer Quality"]'::jsonb, 'Head of Quality for a plastic compounding / polymer manufacturing operation, leading QA, QC and laboratory functions.', '2026-08-31 00:00:00+00', TRUE, 'Quality', 'Senior / Head', 600000, 7, 'open', '["Plastic Compounding / Polymer Manufacturing; strong QA/QC leadership and quality systems experience."]'::jsonb, '["Lead QA/QC, quality laboratory, testing procedures, raw material & finished product quality, customer requirements and audits."]'::jsonb, '["ESI, PF"]'::jsonb, 1, 'Quality Head', NULL, 'subiksha@rareminds.in', NULL),
  ('Quality Engineer / Supplier Quality', 'Radiall', 'Full-time', 'Bengaluru', 'On-site', '5 yrs', '["Supplier Quality", "Process Audit", "Supplier Audit", "STR", "Quality Systems", "Supplier Management"]'::jsonb, 'Quality role focused on supplier quality and end-to-end supplier activities.', '2026-08-31 00:00:00+00', TRUE, 'Supplier Quality', 'Mid-Level', 800000, 1000000, 'open', '["Process Audit, Supplier Audit, STR and end-to-end supplier activities."]'::jsonb, '["Conduct process and supplier audits, manage supplier quality activities and support quality improvement."]'::jsonb, '["ESI, PF"]'::jsonb, 4, 'Quality Engineer / Supplier Quality', NULL, 'subiksha@rareminds.in', NULL),
  ('Assistant Manager', 'IMZ corporate Pvt Ltd', 'Full-time', 'Delhi', 'On-site', '5 -7 Yrs', '["Strong organizational and leadership skills.", "• Excellent vendor management and negotiation abilities."]'::jsonb, 'The role ensures
smooth day-to-day office operations, efficient workplace infrastructure management, vendor
coordination, and compliance with administrative and safety standards.', NULL, TRUE, 'Logistics', 'Mid-Level', 500000, 600000, 'on_hold', '["Office administrator ,Facility Management,vendor and service co ordinator, procurement"]'::jsonb, '["Manage office infrastructure, utilities, and workplace facilities across multiple", "locations."]'::jsonb, '["PF"]'::jsonb, 9, 'Assistant Manager', NULL, 'swetha@rareminds.in', 'July 1st week'),
  ('Corporate Gifting Sales Manager', 'Gagan Sayi Ventures India Pvt. Ltd.', 'Full-Time', 'Bangalore', 'On-site', '2–5+ yrs', '["B2B Sales", "Corporate Gifting", "Business Development", "Account Management", "Negotiation", "CRM", "Consultative Selling", "Client Relationship Management", "Promotional Merchandise", "Vendor Management"]'::jsonb, 'Results-driven B2B sales role focused on developing corporate gifting business, acquiring corporate clients and driving revenue through customized gifting solutions.', '2026-08-31 00:00:00+00', TRUE, 'Sales / Business Development', 'Mid-Level', 1500000, 1800000, 'open', '["Bachelor''s degree in Business, Marketing, Sales or related field; 2–5+ yrs B2B sales; corporate gifting, promotional merchandise, events, printing, branding, HR solutions or related industry preferred; proven target achievement; CRM/MS Office or Google Workspace."]'::jsonb, '["Generate leads through cold calling, networking, referrals and outbound sales; engage HR/Admin/Procurement/Marketing/Leadership teams; build pipeline; understand gifting requirements; prepare proposals and quotations; negotiate and close deals; coordinate sourcing, operations and fulfillment; manage key accounts; achieve sales targets; monitor market/competitor trends; maintain CRM; attend events/networking."]'::jsonb, '["ESI, PF"]'::jsonb, 4, 'Corporate Gifting Sales Manager', NULL, 'subiksha@rareminds.in', NULL),
  ('Head – Brand, Marketing & Outreach', 'Nettur Technical Training Foundation (NTTF)', 'Full-Time', 'Bangalore; extensive travel to Mumbai / Delhi', 'On-site', '8–12 yrs; minimum 5 yrs in education, skilling or social sector', '["Brand Management", "Marketing Communications", "Digital Marketing", "SEO", "Paid Media", "Google Ads", "Meta Ads", "YouTube", "Content Strategy", "PR", "Storytelling", "Agency Management", "Enrollment Marketing", "AI Tools", "CRM", "Analytics", "Outreach"]'::jsonb, 'Senior leadership role responsible for strengthening NTTF''s brand visibility and reputation, particularly across North India, while driving student outreach, enrollment growth, digital presence and ecosystem partnerships.', '2026-07-30 00:00:00+00', TRUE, 'Brand, Marketing & Outreach', 'Senior Leadership', 3000000, 4000000, 'open', '["8–12 yrs brand management/marketing communications/outreach; 5+ yrs education/skilling/social sector; enrollment/admissions growth; agency management; digital marketing; SEO; paid social; content strategy; analytics; AI fluency; strong storytelling; willingness to travel. Preferred: technical/vocational education, North India media relationships, vernacular/Hindi campaigns, CRM such as LeadSquared/HubSpot, team-building, MBA Marketing/related PG qualification."]'::jsonb, '["Own brand strategy and identity; manage branding/creative agencies; develop brand playbook and collateral; drive Tier 2/3 student outreach; own website, SEO and social media; run Google/Meta/YouTube campaigns; manage paid media budgets and CAC/ROI; build PR/media relationships; develop school/ITI/community partnerships; track enrollment funnel; create testimonials and impact stories; build alumni engagement; organise events; develop employer communication; align centre heads; create monthly brand/enrollment dashboard."]'::jsonb, '["ESI, PF"]'::jsonb, 3, 'Head – Brand, Marketing & Outreach', NULL, 'subiksha@rareminds.in', NULL),
  ('Business Development Executive', 'Flick', 'Full-Time', 'Remote', 'Remote', '1+ yr', '["B2B SaaS Sales", "Business Development", "EU Market", "Cold Outreach", "Lead Generation", "Prospecting", "Audit Firms", "ERP Vendors", "Client Acquisition"]'::jsonb, 'B2B SaaS business development role focused on acquiring clients in the European market through outbound sales and cold outreach.', '2026-07-30 00:00:00+00', TRUE, 'Sales / Business Development', 'Junior / Executive', NULL, NULL, 'open', '["1+ yr experience; mandatory B2B SaaS experience; EU market exposure; experience selling/outreach to EU clients, audit firms and ERP vendors."]'::jsonb, '["Conduct cold outreach to EU prospects; identify and qualify business opportunities; engage audit firms and ERP vendors; develop prospect pipeline; generate meetings/leads and support business growth."]'::jsonb, '["ESI, PF"]'::jsonb, 4, 'Business Development Executive', NULL, 'subiksha@rareminds.in', NULL),
  ('Country Manager – Senegal', 'Bharat Serums & Vaccines Ltd. (BSV)', 'Full-Time', 'Senegal', 'On-site', '15 years', '["Country Management", "International Business", "Pharmaceutical Sales", "Business Development", "Market Development", "Stakeholder Management"]'::jsonb, 'Country-level business leadership role responsible for managing and developing the Senegal market for BSV.', '2026-08-31 00:00:00+00', TRUE, 'International Business / Sales', 'Senior / Managerial', 3500, 4500, 'open', '["International business / country management / pharmaceutical sales experience; detailed original requirements not available in current data."]'::jsonb, '["Manage Senegal market operations; develop business and sales; manage local stakeholders/partners; drive market growth and business objectives."]'::jsonb, '["ESI, PF"]'::jsonb, 1, 'Country Manager – Senegal', NULL, 'subiksha@rareminds.in', NULL),
  ('Knowledge & CMDB Management', 'Teamlease - Simplify', 'Contract', 'Pune', 'On-site', NULL, '["ITSM", "ITIL", "Service Management", "Process Coordination", "Assignment Management", "Analytical Skills"]'::jsonb, 'Responsible for receiving, reviewing and analyzing assignments and ensuring process activities are completed as required.', '2026-08-20 00:00:00+00', TRUE, 'IT Service Management / Service Management', 'Mid-level', NULL, NULL, 'draft', '["ITSM/ITIL process knowledge; ability to analyze and manage assigned process activities."]'::jsonb, '["Receive and review assignments; analyze requirements; perform/coordinate process activities; ensure tasks are resolved/completed as per process requirements."]'::jsonb, '["ESI, PF"]'::jsonb, 2, 'Knowledge & CMDB Management', NULL, 'subiksha@rareminds.in', NULL),
  ('Inside Sales Representative(ISR)', 'Radiall', 'Full-Time', 'Bangalore', 'On-site', '5+ yrs', '["Inside Sales", "B2B Sales", "Lead Generation", "Customer Relationship Management", "Sales Coordination", "Communication Skills", "Negotiation", "CRM"]'::jsonb, 'The Inside Sales Representative will be responsible for generating and managing sales opportunities, engaging with customers, supporting the sales process, and coordinating with internal teams to achieve business targets.', '2026-09-15 00:00:00+00', TRUE, 'Sales / Business Development', 'Mid-level', 700000, 900000, 'open', '["Experience in inside sales, customer engagement, lead generation, sales coordination, and handling B2B customers. Strong communication and interpersonal skills are required."]'::jsonb, '["Generate and qualify leads, connect with prospective and existing customers, understand customer requirements, prepare quotations, follow up on sales opportunities, maintain customer relationships, and coordinate with internal sales and business teams."]'::jsonb, '["Pf"]'::jsonb, 4, 'Inside Sales Representative(ISR)', NULL, 'swetha@rareminds.in', NULL),
  ('Project Compliance Specialist', 'Teamlease - GE Vernova', 'Full-Time', 'Noida', 'On-site', '5-10 yrs', '["Project Compliance", "Documentation", "MS Excel", "Reporting", "Stakeholder Management", "Process Compliance", "Audit Coordination"]'::jsonb, 'Responsible for ensuring project compliance, documentation, process adherence, and coordination with internal and external stakeholders.', '2026-09-15 00:00:00+00', TRUE, 'Compliance and Regulatory', 'Senior / Managerial', 1000000, 1300000, 'open', '["Experience in compliance, project coordination, documentation, reporting, and stakeholder management."]'::jsonb, '["Monitor project compliance, maintain documentation, track compliance requirements, prepare reports, coordinate with stakeholders, and ensure timely closure of compliance-related activities."]'::jsonb, '["PF"]'::jsonb, 2, 'Project Compliance Specialist', NULL, 'swetha@rareminds.in', NULL),
  ('Integration Lead', 'Flick Network', 'Full-Time', 'Remote', 'Remote', '5+ yrs', '["REST APIs", "SOAP", "JSON", "XML", "Middleware", "API Integration", "MuleSoft", "Dell Boomi", "SAP Integration Suite", "Oracle Integration Cloud", "ERP Integration", "Accounts Payable", "Procurement"]'::jsonb, 'Lead and manage enterprise integration projects, designing and delivering end-to-end integrations between ERP, finance, procurement, and other enterprise applications.', '2026-09-10 00:00:00+00', TRUE, 'Technology / Engineering', 'Senior / Lead', 1000000, 1300000, 'open', '["8+ years of enterprise integration experience with a minimum of 3 end-to-end ERP or enterprise integrations delivered from discovery and design through production go-live."]'::jsonb, '["Lead integration discovery, solution design, development, testing, deployment, and production go-live. Coordinate with stakeholders and ensure successful delivery of enterprise integrations."]'::jsonb, '["PF"]'::jsonb, 4, 'Integration Lead', NULL, 'swetha@rareminds.in', NULL),
  ('Sales and Marketing', 'Nahata Plastics Pvt Ltd', 'Full-time', 'Delhi', 'Offline', '2+', '["* Experience with CRM software and sales analytics tools.", " Creative thinker with a proactive and problem-solving attitude.", " Understanding of market dynamics and customer behaviour in the technology sector"]'::jsonb, 'We are seeking a motivated Sales &amp; Marketing Executive to join our team and
drive the sales of our innovative 3D printing solutions in Kirti Nagar. This role is ideal for individuals
with a passion for technology sales, excellent communication skills, and a drive to succeed', '2026-08-31 00:00:00+00', TRUE, 'Sales', 'Executive', 400000, 400000, 'open', '["* Bachelor’s degree in Business Administration (BBA) and similar field (MBA in Sales &amp;", "Marketing preferred).", " Minimum 1 year of experience in sales and marketing, preferably in technology or industrial", "products. Freshers with relevant skills are welcome to apply"]'::jsonb, '["* Develop and execute sales strategies to achieve sales targets and expand customer base.", " Identify and pursue new business opportunities through market research and client", "prospecting.", " Build and maintain strong relationships with clients, understanding their needs and offering", "suitable 3D printing solutions"]'::jsonb, '["N/A"]'::jsonb, 36, 'Sales and Marketing', NULL, 'krishna@rareminds.in', NULL),
  ('Polymer Sales', 'Nahata Plastics Pvt Ltd', 'Full-time', 'Delhi', 'Offline', '10+', '["* Experience with CRM software and sales analytics tools.", " Creative thinker with a proactive and problem-solving attitude.", " Understanding of market dynamics and customer behaviour in the technology sector"]'::jsonb, 'We are seeking a motivated Sales &  Marketing Executive to join our team and
drive the sales of our innovative 3D printing solutions in Kundli. This role is ideal for individuals
with a passion for technology sales, excellent communication skills, and a drive to succeed', '2026-08-31 00:00:00+00', TRUE, 'Sales', 'Senior Executive', 1200000, 1200000, 'open', '["Minimum 8+ years of experience in Polymer Sales and Engineering Compounds"]'::jsonb, '["* Develop and execute sales strategies to achieve sales targets and expand customer base.", " Identify and pursue new business opportunities through market research and client", "prospecting.", " Build and maintain strong relationships with clients, understanding their needs and offering", "suitable 3D printing solutions"]'::jsonb, '["N/A"]'::jsonb, 6, 'Polymer Sales', NULL, 'krishna@rareminds.in', NULL),
  ('HR - Executive', 'Nahata Plastics Pvt Ltd', 'Full-time', 'Delhi', 'Offline', '1+', '["CRM", "Using Recruit Portal", "Excel", "Good Communication"]'::jsonb, 'We are Looking  for candidate who could help our Organization in hiring Labours and maitain a good relationship with the employees', '2026-08-31 00:00:00+00', TRUE, 'HR', 'Executive', 300000, 300000, 'open', '["MBA Fresher or Candidate who have eperience in recruiting labours and having good knowledge in labour laws"]'::jsonb, '["Recruitment, Employee Onbording and Attendence maintenance and Salary Part"]'::jsonb, '["N/A"]'::jsonb, 20, 'HR - Executive', NULL, 'krishna@rareminds.in', NULL),
  ('Front Desk cum Sales Cordinator', 'Nahata Plastics Pvt Ltd', 'Full-time', 'Delhi', 'Offline', '1+', '["* Good verbal communication skills in Hindi and English.", "* Basic knowledge of MS Office.", "* Good organizational and coordination skills.", "* Immediate joiners are preferred"]'::jsonb, NULL, '2026-08-31 00:00:00+00', FALSE, 'Sales', 'Executive', 200000, 200000, 'closed', '["MBA Freshers also fine", "0–1 years of experience in Front Desk, Reception, Sales Coordination, Administration, or Office Coordination.", "Good verbal communication skills in Hindi and English.", "Basic knowledge of MS Office"]'::jsonb, '["1. Manage the front desk and greet visitors professionally.", "2. Attend incoming calls and direct them to the concerned departments.", "3. Handle customer inquiries and provide basic information.", "4. Coordinate customer orders and maintain order records"]'::jsonb, '["N/A"]'::jsonb, 30, 'Front Desk cum Sales Cordinator', NULL, 'krishna@rareminds.in', NULL),
  ('GeM Bid & E-Commerce Executive', 'Nahata Plastics Pvt Ltd', 'Full-time', 'Delhi', 'Offline', '1+', '["GeM", "e-commerce", "tendering", "or government bidding"]'::jsonb, 'We are looking for a GeM Bid & E-Commerce Executive to manage Government e-Marketplace (GeM) activities, online bidding, product listings, order processing, and day-to-day e-commerce operations from our Kirti Nagar, Delhi office', '2026-08-31 00:00:00+00', TRUE, 'Sales', 'Executive', 400000, 420000, 'open', '["* Good knowledge of MS Excel, MS Word, and Google Sheets.", "Good communication, coordination, and follow-up skills.", "Strong attention to detail and ability to work under deadlines.", "Candidates with experience in government sales/tender management will be preferred."]'::jsonb, '["Manage and monitor the GeM (Government e-Marketplace) portal.", "Search, evaluate, and participate in relevant GeM bids and tenders.", "Prepare and submit technical and commercial bids within deadlines.", "Study tender documents, eligibility criteria, specifications, and terms & conditions.", "Prepare quotations, cost sheets, and required tender documentation."]'::jsonb, '["N/A"]'::jsonb, 2, 'GeM Bid & E-Commerce Executive', NULL, 'krishna@rareminds.in', NULL),
  ('Executive Electrical (Technical)', 'ITC', 'Full-time', 'Hyderabad', 'Offline', '9+', '["Maintenance of all utility equipments(Boiler", "Chiller", "Compressor and DG)"]'::jsonb, 'Responsible for electrical maintenance, troubleshooting, installation, and preventive maintenance of plant machinery and utility equipment in a food processing/FMCG environment. Coordinate with vendors and service providers, ensure machine uptime, safety, quality-system compliance, and minimize electrical maintenance costs', '2026-06-30 00:00:00+00', FALSE, 'Production', 'Executive', 700000, 700000, 'closed', '["Technical", "• Electrical and mechanical engineering concepts and their application", "• Machines and equipments’ designs, uses and maintenance", "• Plant and machine layouts", "• Spice product attributes and quality norms"]'::jsonb, '["• Assist in installation of new machines and equipment", "• Troubleshoot electrical problems in machines and equipment", "• Attend to periodic repair and maintenance of processing facility", "• Provide guidance to service provider staff in operating electrical, electronic and", "mechanical machines and equipment"]'::jsonb, '["ESI, PF"]'::jsonb, 8, 'Executive Electrical (Technical)', NULL, 'krishna@rareminds.in', NULL),
  ('NOC Engineer', 'Flightcase', 'Full-time', 'Remote', 'Online', '2+', '["Telecom domain knowledge", "NOC / Network Operations", "Basic networking and troubleshooting", "Understanding of telecom/network monitoring"]'::jsonb, 'Responsible for monitoring and supporting telecom/network operations in a 24×7 NOC environment, including rotational and night shifts. The role requires strong communication skills, telecom-domain knowledge, and coordination with the US team to ensure smooth network/service operations', '2026-02-20 00:00:00+00', FALSE, 'Operations', 'Senior Executive', 700000, 700000, 'closed', '["Experience: 1–5 years", "Education: Graduation completed; Engineering degree preferred", "Domain: Telecom / Networking", "Location: Pune – Work from Office", "Notice Period: Immediate joiners to maximum 15 days"]'::jsonb, '["1. Monitor and support telecom/network operations in a 24×7 NOC environment", "2. Troubleshoot and coordinate resolution of network/telecom-related issues", "3. Communicate and coordinate effectively with the US team/client", "4. Handle rotational and night-shift operations as per business requirements"]'::jsonb, '["ESI, PF"]'::jsonb, 15, 'NOC Engineer', NULL, 'krishna@rareminds.in', NULL),
  ('Sales Executive', 'Total Group', 'Full-time', 'Chennai', 'Offline', '2+', '["1.Warehousing Sales", "2.Logistics Sales", "3.Freight Forwarding", "4.Business Development", "5.Account Management"]'::jsonb, 'Responsible for driving sales and business development for the Warehousing Division, including developing existing accounts and acquiring new customers and business opportunities. Lead and motivate the sales team while developing innovative and sustainable warehousing solutions for clients.', '2026-03-20 00:00:00+00', FALSE, 'Sales', 'Senior Executive', 500000, 500000, 'closed', '["Experience: 2–6 years", "Industry: Logistics / Freight Forwarding", "Function: Sales / Business Development", "Location: Mumbai – near Masjid Ali Metro Station", "Education: Diploma/Degree in Freight Forwarding, Logistics & Supply Chain Management or equivalent"]'::jsonb, '["Develop and lead the Inside Sales and Field Sales teams", "Maintain and develop existing customer accounts", "Identify and acquire new customers and business opportunities", "Drive sales and achieve team/business targets"]'::jsonb, '["ESI, PF"]'::jsonb, 10, 'Sales Executive', NULL, 'krishna@rareminds.in', NULL),
  ('Tower Co-Ordinator', 'Aanya Groups', 'Full-time', 'Thane', 'Offline', '4+', '["1.High-Rise Residential Construction", "2.RCC / Structural Works", "3.Finishing Works", "4.MEP Coordination", "5.Tower Execution"]'::jsonb, 'Responsible for end-to-end execution and management of an assigned residential tower, from RCC structure through finishing and handover. Coordinate with contractors, consultants, architects, structural and MEP teams while ensuring project quality, timelines, safety, and cost control.', '2026-03-30 00:00:00+00', FALSE, 'Operations', 'Executive', 600000, 600000, 'closed', '["Experience: 4–6 years", "Education: BE/B.Tech in Civil Engineering", "Location: Thane", "Project: Luxury High-Rise Residential"]'::jsonb, '["1.Lead construction activities for the assigned tower from structure to finishing and handover", "2.Coordinate with contractors, consultants, architects, structural and MEP teams", "3.Prepare and monitor daily/weekly tower execution plans", "4.Track project milestones and ensure timely completion"]'::jsonb, '["N/A"]'::jsonb, 6, 'Tower Co-Ordinator', NULL, 'krishna@rareminds.in', NULL),
  ('Technical Manager', 'Manlift', 'Full-time', 'Noida', 'Offline', '10+', '["1.MEWP / Manlift Equipment", "2.Preventive Maintenance", "3.Breakdown Maintenance", "4.Mechanical Maintenance", "5.Electrical & Electronic Maintenance", "6.Hydraulic Systems"]'::jsonb, 'Manages & coordinates Engineers/technicians engaged in maintaining, servicing, and repairing Manlift Mobile Elevating Work Platforms
(MEWP’s) & related equipment. Drives the efficient execution and monitors the performance of the Manlift wide maintenance strategy,
spare planning, standards, processes, policies, and tools to optimize the availability for rental of all machines that are presented in safe,
reliable and esthetically in good condition.', '2026-04-20 00:00:00+00', FALSE, 'Production', 'Senior Executive', 1800000, 1800000, 'closed', '["1.Graduate/Post graduate or diploma in Engineering (Electrical/Mechanical/Automobile).", "2.Minimum 10 years of experience with at least 5 yearsin a Managerial/Supervisory role.", "3.Experience in the MEWPs, earthmoving equipment, Gen set industry, material handling equipment is necessary."]'::jsonb, '["Managesthe Workshop, yard and related cells (first check, repair line, painting denting, fabrication, Washing and ready line) in", "a manner that supports our best practise goals, related to Operational efficiency in the Manlift “Rental cycle”, Safety, Health,", "Environment and Quality standards, and our customers’ expectations."]'::jsonb, '["ESI, PF"]'::jsonb, 4, 'Technical Manager', NULL, 'krishna@rareminds.in', NULL),
  ('Graduate Engineer Trainee', 'Rollwell Conveyor Design Pvt Ltd', 'Full-time', 'Bengaluru', 'Offline', 'Fresher', '["AutoCAD", "SolidWorks", "Reading Engineering Drawings", "Solid Edge"]'::jsonb, 'Looking for a Fresher Mechanical Engineer to support the Engineering/Design/Proposals team in preparing and modifying engineering drawings, documentation, and project-related activities', '2026-09-15 00:00:00+00', TRUE, 'Production', 'Fresher', 250000, 250000, 'open', '["Experience: Fresher / 0–1 year", "Education: Diploma / B.E. / B.Tech in Mechanical Engineering", "Location: Bangalore", "Department: Engineering / Design / Proposals", "Good understanding of engineering and manufacturing drawings"]'::jsonb, '["1.Read, interpret and understand engineering/manufacturing drawings", "2.Prepare and modify 2D & 3D drawings using AutoCAD", "3.Assist in preparing GA, fabrication, assembly and detail drawings", "4.Coordinate with Design, Production and Project teams"]'::jsonb, '["N/A"]'::jsonb, 80, 'Graduate Engineer Trainee', NULL, 'krishna@rareminds.in', NULL),
  ('Coordinator (DM)', 'Teamlease', 'Contract', 'Gurgaon', 'Offline', '2+', '["1.Project Management", "2.Service Delivery", "3.Network Architecture", "4.LAN & WAN", "5.Networking / CCNA"]'::jsonb, 'Responsible for the successful delivery and deployment of network services at customer locations within agreed scope, quality, and timelines. The role involves coordinating with internal/external stakeholders, managing delivery milestones, risks, issues, migrations, and ensuring smooth transition to Operations and Billing.', '2026-10-09 00:00:00+00', TRUE, 'Operations', 'Executive', 600000, 1200000, 'open', '["Experience: 3+ years in Project Management / Service Delivery", "Education: Bachelor''s degree in Computer Science, IT, Networking, or related field", "Experience coordinating with cross-functional technical teams", "Experience managing customer and vendor relationships"]'::jsonb, '["1.Manage customer orders from acceptance through delivery and closure", "2.Track delivery milestones against agreed baselines and highlight deviations", "3.Monitor progress and proactively prevent delivery delays", "4.Coordinate with internal/external stakeholders to ensure right-first-time delivery", "5.Manage risks, issues, and escalations"]'::jsonb, '["N/A"]'::jsonb, 4, 'Coordinator (DM)', NULL, 'krishna@rareminds.in', NULL),
  ('Optometrist', 'Teamlease', 'Full-time', 'Bengaluru', 'Offline', '2+', '["1.Refraction", "2.Vision Assessment", "3.Eye Examination", "4.Subjective & Objective Refraction"]'::jsonb, 'We are looking for an experienced Optometrist to provide professional eye-care services, conduct comprehensive eye examinations, and recommend suitable lenses and eyewear based on customers'' visual requirements', '2026-10-09 00:00:00+00', TRUE, 'Pharma', 'Executive', 500000, 500000, 'open', '["1.Conduct comprehensive eye examinations and vision assessments for customers.", "2.Perform refraction and determine appropriate lens prescriptions.", "4.Identify common vision problems and recommend suitable corrective solutions.", "5.Assist customers in selecting appropriate lenses, frames and eyewear based on their requirements."]'::jsonb, '["Qualification: B.Optom / Bachelor of Optometry or equivalent.", "Experience: Minimum 2+ years of relevant experience.", "Experience in Optical Retail / Optometry / Eye Care preferred."]'::jsonb, '["ESI, PF"]'::jsonb, 4, 'Optometrist', NULL, 'krishna@rareminds.in', NULL);

COMMIT;
