export { default as AdmissionNoteModal } from './AdmissionNoteModal';
// Entity-level modals - now in correct location
export { default as SchoolAdmissionNoteModal } from './SchoolAdmissionNoteModal';
export { default as MessageModal } from './MessageModal';
export { default as ExportModal } from '../../modals/ExportModal';
export { default as ApprovalModal } from './ApprovalModal';
export { default as PromotionModal } from './PromotionModal';
export { default as GraduationModal } from './GraduationModal';
export { default as DocumentsModal } from './DocumentsModal';
