import { promises as fs } from 'fs';
import path from 'path';
import { 
  APIFunction, 
  FeatureMapping, 
  MigrationConfig, 
  MigrationLogger, 
  MigrationResult,
  MigrationError 
} from '../types';

/**
 * Handles the migration of API functions from services to feature directories
 * while preserving function signatures and behavior.
 */
export class APIFunctionMigrator {
  constructor(
    private config: MigrationConfig,
    private logger: MigrationLogger
  ) {}

  /**
   * Migrates feature-specific API functions to their appropriate directories
   */
  async migrateFeatureFunctions(mappings: FeatureMapping[]): Promise<MigrationResult> {
    const result: MigrationResult = {
      success: true,
      migratedFiles: [],
      updatedImports: [],
      errors: [],
      warnings: [],
      rollbackData: { backupId: '', backupPath: '', changes: [] }
    };

    try {
      for (const mapping of mappings) {
        await this.migrateFeatureMapping(mapping, result);
      }

      this.logger.info(`Successfully migrated ${result.migratedFiles.length} API files`);
      return result;

    } catch (error) {
      result.success = false;
      result.errors.push({
        type: 'migration',
        message: `Migration failed: ${error.message}`,
        file: '',
        details: { error: error.stack }
      });
      
      this.logger.error('API function migration failed', { error });
      return result;
    }
  }

  /**
   * Migrates a single feature mapping
   */
  private async migrateFeatureMapping(
    mapping: FeatureMapping, 
    result: MigrationResult
  ): Promise<void> {
    const targetDir = path.join(
      this.config.targetDirectory, 
      'features', 
      mapping.feature, 
      'api'
    );
    
    const targetFile = path.join(targetDir, `${mapping.feature}Api.ts`);

    try {
      // Group functions by their source file for better organization
      const functionsBySource = this.groupFunctionsBySource(mapping.functions);
      
      // Generate the migrated API file content
      const fileContent = await this.generateApiFileContent(
        mapping.feature, 
        functionsBySource
      );

      // Write the new API file
      await fs.writeFile(targetFile, fileContent, 'utf8');
      result.migratedFiles.push(targetFile);

      this.logger.info(`Migrated ${mapping.functions.length} functions to ${targetFile}`);

    } catch (error) {
      const migrationError: MigrationError = {
        type: 'file_write',
        message: `Failed to migrate functions for feature ${mapping.feature}`,
        file: targetFile,
        details: { error: error.message, functions: mapping.functions.map(f => f.name) }
      };
      
      result.errors.push(migrationError);
      result.success = false;
    }
  }

  /**
   * Groups functions by their original source file
   */
  private groupFunctionsBySource(functions: APIFunction[]): Map<string, APIFunction[]> {
    const groups = new Map<string, APIFunction[]>();
    
    for (const func of functions) {
      const sourceFile = func.sourceFile || 'unknown';
      if (!groups.has(sourceFile)) {
        groups.set(sourceFile, []);
      }
      groups.get(sourceFile)!.push(func);
    }
    
    return groups;
  }

  /**
   * Generates the content for a migrated API file
   */
  private async generateApiFileContent(
    feature: string, 
    functionsBySource: Map<string, APIFunction[]>
  ): Promise<string> {
    const imports = new Set<string>();
    const functionContents: string[] = [];

    // Process each source file group
    for (const [sourceFile, functions] of functionsBySource) {
      // Extract imports from original source
      const sourceImports = await this.extractImportsFromSource(sourceFile);
      sourceImports.forEach(imp => imports.add(imp));

      // Add functions with preserved signatures
      for (const func of functions) {
        const functionCode = await this.preserveFunctionSignature(func);
        functionContents.push(functionCode);
      }
    }

    // Generate file header
    const header = this.generateFileHeader(feature);
    
    // Generate imports section
    const importsSection = Array.from(imports).join('\n');
    
    // Generate functions section
    const functionsSection = functionContents.join('\n\n');

    return `${header}\n\n${importsSection}\n\n${functionsSection}\n`;
  }

  /**
   * Generates the file header with documentation
   */
  private generateFileHeader(feature: string): string {
    return `/**
 * ${feature.charAt(0).toUpperCase() + feature.slice(1)} API Functions
 * 
 * This file contains all API functions related to ${feature} functionality.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */`;
  }

  /**
   * Extracts import statements from the original source file
   */
  private async extractImportsFromSource(sourceFile: string): Promise<string[]> {
    try {
      if (!sourceFile || sourceFile === 'unknown') {
        return [];
      }

      const content = await fs.readFile(sourceFile, 'utf8');
      const imports: string[] = [];
      
      // Extract import statements using regex
      const importRegex = /^import\s+.*?from\s+['"][^'"]+['"];?\s*$/gm;
      let match;
      
      while ((match = importRegex.exec(content)) !== null) {
        imports.push(match[0].trim());
      }

      return imports;
    } catch (error) {
      this.logger.warn(`Could not extract imports from ${sourceFile}`, { error });
      return [];
    }
  }

  /**
   * Preserves the original function signature and behavior
   */
  private async preserveFunctionSignature(func: APIFunction): Promise<string> {
    try {
      // If we have the original source, extract the exact function
      if (func.sourceFile) {
        const originalContent = await fs.readFile(func.sourceFile, 'utf8');
        const extractedFunction = this.extractFunctionFromSource(originalContent, func);
        
        if (extractedFunction) {
          return extractedFunction;
        }
      }

      // Fallback: reconstruct function from metadata
      return this.reconstructFunction(func);
      
    } catch (error) {
      this.logger.warn(`Could not preserve original signature for ${func.name}`, { error });
      return this.reconstructFunction(func);
    }
  }

  /**
   * Extracts the exact function code from source content
   */
  private extractFunctionFromSource(content: string, func: APIFunction): string | null {
    // Try different function patterns
    const patterns = [
      // Regular function declaration
      new RegExp(`export\\s+(?:async\\s+)?function\\s+${func.name}\\s*\\([^)]*\\)[^{]*{[\\s\\S]*?^}`, 'm'),
      // Arrow function
      new RegExp(`export\\s+const\\s+${func.name}\\s*=\\s*(?:async\\s*)?\\([^)]*\\)\\s*=>\\s*{[\\s\\S]*?^};?`, 'm'),
      // Method in object
      new RegExp(`${func.name}\\s*:\\s*(?:async\\s*)?(?:function\\s*)?\\([^)]*\\)\\s*=>\\s*{[\\s\\S]*?^\\s*},?`, 'm')
    ];

    for (const pattern of patterns) {
      const match = content.match(pattern);
      if (match) {
        return match[0].trim();
      }
    }

    return null;
  }

  /**
   * Reconstructs function from metadata when original source is unavailable
   */
  private reconstructFunction(func: APIFunction): string {
    const params = func.parameters?.map(p => `${p.name}: ${p.type}`).join(', ') || '';
    const returnType = func.returnType || 'Promise<any>';
    
    return `/**
 * ${func.name} - Migrated from services
 * TODO: Implement function body from original source
 */
export const ${func.name} = async (${params}): ${returnType} => {
  // TODO: Migrate implementation from ${func.sourceFile || 'original service file'}
  throw new Error('Function ${func.name} needs implementation migration');
};`;
  }

  /**
   * Migrates shared API utilities to the shared directory
   */
  async migrateSharedFunctions(sharedFunctions: APIFunction[]): Promise<MigrationResult> {
    const result: MigrationResult = {
      success: true,
      migratedFiles: [],
      updatedImports: [],
      errors: [],
      warnings: [],
      rollbackData: { backupId: '', backupPath: '', changes: [] }
    };

    if (sharedFunctions.length === 0) {
      return result;
    }

    try {
      const sharedDir = path.join(this.config.targetDirectory, 'shared', 'api');
      
      // Group shared functions by category
      const categories = this.categorizeSharedFunctions(sharedFunctions);
      
      for (const [category, functions] of categories) {
        const targetFile = path.join(sharedDir, `${category}.ts`);
        const content = await this.generateSharedFileContent(category, functions);
        
        await fs.writeFile(targetFile, content, 'utf8');
        result.migratedFiles.push(targetFile);
      }

      this.logger.info(`Migrated ${sharedFunctions.length} shared functions to ${sharedDir}`);
      return result;

    } catch (error) {
      result.success = false;
      result.errors.push({
        type: 'migration',
        message: `Shared function migration failed: ${error.message}`,
        file: '',
        details: { error: error.stack }
      });
      
      return result;
    }
  }

  /**
   * Categorizes shared functions into logical groups
   */
  private categorizeSharedFunctions(functions: APIFunction[]): Map<string, APIFunction[]> {
    const categories = new Map<string, APIFunction[]>();
    
    for (const func of functions) {
      let category = 'utils';
      
      // Categorize based on function name patterns
      if (func.name.includes('http') || func.name.includes('request') || func.name.includes('client')) {
        category = 'httpClient';
      } else if (func.name.includes('auth') || func.name.includes('token')) {
        category = 'authUtils';
      } else if (func.name.includes('validate') || func.name.includes('format')) {
        category = 'validators';
      } else if (func.name.includes('constant') || func.name.includes('config')) {
        category = 'constants';
      }
      
      if (!categories.has(category)) {
        categories.set(category, []);
      }
      categories.get(category)!.push(func);
    }
    
    return categories;
  }

  /**
   * Generates content for shared utility files
   */
  private async generateSharedFileContent(category: string, functions: APIFunction[]): Promise<string> {
    const header = `/**
 * Shared ${category} utilities
 * 
 * Common ${category} functionality used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */`;

    const functionContents = await Promise.all(
      functions.map(func => this.preserveFunctionSignature(func))
    );

    return `${header}\n\n${functionContents.join('\n\n')}\n`;
  }
}