/** Generic table actions must satisfy the same grants as named operations. */
export const ADMIN_TABLE_FEATURES: Record<string, { read: readonly string[]; write: readonly string[] }> = {
  "achievements": {"read": ["digital_portfolio", "learner_verifications"], "write": ["digital_portfolio", "learner_verifications"]},
  "applied_jobs": {"read": ["events", "placement_status"], "write": ["events"]},
  "assessment_types": {"read": ["curriculum_builder"], "write": []},
  "assessments": {"read": ["exam_management", "reports_analytics"], "write": ["exam_management"]},
  "book_reservations": {"read": ["library"], "write": ["library"]},
  "book_reviews": {"read": ["library"], "write": ["library"]},
  "certificates": {"read": ["digital_portfolio", "learner_verifications"], "write": ["digital_portfolio", "learner_verifications"]},
  "circular_recipients": {"read": ["circulars"], "write": []},
  "circulars": {"read": ["circulars"], "write": ["circulars"]},
  "class_swap_history": {"read": ["faculty"], "write": []},
  "class_swap_requests": {"read": ["faculty"], "write": ["faculty"]},
  "college_assignments": {"read": ["program_sections"], "write": ["program_sections"]},
  "college_attendance_records": {"read": ["learner_attendance", "reports_analytics"], "write": []},
  "college_attendance_sessions": {"read": ["learner_attendance", "reports_analytics"], "write": ["learner_attendance"]},
  "college_breaks": {"read": ["events"], "write": ["events"]},
  "college_circulars": {"read": ["circulars"], "write": ["circulars"]},
  "college_classes": {"read": ["program_sections"], "write": ["program_sections"]},
  "college_course_mappings": {"read": ["course_mapping", "curriculum_builder", "faculty", "lesson_plans", "program_sections"], "write": ["course_mapping"]},
  "college_courses": {"read": ["course_mapping", "courses", "curriculum_builder", "learner_attendance"], "write": ["course_mapping", "curriculum_builder"]},
  "college_curriculum_outcomes": {"read": ["content_repository", "curriculum_builder", "lesson_plans", "syllabus_approval"], "write": ["curriculum_builder"]},
  "college_curriculum_status": {"read": ["curriculum_builder"], "write": []},
  "college_curriculum_units": {"read": ["content_repository", "curriculum_builder", "lesson_plans", "syllabus_approval"], "write": ["curriculum_builder"]},
  "college_curriculums": {"read": ["admissions_data", "content_repository", "curriculum_builder", "lesson_plans", "syllabus_approval"], "write": ["curriculum_builder"]},
  "college_event_registrations": {"read": ["events"], "write": ["events"]},
  "college_events": {"read": ["events"], "write": ["events"]},
  "college_faculty_class_assignments": {"read": ["program_sections"], "write": ["program_sections"]},
  "college_faculty_leave_balances": {"read": ["faculty"], "write": ["faculty"]},
  "college_faculty_leaves": {"read": ["faculty"], "write": ["faculty"]},
  "college_faculty_substitutions": {"read": ["faculty", "program_sections"], "write": ["faculty"]},
  "college_learner_assignments": {"read": ["program_sections"], "write": ["program_sections"]},
  "college_leave_types": {"read": ["faculty"], "write": []},
  "college_lecturers": {"read": ["course_mapping", "departments", "faculty", "learner_attendance", "learner_verifications", "mentors", "program_sections", "user_management"], "write": ["faculty", "user_management"]},
  "college_lesson_plans": {"read": ["lesson_plans"], "write": ["lesson_plans"]},
  "college_mentor_learner_allocations": {"read": ["mentors"], "write": ["mentors"]},
  "college_mentor_notes": {"read": ["mentors"], "write": ["mentors"]},
  "college_mentor_periods": {"read": ["mentors"], "write": ["mentors"]},
  "college_subject_attendance_summary": {"read": ["learner_attendance"], "write": []},
  "college_time_periods": {"read": ["program_sections"], "write": ["program_sections"]},
  "college_timetable_slots": {"read": ["faculty", "program_sections"], "write": ["program_sections"]},
  "college_timetables": {"read": ["program_sections"], "write": ["program_sections"]},
  "companies": {"read": ["reports_analytics"], "write": []},
  "conversations": {"read": ["learner_communication"], "write": []},
  "course_enrollments": {"read": ["basic_analytics", "reports_analytics"], "write": ["digital_portfolio"]},
  "course_mappings": {"read": ["faculty"], "write": []},
  "courses": {"read": ["basic_analytics", "courses", "reports_analytics"], "write": ["courses"]},
  "curriculum": {"read": ["content_repository", "curriculum_builder", "syllabus_approval"], "write": []},
  "curriculum_approval_dashboard": {"read": ["curriculum_builder"], "write": []},
  "curriculum_courses": {"read": ["curriculum_builder", "departments"], "write": ["curriculum_builder"]},
  "curriculum_units": {"read": ["content_repository", "syllabus_approval"], "write": []},
  "curriculums": {"read": ["curriculum_builder"], "write": ["curriculum_builder"]},
  "department_budgets": {"read": ["finance", "reports_analytics"], "write": ["finance"]},
  "department_faculty_assignments": {"read": ["course_mapping", "departments", "faculty", "program_sections"], "write": ["departments"]},
  "departments": {"read": ["course_mapping", "curriculum_builder", "departments", "enrolled_learners", "finance", "lesson_plans", "mentors", "program_sections", "programs", "reports_analytics", "user_management"], "write": ["departments"]},
  "digital_portfolios": {"read": ["digital_portfolios"], "write": []},
  "education": {"read": ["digital_portfolio", "learner_verifications"], "write": ["digital_portfolio", "learner_verifications"]},
  "exam_registrations": {"read": ["exam_management", "reports_analytics"], "write": ["exam_management"]},
  "exam_rooms": {"read": ["exam_management"], "write": ["exam_management"]},
  "exam_seating_arrangements": {"read": ["exam_management"], "write": ["exam_management"]},
  "exam_timetable": {"read": ["exam_management"], "write": ["exam_management"]},
  "exam_windows": {"read": ["exam_management", "reports_analytics"], "write": ["exam_management"]},
  "expenditures": {"read": ["finance"], "write": ["finance"]},
  "experience": {"read": ["digital_portfolio", "learner_verifications"], "write": ["learner_verifications"]},
  "fee_payments": {"read": ["finance"], "write": ["finance"]},
  "fee_structures": {"read": ["finance"], "write": ["finance"]},
  "invigilator_assignments": {"read": ["exam_management"], "write": ["exam_management"]},
  "issued_books": {"read": ["library"], "write": ["library"]},
  "learner_admissions": {"read": ["admissions_data"], "write": ["admissions_data"]},
  "learner_ledgers": {"read": ["fee_setup_payments", "finance"], "write": ["fee_setup_payments", "finance"]},
  "learners": {"read": ["admissions_data", "assessment_results", "basic_analytics", "departments", "digital_portfolio", "enrolled_learners", "events", "fee_setup_payments", "finance", "learner_attendance", "library", "library_assets", "mentors", "placement_status", "program_sections", "reports_analytics"], "write": ["admissions_data", "departments", "digital_portfolio", "program_sections"]},
  "library_book_issues": {"read": ["library"], "write": ["library"]},
  "library_book_issues_school": {"read": ["library_assets"], "write": ["library_assets"]},
  "library_books": {"read": ["library"], "write": ["library"]},
  "library_books_college": {"read": ["library"], "write": []},
  "library_books_school": {"read": ["library_assets"], "write": ["library_assets"]},
  "library_categories": {"read": ["library"], "write": ["library"]},
  "library_categories_school": {"read": ["library_assets"], "write": ["library_assets"]},
  "library_settings": {"read": ["library"], "write": ["library"]},
  "library_settings_school": {"read": ["library_assets"], "write": ["library_assets"]},
  "library_stats_school": {"read": ["library_assets"], "write": []},
  "mark_entries": {"read": ["admissions_data", "exam_management", "reports_analytics"], "write": ["exam_management"]},
  "mentor_note_conversations": {"read": ["mentors"], "write": []},
  "opportunities": {"read": ["events"], "write": []},
  "organization_users": {"read": ["user_management"], "write": []},
  "overdue_books": {"read": ["library"], "write": []},
  "overdue_books_school": {"read": ["library_assets"], "write": []},
  "payments": {"read": ["finance"], "write": ["finance"]},
  "personal_assessment_results": {"read": ["assessment_results"], "write": []},
  "pipeline_candidates": {"read": ["reports_analytics"], "write": []},
  "placement_offers": {"read": ["reports_analytics"], "write": []},
  "program_sections": {"read": ["basic_analytics", "curriculum_builder", "enrolled_learners", "program_sections", "programs"], "write": ["program_sections"]},
  "program_sections_view": {"read": ["learner_attendance"], "write": []},
  "programs": {"read": ["admissions_data", "course_mapping", "curriculum_builder", "departments", "enrolled_learners", "finance", "learner_attendance", "lesson_plans", "mentors", "program_sections", "programs"], "write": ["program_sections", "programs"]},
  "projects": {"read": ["digital_portfolio", "learner_verifications"], "write": ["digital_portfolio", "learner_verifications"]},
  "school_classes": {"read": ["admissions_data", "basic_analytics", "curriculum_builder", "program_sections"], "write": ["program_sections"]},
  "school_educator_class_assignments": {"read": ["program_sections"], "write": ["program_sections"]},
  "school_educators": {"read": ["curriculum_builder", "faculty", "library", "program_sections", "teachers"], "write": ["teachers"]},
  "school_fee_payments": {"read": ["fee_setup_payments"], "write": ["fee_setup_payments"]},
  "school_fee_structures": {"read": ["fee_setup_payments"], "write": ["fee_setup_payments"]},
  "shortlists": {"read": ["placement_status"], "write": []},
  "skills": {"read": ["digital_portfolio", "learner_verifications"], "write": ["digital_portfolio", "learner_verifications"]},
  "subject_outcomes": {"read": ["content_repository", "syllabus_approval"], "write": []},
  "timetable_conflicts": {"read": ["teacher_timetable"], "write": []},
  "timetable_entries": {"read": ["faculty"], "write": []},
  "timetable_slots": {"read": ["faculty", "teacher_timetable"], "write": ["teacher_timetable"]},
  "timetables": {"read": ["teacher_timetable"], "write": ["teacher_timetable"]},
  "trainings": {"read": ["digital_portfolio", "learner_verifications"], "write": ["learner_verifications"]},
  "university_colleges": {"read": ["basic_analytics", "curriculum_builder"], "write": []},
  "users": {"read": ["course_mapping", "curriculum_builder", "faculty", "library", "program_sections", "user_management"], "write": []},
  "v_learner_fee_ledger_detailed": {"read": ["finance"], "write": []},
  "video_portfolio": {"read": ["digital_portfolio"], "write": ["digital_portfolio"]},
};
