-- Generated from Rareminds_Pan_India_Fresher_Opportunity_Tracker 4.xlsx.
-- Source rows: 841; generated by scripts/generate-rareminds-opportunity-seed.cjs.
-- Final ownership reconciliation for all generated batches.
-- Idempotency key: company_name + job_title + location + application_link.
-- Static values are SQL-escaped by sqlText(); no runtime/user input is executed.

BEGIN;

-- If these migrations are rerun after local recruiter/user seeds have been loaded,
-- attach previously inserted tracker opportunities to Krishna without
-- changing ownership of unrelated opportunities.
WITH selected_recruiter AS (
  SELECT r.id AS recruiter_id, r.user_id AS created_by_uuid
  FROM public.recruiters r
  WHERE lower(r.email) IN (lower('krishna@rareminds.in'), lower('visakh@rareminds.in'))
     OR lower(r.name) LIKE '%rareminds%'
  ORDER BY
    CASE lower(r.email)
      WHEN lower('krishna@rareminds.in') THEN 0
      WHEN lower('visakh@rareminds.in') THEN 1
      ELSE 2
    END,
    CASE WHEN COALESCE(r.isactive, TRUE) THEN 0 ELSE 1 END,
    r.createdat NULLS LAST,
    r.id
  LIMIT 1
)
UPDATE public.opportunities o
SET recruiter_id = sr.recruiter_id,
    created_by = sr.created_by_uuid::text,
    created_by_uuid = sr.created_by_uuid,
    organization_id = COALESCE(
      u."organizationId",
      o.organization_id,
      (
        SELECT org.id
        FROM public.organizations org
        WHERE lower(org.name) = lower('Rareminds')
        ORDER BY org.created_at NULLS LAST, org.id
        LIMIT 1
      )
    ),
    updated_at = timezone('utc'::text, now())
FROM selected_recruiter sr
JOIN public.users u ON u.id = sr.created_by_uuid
WHERE position('careers@rareminds.in' in o.description) > 0;

COMMIT;
