export * from './ui';

// API & Data Access
export * from './api';
export { exportAsPDF } from './lib/exportppUtils';
export { copyToClipboard } from './lib/exportppUtils';
export { saveResumeToTables } from './api/resumeDataService';
export { exportAsJSON } from './lib/exportppUtils';
export { generateQRCode } from './lib/exportppUtils';
export { getCertificateProxyUrl } from './api/certificateService';
export { downloadCertificate } from './api/certificateService';
export { generateShareableLink } from './lib/exportppUtils';
export { getStudentPortfolioByEmail } from './api/portfolioService';
export { parseResumeWithAI } from './api/resumeParserService';
export { downloadQRCode } from './lib/exportppUtils';
export { getBadgeProgress } from './api/badgeService';
export { generateBadges } from './api/badgeService';
export { mergeResumeData } from './api/resumeParserService';
export { exportResume } from './lib/exportppUtils';
export { generateCourseCertificate } from './api/certificateService';
export { sharePortfolio } from './lib/exportppUtils';
export { exportAsHTML } from './lib/exportppUtils';
export type { ThemeToggle } from './ui/shared/ThemeToggle';
export type { CompactResumeDashboard } from './ui/portfolio/layouts/CompactResumeDashboard';
export type { JourneyMapLayout } from './ui/portfolio/layouts/JourneyMapLayout';
export type { CreativeLayout } from './ui/portfolio/layouts/CreativeLayout';
export type { BackgroundRippleEffect } from './ui/shared/background-ripple-effect';
export type { ProfileCompletionModal } from './ui/shared/ProfileCompletionModal';
export type { InfographicDashboard } from './ui/portfolio/layouts/InfographicDashboard';
export type { ModernLayout } from './ui/portfolio/layouts/ModernLayout';
export type { AIPersonaLayout } from './ui/portfolio/layouts/AIPersonaLayout';
export type { SplitScreenLayout } from './ui/portfolio/layouts/SplitScreenLayout';
export type { ProfileCompletionErrorBoundary } from './ui/shared/ProfileCompletionErrorBoundary';
