/**
 * Shared API utilities
 * 
 * Common API functionality used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */

/**
 * Validate email format
 */
export function validateEmail(email: string): { valid: boolean; sanitized?: string; code?: string } {
  if (!email || typeof email !== 'string') {
    return { valid: false, code: 'INVALID_EMAIL_FORMAT' };
  }

  const sanitized = email.trim().toLowerCase();
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  
  if (!emailRegex.test(sanitized)) {
    return { valid: false, code: 'INVALID_EMAIL_FORMAT' };
  }

  return { valid: true, sanitized };
}

/**
 * Validate password strength
 */
export function validatePassword(password: string): { valid: boolean; code?: string } {
  if (!password || typeof password !== 'string') {
    return { valid: false, code: 'PASSWORD_REQUIRED' };
  }

  if (password.length < 6) {
    return { valid: false, code: 'PASSWORD_TOO_WEAK' };
  }

  return { valid: true };
}

/**
 * Generate correlation ID for request tracking
 */
export function generateCorrelationId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Check if value is UUID format
 */
export function isUUID(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
}

/**
 * Format file size in human readable format
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes';
  
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}