/**
 * Shared authUtils utilities
 * 
 * Common authUtils functionality used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */

import { validateEmail, validatePassword, generateCorrelationId } from './apiUtils';

/**
 * Validate user credentials
 */
export function validateCredentials(email: string, password: string): {
  valid: boolean;
  email?: string;
  code?: string;
  field?: string;
} {
  const emailValidation = validateEmail(email);
  if (!emailValidation.valid) {
    return { valid: false, code: emailValidation.code, field: 'email' };
  }

  const passwordValidation = validatePassword(password);
  if (!passwordValidation.valid) {
    return { valid: false, code: passwordValidation.code, field: 'password' };
  }

  return { valid: true, email: emailValidation.sanitized };
}

/**
 * Build standardized error response
 */
export function buildErrorResponse(code: string, options: { 
  field?: string; 
  customMessage?: string 
} = {}) {
  return {
    success: false,
    user: null,
    error: options.customMessage || getErrorMessage(code),
    errorCode: code,
    correlationId: generateCorrelationId(),
    field: options.field
  };
}

/**
 * Get user-friendly error message
 */
function getErrorMessage(code: string): string {
  const messages: Record<string, string> = {
    'INVALID_EMAIL_FORMAT': 'Please enter a valid email address.',
    'PASSWORD_REQUIRED': 'Password is required.',
    'PASSWORD_TOO_WEAK': 'Password must be at least 6 characters long.',
    'INVALID_CREDENTIALS': 'Invalid email or password.',
    'RATE_LIMITED': 'Too many attempts. Please try again later.',
  };

  return messages[code] || 'An error occurred. Please try again.';
}