import { ssoClient } from '@/shared/api/ssoClient';
/**
 * Shared HTTP Client utilities
 * 
 * Common HTTP client functionality used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */


import { getLogger } from '@/shared/config/logging';

const logger = getLogger('http-client');

// HTTP client configuration
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Lazy validation flag to prevent module-level crashes
let environmentValidated = false;

/**
 * Validates required environment variables
 * Called lazily on first HTTP request instead of at module load
 * This prevents app crashes when .env is missing during development
 */
function validateEnvironment(): void {
  if (environmentValidated) return;

  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    throw new Error(
      'Missing required Supabase environment variables. ' +
      'Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in your .env file.'
    );
  }

  environmentValidated = true;
}

// Common request timeout
export const DEFAULT_TIMEOUT = 30000; // 30 seconds

/**
 * Common HTTP request configuration
 */
export const defaultHeaders = {
  'Accept': 'application/json',
  'Content-Type': 'application/json',
};

/**
 * Create authenticated headers with token
 */
export async function createAuthHeaders(customHeaders: Record<string, string> = {}): Promise<Record<string, string>> {
  // Validate environment variables on first API call
  validateEnvironment();

  const headers: Record<string, string> = {
    ...defaultHeaders,
    ...customHeaders,
  };

  const token = ssoClient.getAccessToken();
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  return headers;
}

/**
 * Generic HTTP request wrapper with error handling
 */
export async function makeRequest<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  // Validate environment variables on first API call
  validateEnvironment();

  const response = await ssoClient.fetch(url, {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options.headers,
    },
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Authenticated HTTP request wrapper
 */
export async function makeAuthenticatedRequest<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  const authHeaders = await createAuthHeaders(options.headers as Record<string, string>);

  return makeRequest<T>(url, {
    ...options,
    headers: authHeaders,
  });
}

/**
 * Request with timeout
 */
export async function requestWithTimeout<T>(
  url: string,
  options: RequestInit = {},
  timeout: number = DEFAULT_TIMEOUT
): Promise<T> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await makeRequest<T>(url, {
      ...options,
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    throw error;
  }
}