import { ssoClient } from '@/shared/api/ssoClient';
/**
 * Shared HTTP Client utilities
 * 
 * Common HTTP client functionality used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */


import { getLogger } from '@/shared/config/logging';

const logger = getLogger('http-client');

// Common request timeout
export const DEFAULT_TIMEOUT = 30000; // 30 seconds

/**
 * Common HTTP request configuration
 */
export const defaultHeaders = {
  'Accept': 'application/json',
  'Content-Type': 'application/json',
};

/**
 * Create authenticated headers with token
 * @deprecated Use ssoClient.fetch / apiClient.apiPost which attach Bearer via authClient vault + replay guard.
 * This helper is kept for legacy callers but will NOT inject Authorization (vault is private).
 * Migrate to makeRequest/makeAuthenticatedRequest → ssoClient.fetch path.
 */
export async function createAuthHeaders(customHeaders: Record<string, string> = {}): Promise<Record<string, string>> {
  validateEnvironment();
  // Do NOT manually inject Bearer - authClient.request attaches it from vault atomically with refresh/replay logic.
  // Returning only default headers forces callers to use ssoClient.fetch path below.
  return {
    ...defaultHeaders,
    ...customHeaders,
  };
}

/**
 * Generic HTTP request wrapper with error handling
 */
export async function makeRequest<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  // Validate environment variables on first API call
  validateEnvironment();

  const response = await ssoClient.fetch(url, {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options.headers,
    },
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Authenticated HTTP request wrapper
 * Uses ssoClient.fetch so vault + refresh + replay + X-RM-CSRF are applied correctly.
 * withAuth Pages Functions require Authorization: Bearer from vault - never plain fetch.
 */
export async function makeAuthenticatedRequest<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  validateEnvironment();
  const response = await ssoClient.fetch(url, {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options.headers,
    },
  });
  if (!response.ok) {
    const body = await response.json().catch(() => ({} as Record<string, unknown>));
    const msg = (body as { error?: { message?: string } })?.error?.message ?? `HTTP ${response.status}: ${response.statusText}`;
    throw new Error(msg);
  }
  return response.json() as Promise<T>;
}

/**
 * Request with timeout
 */
export async function requestWithTimeout<T>(
  url: string,
  options: RequestInit = {},
  timeout: number = DEFAULT_TIMEOUT
): Promise<T> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await makeRequest<T>(url, {
      ...options,
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    throw error;
  }
}