/**
 * Shared HTTP Client utilities
 * 
 * Common HTTP client functionality used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */

import { supabase } from './supabaseClient';
import { getLogger } from '@/shared/config/logging';

const logger = getLogger('http-client');

// HTTP client configuration
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || import.meta.env.VITE_EXTERNAL_API_KEY;
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate required environment variables
if (!API_BASE_URL) {
  logger.warn('API_BASE_URL not configured. Set VITE_API_BASE_URL or VITE_EXTERNAL_API_KEY');
}
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing required Supabase environment variables');
}

// Common request timeout
export const DEFAULT_TIMEOUT = 30000; // 30 seconds

/**
 * Common HTTP request configuration
 */
export const defaultHeaders = {
  'Accept': 'application/json',
  'Content-Type': 'application/json',
};

/**
 * Create authenticated headers with token
 */
export async function createAuthHeaders(customHeaders: Record<string, string> = {}): Promise<Record<string, string>> {
  const { data: { session } } = await supabase.auth.getSession();
  
  const headers = {
    ...defaultHeaders,
    ...customHeaders,
  };

  if (session?.access_token) {
    headers['Authorization'] = `Bearer ${session.access_token}`;
  }

  return headers;
}

/**
 * Generic HTTP request wrapper with error handling
 */
export async function makeRequest<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  const response = await fetch(url, {
    ...options,
    headers: {
      ...defaultHeaders,
      ...options.headers,
    },
  });

  if (!response.ok) {
    throw new Error(`HTTP ${response.status}: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Authenticated HTTP request wrapper
 */
export async function makeAuthenticatedRequest<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  const authHeaders = await createAuthHeaders(options.headers as Record<string, string>);
  
  return makeRequest<T>(url, {
    ...options,
    headers: authHeaders,
  });
}

/**
 * Request with timeout
 */
export async function requestWithTimeout<T>(
  url: string,
  options: RequestInit = {},
  timeout: number = DEFAULT_TIMEOUT
): Promise<T> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeout);

  try {
    const response = await makeRequest<T>(url, {
      ...options,
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    return response;
  } catch (error) {
    clearTimeout(timeoutId);
    throw error;
  }
}