/**
 * Shared API types
 * 
 * Common type definitions used across multiple features.
 * Migrated from /services/ directory following FSD architecture.
 * 
 * @generated by FSD Phase 5 Migration
 */

// Common API Response structure
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

// Authentication types
export interface AuthResult {
  success: boolean;
  user?: any;
  role?: string;
  session?: any;
  error?: string;
}

// File upload types
export interface FileUploadResult {
  success: boolean;
  url?: string;
  key?: string;
  error?: string;
}

// Pagination types
export interface PaginationParams {
  page?: number;
  limit?: number;
  offset?: number;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Error types
export interface ApiError {
  code: string;
  message: string;
  details?: any;
}

// Request options
export interface RequestOptions {
  timeout?: number;
  retries?: number;
  headers?: Record<string, string>;
}